### ISSUE TITLE
`NullPointerException` caused by sending GET request with `Content-Type=application/xml` header

### ISSUE THREAD

**Issue by dreamingo88** [actframework/actframework#1008]
crud cannot work with Content-Type=application/xml.
Error:::::::::

2018-12-04 16:15:15,823 ERROR a.Act@[XNIO-1 task-3] - Action execute failed at [org.osgl.util.E.unexpected(E.java:189)].
2018-12-04 16:15:15,824 ERROR a.Act@[XNIO-1 task-3] - Error is: org.osgl.exception.UnexpectedException: java.lang.NullPointerException
        at org.osgl.util.E.unexpected(E.java:189)
        at org.osgl.util.XML.read(XML.java:106)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.patchedJsonBody(ReflectedHandlerInvoker.java:763)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.ensureJsonDtoGenerated(ReflectedHandlerInvoker.java:723)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:571)
        at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
        at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:555)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:212)
        at act.app.ActionContext.proceedWithHandler(ActionContext.java:1304)
        at act.route.Router$ContextualHandler.handle(Router.java:1671)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:165)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.osgl.util.IO.inputStream(IO.java:1199)
        at org.osgl.util.XML.read(XML.java:104)
        ... 12 more

**Comment by greenlaw110** [comment]
@dreamingo88 you should use `Accept=application/xml`:

![image](https://user-images.githubusercontent.com/216930/49608862-f226e200-f9ed-11e8-8bbf-87986ebe8253.png)

**Comment by greenlaw110** [comment]
However I should fix the NPE issue caused by `null` body in this case
