### ISSUE TITLE
ajax请求拦截后重定向到登录页面，登录页面不会正常渲染。而是把render模板的参数以json方式输出

### ISSUE THREAD

**Issue by pcmanjack** [actframework/actframework#1038]
应用之前版本1.8.1 升级至 1.8.17后 不知何种原因会导致 java.lang.StackOverflowError 错误，并且服务器会直接down掉
错误信息：
```
2018-12-28 13:42:43.425 [XNIO-1 task-5] ERROR act.xio.NetworkHandler - Fatal Error encountered handling request: 
java.lang.StackOverflowError: null
	at java.lang.ThreadLocal.get(ThreadLocal.java:161)
	at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:229)
	at sun.nio.ch.IOUtil.write(IOUtil.java:130)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at org.xnio.nio.NioSocketConduit.write(NioSocketConduit.java:184)
	at io.undertow.server.protocol.http.HttpResponseConduit.write(HttpResponseConduit.java:647)
	at io.undertow.conduits.ChunkedStreamSinkConduit.doWrite(ChunkedStreamSinkConduit.java:165)
	at io.undertow.conduits.ChunkedStreamSinkConduit.write(ChunkedStreamSinkConduit.java:127)
	at org.xnio.conduits.ConduitStreamSinkChannel.write(ConduitStreamSinkChannel.java:150)
	at io.undertow.channels.DetachableStreamSinkChannel.write(DetachableStreamSinkChannel.java:240)
	at io.undertow.server.HttpServerExchange$WriteDispatchChannel.write(HttpServerExchange.java:2105)
	at io.undertow.io.UndertowOutputStream.writeBufferBlocking(UndertowOutputStream.java:296)
	at io.undertow.io.UndertowOutputStream.flush(UndertowOutputStream.java:278)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at com.alibaba.fastjson.serializer.SerializeWriter.flush(SerializeWriter.java:2500)
	at com.alibaba.fastjson.serializer.SerializeWriter.write(SerializeWriter.java:284)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:420)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:137)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:313)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:454)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:137)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:313)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:454)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:137)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:313)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:454)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:137)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:313)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:454)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:160)
	at com.alibaba.fastjson.serializer.ListSerializer.write(ListSerializer.java:137)
```

**Comment by pcmanjack** [comment]
暂时无法重现。正在找重现的方法。

**Comment by pcmanjack** [comment]
补充：服务挂掉后，系统进程未杀死。但是pid文件也删除了。此时重新启动服务会导致上次的服务进程也存在。

**Comment by pcmanjack** [comment]
问题找到了
当用户登录失效后拦截器会拦截请求并且重定向到登录页面。
但是当请求为ajax请求的时候，登录页面不会render到正确的页面，而是把render到页面上的参数以json字符串的方式返回给用户。
相关代码：
拦截器：
```
if (StringUtils.isBlank(userId) || StringUtils.isBlank(userName) || StringUtils.isBlank(sessionId)) {
            if (!"/".equals(fullPath) && !"/index".equals(fullPath)) {
                session.clear();
                throw Controller.Util.redirect("/login");
            } else {
                session.put("user_id", null);
            }
 }
```
登录页面：
```
@GetAction("/login")
    public Result loginIndex(H.Request request, H.Session session) {

        SystemConfigModel systemConfigModel = loginService.getSystemConfig();

        String viewId = BeetlView.ID;
        return render("/m/login", systemConfigModel, viewId);

    }
```

**Comment by greenlaw110** [comment]
@pcmanjack 参见 https://github.com/actframework/act-doc/blob/master/cn/controller.md#641-ajax-%E9%87%8D%E5%AE%9A%E5%90%91

**Comment by pcmanjack** [comment]
> @pcmanjack 参见 https://github.com/actframework/act-doc/blob/master/cn/controller.md#641-ajax-%E9%87%8D%E5%AE%9A%E5%90%91

嗯。get到了。但是我提的这个bug是通过这个拦截发现的。实际上影响比较严重。之前在群里跟你讨论过。主要会导致两个问题。
1、一个普通的页面路由我显式的return render("页面","参数")，但是当我使用ajax请求后，会把“参数”直接以json的方式输出来。此时。当我的“参数”中有敏感数据 会被直接输出（此问题可以使用@ResponseContentType(H.MediaType.HTML)注解 解决）
2、 上面的那个java.lang.StackOverflowError错误就是我的数据库类使用了关联。然后当以json格式输出的时候导致了java.lang.StackOverflowError错误。并且会导致act服务器直接挂掉（此bug比较严重。应该报500错误。服务不应该挂掉。）

**Comment by greenlaw110** [comment]
@pcmanjack 如果应用知道数据有可能关联的情况下,应该在请求处理方法上使用 `@EnableCircularReferenceDetect` 注解

**Comment by pcmanjack** [comment]
> @pcmanjack 如果应用知道数据存在循环引用的可能, 就应该在请求处理方法上使用 `@EnableCircularReferenceDetect` 注解

好的。又get到了一个知识点

**Comment by greenlaw110** [comment]
@pcmanjack 那你这个 issue 就不是问题了, 可以关闭了吧

**Comment by greenlaw110** [comment]
@pcmanjack 我先把 issue 关了,如果你还有问题,麻烦提一个新的 issue
