### ISSUE TITLE
Error enhancing class with `@Data` annotation

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1049]
Source code:

```java
@Data
public class QuotePolicyBase extends UcModelBase {
    public Integer clientId;
    public Integer productId;
    public String clientName;
    public String effectiveDate;
    public JSONObject needs;
}
```

Error stack:

```
2019-02-07 12:54:04,031 ERROR a.a.App@[jobs-thread-2] - Bad enhanced class encountered, asm code dumped to 
	>>/home/luog/p/underwriter/svc/target/tmp/bytes/com.pixolut.underwriter.model.Policy.java
2019-02-07 12:54:04,035 ERROR a.a.App@[jobs-thread-2] - Block issue encountered
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/pixolut/underwriter/model/QuotePolicyBase.hashCode()I @27: invokestatic
  Reason:
    Type 'java/lang/Integer' (current frame, stack[5]) is not assignable to '[Ljava/lang/Object;'
  Current Frame:
    bci: @27
    flags: { }
    locals: { 'com/pixolut/underwriter/model/QuotePolicyBase' }
    stack: { 'java/lang/Integer', 'java/lang/Integer', 'java/lang/String', 'java/lang/String', 'com/alibaba/fastjson/JSONObject', 'java/lang/Integer' }
  Bytecode:
    0x0000000: 2ab4 001c 2ab4 001f 2ab4 0023 2ab4 0026
    0x0000010: 2ab4 0018 2ab7 003c b800 42b8 0046 ac  

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.osgl.Lang.classForName(Lang.java:7365)
	at act.app.App.classForName(App.java:1173)
	...
```

The generated asm code:

```
hashCode()I
   L0
    LINENUMBER 29 L0
    ALOAD 0
    INVOKEVIRTUAL java/lang/Object.getClass ()Ljava/lang/Class;
    ALOAD 0
    INVOKEVIRTUAL com/pixolut/underwriter/model/Policy.getPolicyId ()Ljava/lang/Integer;
    INVOKESTATIC org/osgl/$.hc (Ljava/lang/Object;Ljava/lang/Object;)I
    IRETURN
   L1
```

**Comment by greenlaw110** [comment]
Specifically this issue is caused because of `public JSONObject needs` field

**Comment by greenlaw110** [comment]
Actually this issue only happens when there are exactly 5 fields

**Comment by greenlaw110** [comment]
Okay, specifically, the issue is triggered exactly:
1. there are exactly 5 fields
2. the class has a super class and the framework decide it should call super class hash code. In this case because super class `UcModelBase` is an AdaptiveBean, thus framework decide to call `super.hashCode()`.
