### ISSUE TITLE
metric command stop working

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1058]
in the CLI issuing `act.metric.timer.list` triggers the following exception:

```
java.lang.IllegalAccessError: act/metric/MetricAdmin$1
	at act.metric.MetricAdmin.withoutClassLoading(MetricAdmin.java:82)
	at act.metric.MetricAdmin.getCounters(MetricAdmin.java:60)
	at act.metric.MetricAdminMethodAccess.invoke(Unknown Source)
	at act.cli.bytecode.ReflectedCommandExecutor.invoke(ReflectedCommandExecutor.java:200)
	at act.cli.bytecode.ReflectedCommandExecutor.execute(ReflectedCommandExecutor.java:149)
	at act.handler.builtin.cli.CliHandlerProxy._handle(CliHandlerProxy.java:147)
	at act.handler.builtin.cli.CliHandlerProxy.handle(CliHandlerProxy.java:83)
	at act.cli.CliContext.handle(CliContext.java:426)
	at act.cli.CliSession.run(CliSession.java:189)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
There are actually more than the class loading error, the maven-archetype project's logback.xml file needs to be tuned also
