### ISSUE TITLE
LinkageError due to `org.w3c.dom.Document` Class Object conflict

### ISSUE THREAD

**Issue by pcmanjack** [actframework/actframework#1061]
The product service (running on act-1.8.17) was broken suddenly with the following error stack in the log file:

```
2019-02-18 17:54:20.140 [XNIO-1 task-374] ERROR act.xio.NetworkHandler - Error handling network request
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "<a"
        at java.net.URLDecoder.decode(URLDecoder.java:194)
        at org.osgl.util.Codec.decodeUrl(Codec.java:241)
        at act.session.DefaultSessionCodec.resolveFromCookieContent(DefaultSessionCodec.java:110)
        at act.session.DefaultSessionCodec.decodeSession(DefaultSessionCodec.java:92)
        at act.session.SessionManager.resolveSession(SessionManager.java:61)
        at act.app.ActionContext.resolveSession(ActionContext.java:1504)
        at act.app.ActionContext.resolve(ActionContext.java:1281)
        at act.route.Router$ContextualHandler.handle(Router.java:1668)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:165)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-02-18 17:55:18.404 [XNIO-1 task-231] ERROR act.xio.NetworkHandler - Fatal Error encountered handling request: 
java.lang.LinkageError: loader constraint violation: when resolving method "org.osgl.util.XML.read(Ljava/lang/String;)Lorg/w3c/dom/Document;" the class loader (instance of act/boot/app/FullStackAppBootstrapClassLoader) of the current class, act/handler/builtin/controller/impl/ReflectedHandlerInvoker, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/osgl/util/XML, have different Class objects for the type org/w3c/dom/Document used in the signature
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.patchedJsonBody(ReflectedHandlerInvoker.java:791)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.ensureJsonDtoGenerated(ReflectedHandlerInvoker.java:736)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:584)
        at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
        at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:559)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:213)
        at act.app.ActionContext.proceedWithHandler(ActionContext.java:1304)
        at act.route.Router$ContextualHandler.handle(Router.java:1673)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:165)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-02-18 17:55:18.405 [Thread-14] INFO  act.app.App - App shutting down ....
```

**Comment by greenlaw110** [comment]
Cannot reproduce. However checkout this link: https://community.atlassian.com/t5/Answers-Developer-Questions/How-to-remedy-linkage-error-for-org-w3c-dom-Element-when/qaq-p/558802

I suspect it is caused by the same root cause, i.e. some jar files in your project dependency has `org.w3c.doc.Document` class inside, which should be loaded from the JDK's `rt.jar` file. @pcmanjack try to locate your dependency jar files and see if you get find it.

**Comment by greenlaw110** [comment]
This issue can be reproduced. It is superseded by #1096
