### ISSUE TITLE
Error encountered with customised Unique validator when working with JPA

### ISSUE THREAD

**Issue by moonmanbu** [actframework/actframework#1069]
The annotation:

```java
@ReportAsSingleViolation
@Constraint(validatedBy = UniqueValidator.class)
@Target({ElementType.FIELD, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface Unique {

    String message() default "{org.hibernate.validator.constraints.Length.message}";

    Class<?> entity();

    Class<?>[] groups() default { };

    Class<? extends Payload>[] payload() default { };
}
```

The validator:

```java
public class UniqueValidator implements ConstraintValidator<Unique, Object> {

    private Dao dao;

    @Override
    public void initialize(Unique parameters) {
        Class<?> cls = parameters.entity();
        dao = App.instance().dbServiceManager().dao(cls);
    }

    @Override
    public boolean isValid(Object value, ConstraintValidatorContext context) {
        if (value == null) {
            return true;
        }
        if (dao != null && context instanceof ConstraintValidatorContextImpl) {
            ConstraintValidatorContextImpl contextImpl = (ConstraintValidatorContextImpl) context;
            ConstraintViolationCreationContext ctx = contextImpl.getConstraintViolationCreationContexts().get(0);
            String fieldName = ctx.getPath().getLeafNode().getName();

            return dao.countBy(fieldName, value) <= 0;
        }
        return false;
    }
}
```

The entity:

```java
@Entity
public class Department extends BaseModel {

    @Unique(entity = Department.class)
    public String name;
    ....
}
```

The request handler method:

```java
    @PostAction
    public Department create(Department department) {
        return departmentDao.save(department);
    }
```

When id generation strategy is:

```java
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long id;
```

It raises the following error stack:

```
2019-02-24 17:46:44,324 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-3] - error handling request: [POST]/api/v1/departments
javax.validation.ConstraintViolationException: Validation failed for classes [cc.topush.model.Department] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{rootBean=cc.topush.model.Department@1427c17, propertyPath='name', message='{org.hibernate.validator.constraints.Length.message}', leafBean=cc.topush.model.Department@1427c17, value=testname}
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:138)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:78)
	at org.hibernate.action.internal.EntityIdentityInsertAction.preInsert(EntityIdentityInsertAction.java:197)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:75)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:626)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:280)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:261)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:306)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:67)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:778)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:751)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:756)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1146)
	at act.db.jpa.JPADao._save(JPADao.java:146)
	at act.db.jpa.JPADao.save(JPADao.java:140)
	at cc.topush.service.v1.DepartmentService.create(DepartmentService.java:67)
	at cc.topush.service.v1.DepartmentServiceMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1038)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1024)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:663)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:559)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:213)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1308)
	at act.route.Router$ContextualHandler.handle(Router.java:1714)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

When using customized id generation strategy, e.g. the snowflake:

```java
    @GeneratedValue(generator = "snowflake")
    @GenericGenerator(
            name = "snowflake",
            strategy = "cc.topush.algo.SnowflakeIdGenerator",
            parameters = {
                    @Parameter(name = "datacenterId", value = "3"),
                    @Parameter(name = "workerId", value = "2")
            })
    public long id;
```

Then it will raise StackOverflowError in `UniqueValidator#isValid()` method at:

```java
 return dao.countBy(fieldName, value) <= 0;
```

**Comment by moonmanbu** [comment]
```java
    @PostAction
    public Department create(Department department) {
        return departmentDao.save(department);
    }
```
```
save过程中, 当UniqueValidator#isValid() == false, 验证不能通过时会触发
org.hibernate.cfg.beanvalidation.BeanValidationEventListener#validate()中的ConstraintViolationException异常
```
异常栈
```
javax.validation.ConstraintViolationException: Validation failed for classes [cc.topush.model.Department] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{rootBean=cc.topush.model.Department@1eafb8b, propertyPath='name', message='不能重复', leafBean=cc.topush.model.Department@1eafb8b, value=testname}
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:138)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:78)
	at org.hibernate.action.internal.EntityIdentityInsertAction.preInsert(EntityIdentityInsertAction.java:197)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:75)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:626)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:280)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:261)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:306)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:67)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:778)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:751)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:756)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1146)
	at act.db.jpa.JPADao._save(JPADao.java:146)
	at act.db.jpa.JPADao.save(JPADao.java:140)
	at cc.topush.service.v1.DepartmentService.create(DepartmentService.java:67)
	at cc.topush.service.v1.DepartmentServiceMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1038)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1024)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:663)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:559)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:213)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1308)
	at act.route.Router$ContextualHandler.handle(Router.java:1714)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by greenlaw110** [comment]
@moonmanbu 这个异常是 hibernate 检查 Bean 有效性时触发的, 你觉得系统正确的反应应该是什么"?

**Comment by moonmanbu** [comment]
我觉得应该是在update的时同时又从数据库read时导致的

**Comment by greenlaw110** [comment]
@moonmanbu 这样吧, 你把问题总结一下, 按照下面的格式:

1. 重现执行步骤

2. 期望看到的结果

3. 实际看到的结果

**Comment by moonmanbu** [comment]
@greenlaw110
1. 重现执行步骤
```java
// 自定义@Unique注解的验证器
public class UniqueValidator implements ConstraintValidator<Unique, Object> {
    @Override
    public void initialize(Unique parameters) {
    }

    @Override
    public boolean isValid(Object value, ConstraintValidatorContext context) {
        if (value == null) {
            return false;
        }
        if (context instanceof ConstraintValidatorContextImpl) {
            GroupValidationContext<?> validationContext = ((ConstraintValidatorContextImpl) context).getValidationContext();
            Class<?> modelClass = validationContext.getCurrentOwner();
            Dao dao = App.instance().dbServiceManager().dao(modelClass);
            if (dao != null) {
                String fieldName = validationContext.getPropertyName();
                return dao.countBy(fieldName, value) <= 0;
            }
        }
        return true;
    }
}

// 自定义@Unique注解
/**
 * 从数据库查询是否唯一
 */
@Constraint(validatedBy = UniqueValidator.class)
@Target({FIELD, METHOD})
@NotBlank
@Retention(RetentionPolicy.RUNTIME)
public @interface Unique {

    String message() default "{javax.validation.constraints.Unique.message}";

    Class<?>[] groups() default { };

    Class<? extends Payload>[] payload() default { };

}

// entity
@Entity
public class Department  {
    @Unique
    public String name;
}

// 控制器使用
    @PostAction
    public Department create(@Valid Department department) {
        return departmentDao.save(department);
    }
```
2. 期望看到的结果
请求体为
```JavaScript
{
	"name": "主要单位"
}
```
当提交的数据在数据库中不唯一时, 即@Unique的验证不通过, 返回
```javascript
{
    "ts": 1553568554458,
    "message": "department.name: 不能重复"
}
```
3. 实际看到的结果
分两种情况
控制器这么写是, 即@Valid注解放在参数上
```java
    @PostAction
    public Department create(@Valid Department department) {
        return departmentDao.save(department);
    }
```
可以得到期望的结果, 及在dao.save之前已经进行了验证
当控制器如下写法时, 即参数上无@Valid注解
```java
    @PostAction
    public Department create(Department department) {
        return departmentDao.save(department);
    }
```
则验证将在dao.save过程中触发, 因为@Uniqe验证需要到数据库进行查询, 结果会弹出如下异常
```
javax.validation.ConstraintViolationException: Validation failed for classes [cc.topush.model.Department] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{rootBean=cc.topush.model.Department@bd442a, propertyPath='name', message='不能重复', leafBean=cc.topush.model.Department@bd442a, value=主要单位}
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:138)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:78)
	at org.hibernate.action.internal.EntityIdentityInsertAction.preInsert(EntityIdentityInsertAction.java:197)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:75)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:626)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:280)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:261)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:306)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:67)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:778)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:751)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:756)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1146)
	at act.db.jpa.JPADao._save(JPADao.java:146)
	at act.db.jpa.JPADao.save(JPADao.java:140)
	at cc.topush.service.v1.DepartmentService.create(DepartmentService.java:51)
	at cc.topush.service.v1.DepartmentServiceMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1038)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1024)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:663)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:559)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:213)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1308)
	at act.route.Router$ContextualHandler.handle(Router.java:1714)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
相应结果为
```JavaScript
{
    "ts": 1553568940102,
    "message": "调用请求处理器 cc.topush.service.v1.DepartmentService.create 时发生错误: 错误请求"
}
```
而非期望得到的
```javascript
{
    "ts": 1553568554458,
    "message": "department.name: 不能重复"
}
```

**Comment by moonmanbu** [comment]
@greenlaw110 
对现有实体进行更新并触发validator时还会包之前的异常
```
action: PUT http://192.168.56.1:5460/api/v1/departments/1
body:
{
    name: "some exists name"
}
```
response
```
{
    "ts": 1554339391532,
    "message": "调用请求处理器 cc.topush.service.v1.DepartmentService.update 时发生错误: 服务器错误"
}
```
异常栈
```
2019-04-04 08:56:31,531 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-4] - Server error encountered on handling request: [PUT]/api/v1/departments/1
javax.persistence.RollbackException: Error while committing the transaction
	at org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:87)
	at act.db.jpa.JPAContext._exitTxScope(JPAContext.java:152)
	at act.db.jpa.JPAContext.releaseResources(JPAContext.java:85)
	at act.util.DestroyableBase.destroy(DestroyableBase.java:53)
	at act.db.jpa.JPAContext.close(JPAContext.java:280)
	at act.db.jpa.JPAPlugin$5.on(JPAPlugin.java:92)
	at act.db.jpa.JPAPlugin$5.on(JPAPlugin.java:88)
	at act.event.EventBus.callOn(EventBus.java:1440)
	at act.event.EventBus.callOn(EventBus.java:1462)
	at act.event.EventBus.callOn(EventBus.java:1497)
	at act.event.EventBus._emitWithOnceBus(EventBus.java:1413)
	at act.event.EventBus.emit(EventBus.java:975)
	at act.handler.event.ResultEvent$1.apply(ResultEvent.java:62)
	at act.handler.event.ResultEvent$1.apply(ResultEvent.java:56)
	at org.osgl.mvc.MvcConfig.applyBeforeCommitResultHandler(MvcConfig.java:195)
	at org.osgl.mvc.result.Result.applyBeforeCommitHandler(Result.java:233)
	at org.osgl.mvc.result.RenderContent.apply(RenderContent.java:251)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:332)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:229)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1352)
	at act.route.Router$ContextualHandler.handle(Router.java:1714)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.validation.ConstraintViolationException: Validation failed for classes [cc.topush.model.Department] during update time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{rootBean=cc.topush.model.Department@7ce0f1, propertyPath='name', message='未设置', leafBean=cc.topush.model.Department@7ce0f1, value=}
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:138)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreUpdate(BeanValidationEventListener.java:86)
	at org.hibernate.action.internal.EntityUpdateAction.preUpdate(EntityUpdateAction.java:244)
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:118)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:589)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:463)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1295)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:468)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3159)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2352)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:491)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:147)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:65)
	at org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:61)
	... 24 common frames omitted
```

**Comment by greenlaw110** [comment]
@moonmanbu 你试过最新的版本吗?

我在 Content 类上加上了这个:

![image](https://user-images.githubusercontent.com/216930/56132558-a274aa80-5fcd-11e9-9d08-21309a5af92b.png)

测试 Put 一个无效数据, 返回了正确的消息:
![image](https://user-images.githubusercontent.com/216930/56132591-ba4c2e80-5fcd-11e9-889d-86de1c6e1480.png)
