### ISSUE TITLE
ActFramework hot reload caused Ehcache Classloader Exception

### ISSUE THREAD

**Issue by FTD-IceIce** [actframework/actframework#1070]
Error stack:

```
 java.lang.ClassCastException: net.sf.ehcache.Element cannot be cast to net.sf.ehcache.Element
	at net.sf.ehcache.store.disk.DiskStorageFactory.read(DiskStorageFactory.java:371)
	at net.sf.ehcache.store.disk.DiskStorageFactory.retrieve(DiskStorageFactory.java:864)
	at net.sf.ehcache.store.disk.Segment.decode(Segment.java:171)
	at net.sf.ehcache.store.disk.Segment.put(Segment.java:458)
	at net.sf.ehcache.store.disk.DiskStore.putFaulted(DiskStore.java:229)
	at net.sf.ehcache.store.CacheStore$3.call(CacheStore.java:143)
	at net.sf.ehcache.store.CacheStore$3.call(CacheStore.java:137)
	at net.sf.ehcache.store.cachingtier.OnHeapCachingTier$Fault.get(OnHeapCachingTier.java:334)
	at net.sf.ehcache.store.cachingtier.OnHeapCachingTier$Fault.access$200(OnHeapCachingTier.java:311)
	at net.sf.ehcache.store.cachingtier.OnHeapCachingTier.get(OnHeapCachingTier.java:175)
	at net.sf.ehcache.store.CacheStore.put(CacheStore.java:137)
	at net.sf.ehcache.Cache.putInternal(Cache.java:1617)
	at net.sf.ehcache.Cache.put(Cache.java:1543)
	at net.sf.ehcache.Cache.put(Cache.java:1508)
	at org.osgl.cache.impl.EhCacheService.put(EhCacheService.java:89)
	at org.osgl.cache.impl.EhCacheService.put(EhCacheService.java:94)
	at org.osgl.http.H$Session.cache(H.java:2574)
	at x.x.controller.UtilController.imageCode(UtilController.java:56)
	at x.x.controller.UtilControllerMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1038)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1024)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:663)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:559)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:213)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1308)
	at act.route.Router$ContextualHandler.handle(Router.java:1714)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by FTD-IceIce** [comment]
> java.lang.ClassCastException: net.sf.ehcache.Element cannot be cast to net.sf.ehcache.Element
	at net.sf.ehcache.store.disk.DiskStorageFactory.read(DiskStorageFactory.java:371)
	at net.sf.ehcache.store.disk.DiskStorageFactory.retrieve(DiskStorageFactory.java:864)
	at net.sf.ehcache.store.disk.Segment.decode(Segment.java:171)
	at net.sf.ehcache.store.disk.Segment.put(Segment.java:458)
	at net.sf.ehcache.store.disk.DiskStore.putFaulted(DiskStore.java:229)
	at net.sf.ehcache.store.CacheStore$3.call(CacheStore.java:143)
	at net.sf.ehcache.store.CacheStore$3.call(CacheStore.java:137)
	at net.sf.ehcache.store.cachingtier.OnHeapCachingTier$Fault.get(OnHeapCachingTier.java:334)
	at net.sf.ehcache.store.cachingtier.OnHeapCachingTier$Fault.access$200(OnHeapCachingTier.java:311)
	at net.sf.ehcache.store.cachingtier.OnHeapCachingTier.get(OnHeapCachingTier.java:175)
	at net.sf.ehcache.store.CacheStore.put(CacheStore.java:137)
	at net.sf.ehcache.Cache.putInternal(Cache.java:1617)
	at net.sf.ehcache.Cache.put(Cache.java:1543)
	at net.sf.ehcache.Cache.put(Cache.java:1508)
	at org.osgl.cache.impl.EhCacheService.put(EhCacheService.java:89)
	at org.osgl.cache.impl.EhCacheService.put(EhCacheService.java:94)
	at org.osgl.http.H$Session.cache(H.java:2574)
	at x.x.controller.UtilController.imageCode(UtilController.java:56)
	at x.x.controller.UtilControllerMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1038)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1024)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:663)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:559)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:213)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1308)
	at act.route.Router$ContextualHandler.handle(Router.java:1714)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by greenlaw110** [comment]
@FTD-IceIce I can't reproduce this issue. I've sent you the test app. Let me know if you have any other concerns

**Comment by greenlaw110** [comment]
Able to reproduce on customer's project. 

## Root cause

osgl-cache is black listed to actframework, meaning Act's classloader will not load any class defined in osgl-cache, including `org.osgl.cache.impl.EhCacheService`, however ehcache is not blacklisted, thus Act's class loader will try to load classes defined in this jar file, e.g. `Element`. This creates tension between PUT an element (which is loaded with root class loader) and GET (which is loaded with Act's class loader).

## Solution

Add ehcache into act's jar blacklist
