### ISSUE TITLE
`@LoginUser` caused `InjectException` upon hot reload

### ISSUE THREAD

**Issue by moonmanbu** [actframework/actframework#1071]
controller
```java
public class AuthenticatedService extends Service {

    @LoginUser
    protected User me;
    ...
}
```
异常栈
```
2019-02-25 10:53:37,978 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-3] - error handling request: [GET]/api/v1/users
org.osgl.inject.InjectException: Unable to inject field value on class cc.topush.service.v1.UserService
	at org.osgl.inject.BeanSpec.setField(BeanSpec.java:764)
	at org.osgl.inject.Genie$FieldInjector.applyTo(Genie.java:471)
	at org.osgl.inject.Genie$10.get(Genie.java:1040)
	at org.osgl.inject.Genie$8.get(Genie.java:987)
	at act.inject.param.ParamValueLoaderService$2.load(ParamValueLoaderService.java:231)
	at act.inject.param.ParamValueLoaderService$6.load(ParamValueLoaderService.java:694)
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:65)
	at act.inject.param.ParamValueLoaderService.loadHostBean(ParamValueLoaderService.java:137)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.controllerInstance(ReflectedHandlerInvoker.java:887)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:586)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:559)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:213)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1308)
	at act.route.Router$ContextualHandler.handle(Router.java:1714)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Can not set cc.topush.model.User field cc.topush.service.v1.base.AuthenticatedService.me to cc.topush.model.User
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.osgl.inject.BeanSpec.setField(BeanSpec.java:762)
	... 18 common frames omitted
```

**Comment by greenlaw110** [comment]
@moonmanbu I need you to provide a sample project that can reproduce this issue.

**Comment by moonmanbu** [comment]
https://github.com/actframework/act-aaa-plugin/tree/master/testapps/jpa_model_id
在这个demo里发现的这个问题

**Comment by greenlaw110** [comment]
@moonmanbu the automate test result of jpa_model_id project:
![image](https://user-images.githubusercontent.com/216930/54484008-e468de80-48b1-11e9-99ad-ad8c0a2312a2.png)

LoginUser defined in base class:
![image](https://user-images.githubusercontent.com/216930/54484001-d3b86880-48b1-11e9-88bc-314ae4ead0d4.png)


The user `me` is bound after controller is instantiated:
![image](https://user-images.githubusercontent.com/216930/54483998-cbf8c400-48b1-11e9-8578-7009fabcd48d.png)

**Comment by greenlaw110** [comment]
BTW, I have tried to modify the project several times to trigger hotreload, I still don't have the inject exception issue:
![image](https://user-images.githubusercontent.com/216930/54484060-a28c6800-48b2-11e9-95ae-72f977a60955.png)

**Comment by greenlaw110** [comment]
Alright, debugging customer's project reviews there are classloader inconsistent issue between the value and the field type:

![image](https://user-images.githubusercontent.com/216930/55055965-d0df2400-50b8-11e9-862e-4cc00e4b8727.png)

**Comment by greenlaw110** [comment]
Okay, the `LoginUserFinder` tried to get cached user from AAAPlugin cache:
![image](https://user-images.githubusercontent.com/216930/55056575-91b1d280-50ba-11e9-9236-a7fe510ce59a.png)

So the issue is AAAPlugin shall respond to hot reload event and clear the cache upon hot reload happening.

**Comment by greenlaw110** [comment]
To fix this we need to do some work in osgl-cache:
https://github.com/osglworks/java-cache/issues/6
