### ISSUE TITLE
`IllegalArgumentException` with static Dao class definition inside a model class

### ISSUE THREAD

**Issue by moonmanbu** [actframework/actframework#1072]
BaseModel
```java
@MappedSuperclass
public class BaseModel implements SimpleBean {

    ...
    public static class Dao<M extends BaseModel> extends JPADao<Long, M> {

    }
}
```
Model
```java
@Entity
public class SupportInfo extends BaseModel {
    ...
    public static class Dao extends BaseModel.Dao<SupportInfo> {

    }
}
```

异常栈
```
ava.lang.IllegalArgumentException: Cannot infer type parameter implementation on cc.topush.model.base.BaseModel$Dao against act.db.DaoBase
	at org.osgl.util.Generics.typeParamImplementations(Generics.java:67)
	at act.db.DaoBase.exploreTypes(DaoBase.java:125)
	at act.db.DaoBase.<init>(DaoBase.java:50)
	at act.db.jpa.JPADao.<init>(JPADao.java:57)
	at cc.topush.model.base.BaseModel$Dao.<init>(BaseModel.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.osgl.inject.Genie$10.get(Genie.java:1034)
	at org.osgl.inject.Genie$8.get(Genie.java:987)
	at org.osgl.inject.Genie.get(Genie.java:570)
	at act.inject.genie.GenieInjector.get(GenieInjector.java:76)
	at act.app.App.getInstance(App.java:1118)
	at act.app.DbServiceManager$1$1.visit(DbServiceManager.java:101)
	at act.app.DbServiceManager$1$1.visit(DbServiceManager.java:83)
	at org.osgl.Lang$Visitor.apply(Lang.java:2460)
	at org.osgl.Lang$14.visit(Lang.java:2565)
	at org.osgl.Lang$Visitor.apply(Lang.java:2460)
	at org.osgl.Lang$Visitor.apply(Lang.java:2450)
	at act.util.ClassNode.visitTree(ClassNode.java:178)
	at act.util.ClassNode.visitSubTree(ClassNode.java:185)
	at act.util.ClassNode.visitTree(ClassNode.java:176)
	at act.util.ClassNode.visitSubTree(ClassNode.java:185)
	at act.util.ClassNode.visitTree(ClassNode.java:176)
	at act.util.ClassNode.visitSubTree(ClassNode.java:185)
	at act.util.ClassNode.visitTree(ClassNode.java:176)
	at act.util.ClassNode.visitTree(ClassNode.java:171)
	at act.util.ClassNode.visitPublicNotAbstractTreeNodes(ClassNode.java:293)
	at act.app.DbServiceManager$1.initDao(DbServiceManager.java:83)
	at act.app.DbServiceManager$1.run(DbServiceManager.java:76)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:132)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:126)
	at act.event.EventBus.callOn(EventBus.java:1354)
	at act.event.EventBus.callOn(EventBus.java:1376)
	at act.event.EventBus.callOn(EventBus.java:1411)
	at act.event.EventBus._emitWithOnceBus(EventBus.java:1327)
	at act.event.EventBus.emit(EventBus.java:891)
	at act.db.sql.SqlDbService$4.run(SqlDbService.java:142)
	at act.job.Job$4.apply(Job.java:449)
	at act.job.Job.doJob(Job.java:407)
	at act.job.Job.run(Job.java:338)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:529)
	at act.job.Job.doJob(Job.java:407)
	at act.job.Job.run(Job.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.osgl.util.Generics.typeParamImplementations(Generics.java:270)
	at org.osgl.util.Generics.typeParamImplementations(Generics.java:65)
	... 53 common frames omitted
```

**Comment by greenlaw110** [comment]
@moonmanbu `BaseModel.Dao` must be abstract, as there is a type parameter `M` which cannot be materialized:

```java
@MappedSuperclass
public class BaseModel implements SimpleBean {

    ...
    // The following class must be decorated with **abstract**
    public static class Dao<M extends BaseModel> extends JPADao<Long, M> {

    }
}
```

**Comment by greenlaw110** [comment]
Dao init logic improved. Now we will log a warn message in case Dao is not declared as abstract in this case:

![image](https://user-images.githubusercontent.com/216930/54875275-f1f10c00-4e4f-11e9-9709-7564699dd8b2.png)
