### ISSUE TITLE
Misleading error stack printed out when loading yml file with `@LoadResource`

### ISSUE THREAD

**Issue by flyingbeecd** [actframework/actframework#1073]
ACT version: 1.8.19.0

yml file：

```
- id: u31.csg
  name: 网管
  type: corba
  provider: zz
  adapter: Adapter
  ip: 127.0.0.1
  port: 8080
  nameService:  NameService
  userName: user
  password: aaa
  howmany: 100
  nameComponents:
  - id: 123
    kind: ems
```

create a bean `Config` make it comply to the yaml file and then try load it:
 
```java    
    @LoadResource("configs.yml")
    private List<Config> configs;
```

Error stack printed during app start:

```
java.lang.UnsupportedOperationException: target type not supported: java.util.List<Config>
	at org.osgl.util.IO$ReadStageBase.toUnknownType(IO.java:731)
	at org.osgl.util.IO$ReadStageBase._to(IO.java:710)
	at org.osgl.util.IO$ReadStageBase.to(IO.java:665)
	at act.inject.util.ResourceLoader._load(ResourceLoader.java:235)
	at act.inject.util.ResourceLoader._load(ResourceLoader.java:157)
	at act.inject.util.ResourceLoader.load(ResourceLoader.java:142)
	at act.inject.util.ResourceLoader.initialized(ResourceLoader.java:80)
	at org.osgl.inject.ValueLoader$Base.init(ValueLoader.java:62)
	at org.osgl.inject.ValueLoaderFactory.create(ValueLoaderFactory.java:50)
	at org.osgl.inject.Genie.findProvider(Genie.java:933)
	at org.osgl.inject.Genie.fieldInjector(Genie.java:1092)
	at org.osgl.inject.Genie.fieldInjectors(Genie.java:1082)
	at org.osgl.inject.Genie.buildFieldMethodInjector(Genie.java:1023)
	at org.osgl.inject.Genie.buildProvider(Genie.java:1003)
	at org.osgl.inject.Genie.findProvider(Genie.java:961)
	at org.osgl.inject.Genie.getProvider(Genie.java:599)
	at org.osgl.inject.Genie.get(Genie.java:570)
	at act.inject.genie.GenieInjector.get(GenieInjector.java:76)
	at act.app.App.getInstance(App.java:1118)
	at act.util.ReflectedInvokerHelper.tryGetSingleton(ReflectedInvokerHelper.java:60)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:354)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createControllerAction(ReflectedHandlerInvoker.java:1177)
	at act.Act$Mode.createRequestHandler(Act.java:150)
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:425)
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:349)
	at act.handler.builtin.controller.RequestHandlerProxy.actionHandler(RequestHandlerProxy.java:176)
	at act.apidoc.Endpoint.explore(Endpoint.java:323)
	at act.apidoc.Endpoint.<init>(Endpoint.java:222)
	at act.apidoc.ApiManager$4.visit(ApiManager.java:193)
	at act.route.Router.visit(Router.java:225)
	at act.route.Router.visit(Router.java:228)
	at act.route.Router.accept(Router.java:184)
	at act.apidoc.ApiManager.load(ApiManager.java:188)
	at act.apidoc.ApiManager.load(ApiManager.java:133)
	at act.apidoc.ApiManager$1.run(ApiManager.java:94)
	at act.job.Job$4.apply(Job.java:442)
	at act.job.Job.doJob(Job.java:403)
	at act.job.Job.run(Job.java:338)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:112)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:93)
	at act.job.Job.runFollowingJobs(Job.java:423)
	at act.job.Job.run(Job.java:392)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:477)
	at act.event.EventBus.callOn(EventBus.java:1354)
	at act.event.EventBus.callOn(EventBus.java:1376)
	at act.event.EventBus.callOn(EventBus.java:1406)
	at act.event.EventBus._emit(EventBus.java:1267)
	at act.event.EventBus.emit(EventBus.java:723)
	at act.app.App.emit(App.java:1282)
	at act.app.App$5.run(App.java:822)
	at act.job.Job$4.apply(Job.java:442)
	at act.job.Job.doJob(Job.java:403)
	at act.job.Job.run(Job.java:338)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:112)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:93)
	at act.job.Job.runFollowingJobs(Job.java:423)
	at act.job.Job.run(Job.java:392)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:477)
	at act.event.EventBus.callOn(EventBus.java:1354)
	at act.event.EventBus.callOn(EventBus.java:1376)
	at act.event.EventBus.callOn(EventBus.java:1406)
	at act.event.EventBus._emit(EventBus.java:1267)
	at act.event.EventBus.emit(EventBus.java:723)
	at act.app.App.emit(App.java:1282)
	at act.app.App$4.run(App.java:797)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:529)
	at act.job.Job.doJob(Job.java:403)
	at act.job.Job.run(Job.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
@flyingbeecd I can't reproduce this issue. Here is the test app:
https://github.com/actframework/actframework/blob/develop/testapps/GHIssues/src/main/java/ghissues/Gh1073.java

**Comment by greenlaw110** [comment]
Okay, it is now clear the error stack will be printed out when log level is debug, which is a misleading log. I need to get rid of it.

**Comment by greenlaw110** [comment]
I've make the error be logged at trace level
