### ISSUE TITLE
Exception caused by @After Interceptor defined in abstract class

### ISSUE THREAD

**Issue by donald2150** [actframework/actframework#1078]
```
09:32:45.787 [XNIO-1 task-4] ERROR a.h.b.c.RequestHandlerProxy - Error invoking exception handler
org.osgl.inject.InjectException: Cannot instantiate class com.gyrj.sys.controller.AppBaseController
	at org.osgl.inject.Genie.findProvider(Genie.java:955)
	at org.osgl.inject.Genie.getProvider(Genie.java:599)
	at act.inject.genie.GenieInjector.getProvider(GenieInjector.java:81)
	at act.inject.param.ParamValueLoaderService.findBeanLoader(ParamValueLoaderService.java:223)
	at act.inject.param.ParamValueLoaderService.loadHostBean(ParamValueLoaderService.java:131)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.controllerInstance(ReflectedHandlerInvoker.java:887)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:586)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:680)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker$_Exception.internalHandle(ReflectedHandlerInvoker.java:1391)
	at act.handler.builtin.controller.ExceptionInterceptor.handle(ExceptionInterceptor.java:70)
	at act.handler.builtin.controller.RequestHandlerProxy$GroupExceptionInterceptor.apply(RequestHandlerProxy.java:716)
	at act.handler.builtin.controller.RequestHandlerProxy.handleException(RequestHandlerProxy.java:579)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:239)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1308)
	at act.route.Router$ContextualHandler.handle(Router.java:1714)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
09:32:45.787 [XNIO-1 task-4] ERROR a.h.b.c.RequestHandlerProxy - Error invoking exception handler
org.osgl.inject.InjectException: Cannot instantiate class com.gyrj.sys.controller.AppBaseController
	at org.osgl.inject.Genie.findProvider(Genie.java:955)
	at org.osgl.inject.Genie.getProvider(Genie.java:599)
	at act.inject.genie.GenieInjector.getProvider(GenieInjector.java:81)
	at act.inject.param.ParamValueLoaderService.findBeanLoader(ParamValueLoaderService.java:223)
	at act.inject.param.ParamValueLoaderService.loadHostBean(ParamValueLoaderService.java:131)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.controllerInstance(ReflectedHandlerInvoker.java:887)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:586)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:680)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker$_Exception.internalHandle(ReflectedHandlerInvoker.java:1391)
	at act.handler.builtin.controller.ExceptionInterceptor.handle(ExceptionInterceptor.java:70)
	at act.handler.builtin.controller.RequestHandlerProxy$GroupExceptionInterceptor.apply(RequestHandlerProxy.java:716)
	at act.handler.builtin.controller.RequestHandlerProxy.handleException(RequestHandlerProxy.java:579)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:239)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1308)
	at act.route.Router$ContextualHandler.handle(Router.java:1714)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by greenlaw110** [comment]
@donald2150 I can't reproduce this issue. Here is my test code:

The abstract base class

```java
package ghissues.gh1078;

import ghissues.BaseController;
import org.osgl.mvc.annotation.After;
import org.osgl.mvc.result.RenderJSON;
import org.osgl.util.C;

public abstract class Base extends BaseController {

    @After
    public void after() {
        throw new RenderJSON(C.Map("result", "intercepted"));
    }

}
```

The controller class:

```java

  
package ghissues.gh1078;

import act.controller.annotation.UrlContext;
import org.osgl.mvc.annotation.GetAction;

@UrlContext("1078")
public class Service extends Base {

    @GetAction
    public String test() {
        return "okay";
    }

}
```

Sending request to `/1078` shows the interceptor applied as expected:

![image](https://user-images.githubusercontent.com/216930/54476894-590e2f80-4856-11e9-8c44-0c5b40948e2d.png)

**Comment by greenlaw110** [comment]
Root cause, in customer project, the `@Global` is used on top of an instance method declared in an abstract class. The logic is broken.

Enhancement is done to warn the developer about this and ignore the `@Global` annotation in such case.
