### ISSUE TITLE
Upload file caused server crash

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1082]
Sending a request with file upload to an act app result in server crash. The log files shows:

```
java.lang.IllegalAccessError: tried to access method org.osgl.storage.impl.SObject.<init>(Ljava/lang/String;)V from class org.osgl.storage.impl.StorageObject
        at org.osgl.storage.impl.StorageObject.<init>(StorageObject.java:39)
        at org.osgl.storage.impl.FileObject.<init>(FileObject.java:28)
        at org.osgl.storage.impl.FileSystemService.newSObject(FileSystemService.java:161)
        at org.osgl.storage.impl.StorageServiceBase.getFull(StorageServiceBase.java:276)
        at act.util.UploadFileStorageService._store(UploadFileStorageService.java:89)
        at act.util.UploadFileStorageService.store(UploadFileStorageService.java:73)
        at act.data.ApacheMultipartParser.parse(ApacheMultipartParser.java:57)
        at act.app.ActionContext.bodyParams(ActionContext.java:778)
        at act.app.ActionContext.getBody(ActionContext.java:767)
        at act.app.ActionContext._paramVal(ActionContext.java:734)
        at act.app.ActionContext.paramVal(ActionContext.java:723)
        at act.app.ActionContext.body(ActionContext.java:696)
        at act.app.ActionContext.upload(ActionContext.java:799)
        at act.app.ActionContext.upload(ActionContext.java:795)
        at act.data.SObjectResolver.resolve(SObjectResolver.java:73)
        at act.data.SObjectBinder.resolve(SObjectBinder.java:40)
        at act.data.SObjectBinder.resolve(SObjectBinder.java:33)
        at act.inject.param.BoundedValueLoader.load(BoundedValueLoader.java:41)
        at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:58)
        at act.inject.param.ParamValueLoaderService.loadMethodParams(ParamValueLoaderService.java:191)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.params(ReflectedHandlerInvoker.java:1147)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:588)
        at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
        at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:559)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:213)
        at act.app.ActionContext.proceedWithHandler(ActionContext.java:1308)
        at act.route.Router$ContextualHandler.handle(Router.java:1714)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
This issue is introduced with fix to https://github.com/actframework/actframework/issues/1077

**Comment by greenlaw110** [comment]
The fix is to make `SObject` constructor be public, which is done through osgl-tool https://github.com/osglworks/java-tool/commit/9d9dee312c0d88c72948258c9b36ce5f06d98dba
