### ISSUE TITLE
java.lang.LinkageError caused by org.w3c.dom.Document

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1096]
This issue actually re-open #1061 

I can reproduce it by replacing act-eclipselink with act-hibernate in GHIssue test project. When project start I got the following console log:

```
java.lang.LinkageError: loader constraint violation: when resolving method "org.osgl.util.XML.toString(Lorg/w3c/dom/Document;)Ljava/lang/String;" the class loader (instance of act/boot/app/FullStackAppBootstrapClassLoader) of the current class, act/test/Scenario$RequestBuilder, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/osgl/util/XML, have different Class objects for the type org/w3c/dom/Document used in the signature
	at act.test.Scenario$RequestBuilder.verifyXmlBody(Scenario.java:274)
	at act.test.Scenario$RequestBuilder.<init>(Scenario.java:148)
	at act.test.Scenario.sendRequest(Scenario.java:487)
	at act.test.Interaction.verify(Interaction.java:88)
	at act.test.Interaction.run(Interaction.java:68)
	at act.test.Scenario.run(Scenario.java:622)
	at act.test.Scenario.runInteractions(Scenario.java:612)
	at act.test.Scenario.run(Scenario.java:579)
	at act.test.Scenario.start(Scenario.java:451)
	at act.test.Scenario.start(Scenario.java:439)
	at act.test.Test.run(Test.java:283)
	at act.test.ScenarioDebugHelper.run(ScenarioDebugHelper.java:102)
	at act.test.ScenarioDebugHelperMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1042)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1028)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:663)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:558)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:210)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1326)
	at act.route.Router$ContextualHandler.handle(Router.java:1714)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Search for Document in IDEA, we found the same class coming from 2 different jar files:
![image](https://user-images.githubusercontent.com/216930/55115284-42aa8280-5138-11e9-8d3d-b8ea76af9062.png)

**Comment by greenlaw110** [comment]
Fix:

Add `xml-apis` into the `act.jar.black.list` file
