### ISSUE TITLE
`UnexpectedException` triggered executing CLI command in TSCPP project

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1117]
Screen shot:

![image](https://user-images.githubusercontent.com/216930/56264754-d31e2680-612a-11e9-906a-ddfc86741714.png)

Stack trace:

```
2019-04-17 16:00:27,808 ERROR a.h.b.c.CliHandlerProxy@[cli-thread-3] - Error handling request
org.osgl.exception.UnexpectedException: Cannot find access method to field SEP_COLON on class java.lang.Object
	at org.osgl.util.E.unexpected(E.java:179)
	at org.osgl.util.ReflectionPropertyHandlerFactory.getterViaField(ReflectionPropertyHandlerFactory.java:134)
	at org.osgl.util.ReflectionPropertyHandlerFactory.createPropertyGetter(ReflectionPropertyHandlerFactory.java:76)
	at org.osgl.Lang.propertyGetter(Lang.java:8349)
	at org.osgl.Lang.getProperty(Lang.java:8322)
	at org.osgl.Lang.getProperty(Lang.java:8231)
	at act.cli.ascii_table.impl.CollectionASCIITableAware.getProperty(CollectionASCIITableAware.java:129)
	at act.cli.ascii_table.impl.CollectionASCIITableAware.<init>(CollectionASCIITableAware.java:115)
	at act.cli.view.CliView$1.render(CliView.java:94)
	at act.cli.view.CliView$5.render(CliView.java:190)
	at act.cli.view.CliView.render(CliView.java:320)
	at act.cli.view.CliView.print(CliView.java:325)
	at act.handler.builtin.cli.CliHandlerProxy.onResult(CliHandlerProxy.java:122)
	at act.handler.builtin.cli.CliHandlerProxy.handle(CliHandlerProxy.java:84)
	at act.cli.CliContext.handle(CliContext.java:426)
	at act.cli.CliSession.run(CliSession.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
``` 

The command method:

```java
    @PropertySpec(EXPORT_FIELDS)
    @Command(name = "user.list", help = "list all users")
    public Iterable<User> list() {
        return dao.q("email !=", "root@app");
    }
```

Definition of `EXPORT_FIELDS`:

```java
public static final String EXPORT_FIELDS = "-permissions,-roles,-privileges";
```

**Comment by greenlaw110** [comment]
If we change the `EXPORT-FIELDS` to 

```java
public static final String EXPORT_FIELDS = "id,firstName,lastName,email,mobile,baseValue,hourlyRate,defects";
```

Then the issue will not happen

**Comment by greenlaw110** [comment]
The issue is in the `DataPropertyRepository`, it get all public fields including the static fields of the bean to be exported:
![image](https://user-images.githubusercontent.com/216930/56265299-84718c00-612c-11e9-95cb-999c328e95b9.png)
