### ISSUE TITLE
Upload file issue

### ISSUE THREAD

**Issue by BoboYaya** [actframework/actframework#1128]
Version：1.8.20.1

Error message：

```
2019-05-05 17:15:54,210 ERROR a.x.NetworkHandler@[XNIO-1 task-3] - Fatal Error encountered handling request: 
java.lang.IllegalAccessError: org/osgl/storage/impl/SObject$InputStreamSObject
	at org.osgl.storage.impl.StorageServiceBase.put(StorageServiceBase.java:307)
```

Source code:
```java
public JSONObject upload(ISObject file, StorageServiceManager ssMgr){
        IStorageService ss = ssMgr.storageService("upload");
        String key = ss.getKey();
        file.getAttribute(ISObject.ATTR_FILE_NAME);
        file = ss.put(key, file);
｝
```

configuration：

```
ss.instances=upload
ss.upload.impl=act.storage.FileSystemStoragePlugin
ss.upload.home.dir=upload
ss.upload.staticWebEndpoint=/upload
ss.upload.get.MetaOnly=true
```

**Comment by BoboYaya** [comment]
刚才降回较早前的版本做了测试，同样的代码在版本：act-starter-parent：1.8.16.0 下就正常。

**Comment by BoboYaya** [comment]
这是具体的报错信息:

2019-05-05 19:29:04,070 ERROR a.x.NetworkHandler@[XNIO-1 task-4] - Fatal Error encountered handling request: 
java.lang.IllegalAccessError: tried to access class org.osgl.storage.impl.SObject$InputStreamSObject from class org.osgl.storage.impl.StorageServiceBase
	at org.osgl.storage.impl.StorageServiceBase.put(StorageServiceBase.java:307)
	at com.bobo.controller.ArticlePostCtrl.upload(ArticlePostCtrl.java:183)
	at com.bobo.controller.ArticlePostCtrlMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1049)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1035)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:668)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:558)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:210)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1358)
	at act.route.Router$ContextualHandler.handle(Router.java:1748)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

会不会是osgl里进行相关的升级造成的？

**Comment by greenlaw110** [comment]
@BoboYaya can you please provide your `pom.xml` file?

**Comment by BoboYaya** [comment]
@greenlaw110 
Here is the main part of my pom.xml.
![QQ截图20190505213009](https://user-images.githubusercontent.com/50290297/57194744-fd6e4180-6f7c-11e9-87bd-e53a2ba8e765.png)

**Comment by jiankian** [comment]
我的也是，请问解决了吗？之前是OSS，现在试试本地上传，就报错了！

**Comment by jiankian** [comment]
![屏幕快照 2019-05-10 19 22 41](https://user-images.githubusercontent.com/9036838/57524402-48f86500-735a-11e9-97b8-70d6785844d3.png)

**Comment by jiankian** [comment]
act-parent和act-storage降了几个版本也没用，传不了文件，降到2018年四月的版本以下，Act不能启动了。好急，🙃

**Comment by greenlaw110** [comment]
@jiankian 你试试 act-1.8.22-SNAPSHOT 呢

**Comment by jiankian** [comment]
快照地址在https://repository.sonatype.org/#nexus-search;quick~actframework吗，还不能使用1.8.22

**Comment by greenlaw110** [comment]
Try add this into your `pom.xml` file:

```xml
    <dependency>
      <groupId>org.actframework</groupId>
      <artifactId>act</artifactId>
      <version>1.8.22-SNAPSHOT</version>
    </dependency>
```

**Comment by jiankian** [comment]
可以上传文件了 @greenlaw110  ，谢谢
