### ISSUE TITLE
Url request path parameters mapping to Map<String, Object> failed

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#116]
Path parameters like:
``` url
?search.loginName=g&search.email=t
```

Mapping to Map<String, Object>
```java
    public List<Admin> list(Map<String, Object> search) {
        ...
        return admins;
    }
```

Catch errors:
```log
2017-03-23 10:13:30,138 ERROR [XNIO-1 task-1] [act.handler.builtin.controller.RequestHandlerProxy] - Error handling request
org.osgl.exception.UnexpectedException: Component type not resolvable: class java.lang.Object
	at org.osgl.util.E.unexpected(E.java:96)
	at act.inject.param.MapLoader.load(MapLoader.java:112)
	at act.inject.param.JsonParamValueLoader.load(JsonParamValueLoader.java:71)
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:49)
	at act.inject.param.ParamValueLoaderService.loadMethodParams(ParamValueLoaderService.java:163)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.params(ReflectedHandlerInvoker.java:467)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:212)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:42)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:445)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:187)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1011)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:98)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by greenlaw110** [comment]
@leeaee can you use `Map<String, String>` instead of `Map<String, Object>` if the map value is always a simple type? if the map value is complex type, you probably can try `Map<String, JsonObject>`

**Comment by leeaee** [comment]
@greenlaw110 yes, I tried ```Map<String, String>``` and its OK for the current scenario. The only thing is that I need get used to transferring some integer value from string type manually now.

**Comment by greenlaw110** [comment]
Well the framework can't do anything on this case. Because things like `123` could be a String `"123"` or an integer `123` and there is no place to tell the framework how to resolve the value

**Comment by greenlaw110** [comment]
@leeaee I think you can use `JsonObject` to replace `Map<String, String>`
