### ISSUE TITLE
无法注册beetl模板自定义方法

### ISSUE THREAD

**Issue by BoboYaya** [actframework/actframework#1165]
自定义方法代码

```java
import org.beetl.core.Context;
import org.beetl.core.Function;

public class I18nFunction implements Function {
    @Override
    public String call(Object[] paras, Context ctx) {
        String key = (String) paras[0];
        return key;
    }
}
```

beetl.properities配置信息

```
FN.i18n = com.jame.util.I18nFunction
```

报错信息

```
2019-07-12 12:13:58,108 WARN  a.j.JobExceptionListenerManager@[jobs-thread-2] - Job exception encountered on running job[BeetlView:init]
java.lang.RuntimeException: 初始化失败
	at org.beetl.core.GroupTemplate.<init>(GroupTemplate.java:156)
	at org.beetl.core.GroupTemplate.<init>(GroupTemplate.java:142)
	at act.view.beetl.BeetlView.init(BeetlView.java:104)
	at act.view.View$1.run(View.java:54)
	at act.job.Job$4.apply(Job.java:454)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:535)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: com.jame.util.I18nFunction cannot be cast to org.beetl.core.Function
	at org.beetl.core.GroupTemplate.initFunction(GroupTemplate.java:201)
	at org.beetl.core.GroupTemplate.init(GroupTemplate.java:172)
	at org.beetl.core.GroupTemplate.<init>(GroupTemplate.java:153)
```

**Comment by greenlaw110** [comment]
Wrong place. The issue should go act-beetl project
