### ISSUE TITLE
production mode can not boot on Windows7 (x64) and Windows10 (x64)

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1200]
I am development on macOS Platform，use command `mvn clean package` build the Project。
on windows,  I can not run with run.bat script.
on win7:
![QQ20190907-075640](https://user-images.githubusercontent.com/9036838/64466576-7e189680-d145-11e9-8687-99ef915ae5ec.png)
![QQ20190907-075648](https://user-images.githubusercontent.com/9036838/64466583-82dd4a80-d145-11e9-874d-24a7110182f7.png)
![QQ20190907-075702](https://user-images.githubusercontent.com/9036838/64466594-88d32b80-d145-11e9-9356-63702c72573b.png)
![QQ20190907-075944](https://user-images.githubusercontent.com/9036838/64466598-8ec90c80-d145-11e9-9c4b-c913f88780c4.png)

on win10:
![6263121E3B44D02761FC9694FE3A3C31](https://user-images.githubusercontent.com/9036838/64466407-77d5ea80-d144-11e9-856d-06fb849e007f.jpg)

But it's normal on my macOS computer.
![QQ20190907-080436](https://user-images.githubusercontent.com/9036838/64466754-39d9c600-d146-11e9-96de-05d998a99500.png)

Developed in Windows system, it can run by IDEA, but the project can't start after packaging.
![QQ20190907-083946](https://user-images.githubusercontent.com/9036838/64467575-5d077400-d14c-11e9-86bc-1b823c3e8387.png)

![QQ20190907-084021](https://user-images.githubusercontent.com/9036838/64467581-6c86bd00-d14c-11e9-921d-230192ec5cee.png)
![QQ20190907-084219](https://user-images.githubusercontent.com/9036838/64467584-727c9e00-d14c-11e9-91f6-efc7dd293ead.png)

run the run.bar script After  `mvn clean package` finished
![QQ20190907-085004](https://user-images.githubusercontent.com/9036838/64467592-80caba00-d14c-11e9-81b0-5f33dd518af5.png)

`C:\Users\jiankian\Desktop\CX-SC-v2\serve\target\dist\serve-1.0-SNAPSHOT-r4840.tar\serve-1.0-SNAPSHOT-r4840>run.bat
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
   _____  __   __   _____    _____
  / ____| \ \ / /  / ____|  / ____|
 | |       \ V /  | (___   | |
 | |        > <    \___ \  | |
 | |____   / . \   ____) | | |____
  \_____| /_/ \_\ |_____/   \_____|

powered by ActFramework r1.8.26-68ff

 version: v1.0-SNAPSHOT-4840
scan pkg: cn.anline.cx.sc.serve
base dir: C:\Users\jiankian\Desktop\CX-SC-v2\serve\target\dist\serve-1.0-SNAPSHOT-r4840.tar\serve-1.0-SNAPSHOT-r4840
     pid: 7864
 profile: prod
    mode: PROD
      OS: WINDOWS
     jdk: Java HotSpot(TM) 64-Bit Server VM 1.8

     zen: Errors should never pass silently
          Unless explicitly silenced.

2019-09-07 08:45:53,400 INFO  a.Act@[main] - loading application(s) ...
2019-09-07 08:45:53,408 INFO  a.a.App@[main] - App starting ....
2019-09-07 08:45:53,424 INFO  o.xnio@[Thread-0] - XNIO version 3.3.8.Final
2019-09-07 08:45:53,440 INFO  o.x.nio@[Thread-0] - XNIO NIO Implementation Version 3.3.8.Final
2019-09-07 08:45:53,580 INFO  a.a.DbServiceManager@[main] - db service[mysql] initialized
2019-09-07 08:45:53,580 WARN  a.a.DbServiceManager@[main] - db service configuration not found. Use the sole one db service[mysql] as default service
2019-09-07 08:45:53,666 INFO  a.s.StorageServiceManager@[main] - storage service[upload] initialized
2019-09-07 08:45:53,674 INFO  a.s.StorageServiceManager@[main] - storage service[space] initialized
2019-09-07 08:45:53,674 INFO Exception in thread "main"  a.a.App@[Thread-2] - App shutting down ....
java.lang.RuntimeException: java.lang.IllegalStateException: Native library for Attach API not available in this JRE
        at act.db.ebean.EbeanAgentLoader.loadAgent(EbeanAgentLoader.java:120)
        at act.db.ebean.EbeanAgentLoader.loadAgentFromClasspath(EbeanAgentLoader.java:160)
        at act.db.ebean.EbeanService$1.on(EbeanService.java:86)
        at act.event.EventBus.callOn(EventBus.java:1440)
        at act.event.EventBus.callOn(EventBus.java:1462)
        at act.event.EventBus.callOn(EventBus.java:1492)
        at act.event.EventBus._emit(EventBus.java:1353)
        at act.event.EventBus.emit(EventBus.java:807)
        at act.app.App.emit(App.java:1283)
        at act.app.App.refresh(App.java:746)
        at act.app.AppManager.load(AppManager.java:77)
        at act.app.AppManager$_F$1.visit(AppManager.java:145)
        at act.app.AppManager$_F$1.visit(AppManager.java:141)
        at org.osgl.Lang$Visitor.apply(Lang.java:2460)
        at org.osgl.Lang$Visitor.apply(Lang.java:2450)
        at act.app.AppScanner.scan(AppScanner.java:91)
        at act.app.AppScanner.scan(AppScanner.java:71)
        at act.app.AppManager.loadSingleApp(AppManager.java:55)
        at act.Act.startup(Act.java:336)
        at act.Act.startup(Act.java:1272)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.osgl.Lang.invokeStatic(Lang.java:8059)
        at act.Act.bootstrap(Act.java:1178)
        at act.Act.start(Act.java:688)
        at cn.anline.cx.sc.serve.Ann.main(Ann.java:7)
Caused by: java.lang.IllegalStateException: Native library for Attach API not available in this JRE
        at act.db.ebean.EbeanAgentLoader.getVirtualMachineImplementationFromEmbeddedOnes(EbeanAgentLoader.java:221)
        at act.db.ebean.EbeanAgentLoader.loadAgent(EbeanAgentLoader.java:96)
        ... 27 more
Caused by: java.lang.UnsatisfiedLinkError: no attach in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at sun.tools.attach.WindowsVirtualMachine.<clinit>(WindowsVirtualMachine.java:185)
        at act.db.ebean.EbeanAgentLoader.getVirtualMachineImplementationFromEmbeddedOnes(EbeanAgentLoader.java:199)
        ... 28 more
`

the same production package file, run at CentOS（The latest version 7.6.x）:
![QQ20190908-015326](https://user-images.githubusercontent.com/9036838/64478506-f7fb5f00-d1db-11e9-80bf-a84b386797c2.png)
everything is OK!

**Comment by jiankian** [comment]
Please use OpenJDK，do not use Oracle JDK and JRE
![image](https://user-images.githubusercontent.com/9036838/64485825-ccb65580-d257-11e9-8161-0f3c97812235.png)
