### ISSUE TITLE
Hotreload error - Provider has already registered for spec: class act.aaa.AAAService

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1201]
console log messages:

```
2019-09-14 07:29:30,846 INFO  a.a.App@[jobs-thread-1] - App starting ....
2019-09-14 07:29:32,863 INFO  o.m.d.connection@[jobs-thread-8] - Opened connection [connectionId{localValue:10, serverValue:271}] to localhost:27017
2019-09-14 07:29:32,878 WARN  a.a.DefaultAuditor@[jobs-thread-8] - Audit entity type not found. Auditing is disabled
2019-09-14 07:29:32,879 WARN  a.a.AppServiceRegistry@[jobs-thread-8] - Service type[class act.aaa.AAAService] already registered
2019-09-14 07:29:32,881 WARN  a.e.EventBus@[jobs-thread-8] - error calling event handler on DEPENDENCY_INJECTOR_LOADED
org.osgl.inject.InjectException: Provider has already registered for spec: class act.aaa.AAAService
	at org.osgl.inject.Genie.addIntoRegistry(Genie.java:763)
	at org.osgl.inject.Genie.addIntoRegistry(Genie.java:776)
	at org.osgl.inject.Genie.bindProviderToClass(Genie.java:721)
	at org.osgl.inject.Genie.registerProvider(Genie.java:717)
	at org.osgl.inject.Genie.registerProvider(Genie.java:608)
	at act.inject.genie.GenieInjector.registerDiBinder(GenieInjector.java:92)
	at act.event.EventBus$5.on(EventBus.java:1594)
	at act.event.EventBus$5.on(EventBus.java:1587)
	at act.event.EventBus.callOn(EventBus.java:1440)
	at act.event.EventBus.callOn(EventBus.java:1462)
	at act.event.EventBus.callOn(EventBus.java:1497)
	at act.event.EventBus._emitWithOnceBus(EventBus.java:1413)
	at act.event.EventBus.emit(EventBus.java:975)
	at act.app.App$6.on(App.java:1276)
	at act.event.EventBus.callNowIfEmitted(EventBus.java:1504)
	at act.event.EventBus._bind(EventBus.java:1243)
	at act.event.EventBus.bind(EventBus.java:615)
	at act.app.App.register(App.java:1272)
	at act.app.App.register(App.java:1263)
	at act.app.AppServiceBase.<init>(AppServiceBase.java:31)
	at act.aaa.AAAService.<init>(AAAService.java:101)
	at act.aaa.AAAService.<init>(AAAService.java:111)
	at act.aaa.AAAPlugin.initializeAAAService(AAAPlugin.java:228)
	at act.aaa.AAAPlugin.buildService(AAAPlugin.java:174)
	at act.aaa.AAAServiceFinder.ensureAAAIntegration(AAAServiceFinder.java:126)
	at act.aaa.AAAServiceFinderMethodAccess.invoke(Unknown Source)
	at act.job.bytecode.ReflectedJobInvoker.invoke(ReflectedJobInvoker.java:143)
	at act.job.bytecode.ReflectedJobInvoker.apply(ReflectedJobInvoker.java:110)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:112)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:93)
	at act.job.Job.runFollowingJobs(Job.java:435)
	at act.job.Job.run(Job.java:397)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:483)
	at act.event.EventBus.callOn(EventBus.java:1440)
	at act.event.EventBus.callOn(EventBus.java:1462)
	at act.event.EventBus.callOn(EventBus.java:1492)
	at act.event.EventBus._emit(EventBus.java:1353)
	at act.event.EventBus.emit(EventBus.java:807)
	at act.app.App.emit(App.java:1296)
	at act.app.App$5.run(App.java:827)
	at act.job.Job$4.apply(Job.java:454)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:535)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
This issue caused #1199
