### ISSUE TITLE
使用OnSysEvent时报空指针异常

### ISSUE THREAD

**Issue by Saharaqie** [actframework/actframework#1206]
版本：1.8.21.0
`@OnSysEvent(SysEventId.DEPENDENCY_INJECTOR_LOADED)
    public void on(EventBus eventBus) {
        eventBus.bind(EbeanConfigLoaded.class, new ActEventListenerBase<EbeanConfigLoaded>() {
            @Override
            public void on(EbeanConfigLoaded event) {
                ServerConfig config = event.source();
                config.addClass(UUIDGenerator.class);
            }
        });
    }`
自己初步判断是act.job.meta.JobMethodMetaInfo.method()中，根据class和name查方法时，未传入参数，查不到有参的方法
将代码改成这样可以正常运行
`@OnSysEvent(SysEventId.DEPENDENCY_INJECTOR_LOADED)
    public void on() {
        Act.app().eventBus().bind(EbeanConfigLoaded.class, new ActEventListenerBase<EbeanConfigLoaded>() {
            @Override
            public void on(EbeanConfigLoaded event) {
                ServerConfig config = event.source();
                config.addClass(UUIDGenerator.class);
            }
        });
    }`

**Comment by Saharaqie** [comment]
github的排版还是不会用，凑合看吧

**Comment by greenlaw110** [comment]
Root cause identified, the meta information of method `on` is still not completely constructed when system event `DEPENDENCY_INJECTOR_LOADED` triggered, rather `DEPENDENCY_INJECTOR_PROVISIONED` which triggered after `DEPENDENCY_INJECTOR_LOADED` will loading the parameter and method information for Job handler meta:

![image](https://user-images.githubusercontent.com/216930/65765766-7ceaf000-e16c-11e9-99bf-16c1033b9783.png)

The gotcha here is DO NOT declare event listener using `OnSysEvent` annotation before `SINGLETON_PROVISIONED` which is raised after `DEPENDENCY_INJECTOR_PROVISIONED` event

**Comment by Saharaqie** [comment]
`SINGLETON_PROVISIONED`这个事件好像是在**Ebean**的对象加载之后，所以还没有注册成功就调用了这个`IdGenerator`。
```java
Caused by: java.lang.IllegalStateException: No custom IdGenerator registered with name uuid
	at io.ebeaninternal.server.deploy.parse.AnnotationFields.readGenValue(AnnotationFields.java:552)
	at io.ebeaninternal.server.deploy.parse.AnnotationFields.readField(AnnotationFields.java:207)
	at io.ebeaninternal.server.deploy.parse.AnnotationFields.parse(AnnotationFields.java:114)
	at io.ebeaninternal.server.deploy.parse.ReadAnnotations.readInitial(ReadAnnotations.java:29)
	... 27 common frames omitted
```
