### ISSUE TITLE
"The response has already been started" error

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1208]
When it raised an exception in template engine it always log the following error messages:

```
java.lang.IllegalStateException: UT000002: The response has already been started
	at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1406)
	at act.xio.undertow.UndertowResponse._setStatusCode(UndertowResponse.java:232)
	at act.ActResponse.status(ActResponse.java:142)
	at act.ActResponse.status(ActResponse.java:38)
	at org.osgl.mvc.result.Result.applyStatus(Result.java:229)
	at org.osgl.mvc.result.Result.apply(Result.java:250)
	at act.xio.NetworkHandler.handleException(NetworkHandler.java:257)
	at act.xio.NetworkHandler.handle(NetworkHandler.java:157)
	at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:48)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
```

**Comment by CrossLee** [comment]
reproduced in 1.9.2-SNAPSHOT

**Comment by greenlaw110** [comment]
@CrossLee are you able to provide a simple project that reproduce this issue on 1.9.2-SNAPSHOT?

**Comment by CrossLee** [comment]
it's hard to reproduce again...
if any update, i will comment here.
