### ISSUE TITLE
`UnexpectedException: type not recognized: ? extends T` - JsonDtoPatch logic issue

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1218]
A `Hello` class:

```java
public class Hello {
    private Logger logger = Logger.getLogger(Hello.class);
}
```

Controller:

```java
public class HelloTest {
    private final Hello hello = new Hello();

    @GetAction
    public void test() {

    }
}
```

Starting the app it raise the error, here is the error stack:
```
org.osgl.exception.UnexpectedException: type not recognized: ? extends T
	at org.osgl.util.E.unexpected(E.java:179)
	at org.osgl.inject.BeanSpec.rawTypeOf(BeanSpec.java:995)
	at org.osgl.inject.BeanSpec.<init>(BeanSpec.java:157)
	at org.osgl.inject.BeanSpec.of(BeanSpec.java:1039)
	at org.osgl.inject.BeanSpec.of(BeanSpec.java:1062)
	at org.osgl.inject.BeanSpec.fields(BeanSpec.java:680)
	at org.osgl.inject.BeanSpec.nonStaticFields(BeanSpec.java:599)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:52)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:65)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:65)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:65)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:65)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:65)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:65)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:65)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:65)
	at act.inject.param.JsonDtoPatch.of(JsonDtoPatch.java:112)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:321)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createControllerAction(ReflectedHandlerInvoker.java:1200)
	at act.Act$Mode.createRequestHandler(Act.java:164)
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:424)
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:348)
	at act.handler.builtin.controller.RequestHandlerProxy.actionHandler(RequestHandlerProxy.java:173)
	at act.apidoc.Endpoint.explore(Endpoint.java:414)
	at act.apidoc.Endpoint.<init>(Endpoint.java:277)
	at act.apidoc.ApiManager$4.visit(ApiManager.java:207)
	at act.route.Router.visit(Router.java:221)
	at act.route.Router.visit(Router.java:224)
	at act.route.Router.accept(Router.java:180)
	at act.apidoc.ApiManager.load(ApiManager.java:202)
	at act.apidoc.ApiManager.load(ApiManager.java:144)
	at act.apidoc.ApiManager$1.run(ApiManager.java:101)
	at act.job.Job$4.apply(Job.java:454)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:112)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:93)
	at act.job.Job.runFollowingJobs(Job.java:435)
	at act.job.Job.run(Job.java:397)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:483)
	at act.event.EventBus.callOn(EventBus.java:1440)
	at act.event.EventBus.callOn(EventBus.java:1462)
	at act.event.EventBus.callOn(EventBus.java:1492)
	at act.event.EventBus._emit(EventBus.java:1353)
	at act.event.EventBus.emit(EventBus.java:807)
	at act.app.App.emit(App.java:1302)
	at act.app.App$5.run(App.java:841)
	at act.job.Job$4.apply(Job.java:454)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:112)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:93)
	at act.job.Job.runFollowingJobs(Job.java:435)
	at act.job.Job.run(Job.java:397)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:483)
	at act.event.EventBus.callOn(EventBus.java:1440)
	at act.event.EventBus.callOn(EventBus.java:1462)
	at act.event.EventBus.callOn(EventBus.java:1492)
	at act.event.EventBus._emit(EventBus.java:1353)
	at act.event.EventBus.emit(EventBus.java:807)
	at act.app.App.emit(App.java:1302)
	at act.app.App$4.run(App.java:816)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:535)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
Although the issue should be avoid by declaring the `logger` in `Hello` class as static, it still reveals problem of ActFramework during JSON DTO patching process

1. `hello` is declared as `final` in `HelloTest` class, thus it shall not generate JsonDto class for it, since it cannot be bound to any request info.

2. Add `@NoBind` to `logger` in `Hello` class doesn't fix the issue, it still tried to process `logger` field. While adding `@NoBind` to `hello` in `HelloTest` class does fix the issue.
