### ISSUE TITLE
renderJson(null) cause response stream closed error

### ISSUE THREAD

**Issue by CrossLee** [actframework/actframework#1238]
act-starter-parent version : 1.8.28.0

response stream closed while render a null json object in controller.

code:
```renderJson(null);```
error stack:
```
2019-11-04 17:17:12,289 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-3] - Server error encountered on handling request: [GET]/t/t1
org.osgl.exception.UnexpectedIOException: java.io.IOException: Stream closed
	at org.osgl.util.E.ioException(E.java:254)
	at org.osgl.util.IO.flush(IO.java:982)
	at org.osgl.mvc.result.RenderContent.apply(RenderContent.java:261)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:332)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:229)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1366)
	at act.route.Router$ContextualHandler.handle(Router.java:1771)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:183)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Stream closed
	at sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:45)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:140)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at org.osgl.util.IO.flush(IO.java:980)
	... 9 common frames omitted
2019-11-04 17:17:12,290 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-3] - error rendering exception handle result
java.lang.IllegalStateException: UT000002: The response has already been started
	at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1406)
	at act.xio.undertow.UndertowResponse._setStatusCode(UndertowResponse.java:232)
	at act.ActResponse.status(ActResponse.java:142)
	at act.ActResponse.status(ActResponse.java:38)
	at org.osgl.mvc.result.Result.applyStatus(Result.java:229)
	at org.osgl.mvc.result.Result.apply(Result.java:250)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:332)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:248)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1366)
	at act.route.Router$ContextualHandler.handle(Router.java:1771)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:183)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

expected:
a null object return to frontend.

screenshoot:
![image](https://user-images.githubusercontent.com/4584905/68109720-34baac80-ff26-11e9-94dc-e7f4c4317313.png)

**Comment by greenlaw110** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/216930/69477286-77dab200-0e38-11ea-8b33-5cb4bb47ca80.png)

Running the app:

![image](https://user-images.githubusercontent.com/216930/69477290-8b861880-0e38-11ea-91d0-745133f95905.png)

Send request:

![image](https://user-images.githubusercontent.com/216930/69477292-950f8080-0e38-11ea-8aec-8a4eaee9f4e4.png)
