### ISSUE TITLE
act-gallery/jobs demo start up error on act-1.8.29 

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1239]
Updated https://github.com/act-gallery/jobs project to act-1.8.29, start the app will cause the following error:

```
2019-11-06 06:24:47,006 WARN  a.j.JobExceptionListenerManager@[jobs-thread-2] - Job exception encountered on running job[compile-api-book]
java.lang.IllegalArgumentException: null
	at org.osgl.util.E.illegalArgumentIf(E.java:642)
	at org.osgl.util.S.requireNotBlank(S.java:516)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:50)
	at act.inject.param.JsonDtoPatch.of(JsonDtoPatch.java:120)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:325)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createControllerAction(ReflectedHandlerInvoker.java:1225)
	at act.Act$Mode.createRequestHandler(Act.java:164)
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:428)
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:352)
	at act.handler.builtin.controller.RequestHandlerProxy.actionHandler(RequestHandlerProxy.java:173)
	at act.apidoc.Endpoint.explore(Endpoint.java:419)
	at act.apidoc.Endpoint.<init>(Endpoint.java:279)
	at act.apidoc.ApiManager$4.visit(ApiManager.java:230)
	at act.route.Router.visit(Router.java:221)
	at act.route.Router.visit(Router.java:224)
	at act.route.Router.accept(Router.java:180)
	at act.apidoc.ApiManager.load(ApiManager.java:225)
	at act.apidoc.ApiManager.load(ApiManager.java:147)
	at act.apidoc.ApiManager$1.run(ApiManager.java:103)
	at act.job.Job$4.apply(Job.java:454)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:112)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:93)
	at act.job.Job.runFollowingJobs(Job.java:435)
	at act.job.Job.run(Job.java:397)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:483)
	at act.event.EventBus.callOn(EventBus.java:1440)
	at act.event.EventBus.callOn(EventBus.java:1462)
	at act.event.EventBus.callOn(EventBus.java:1492)
	at act.event.EventBus._emit(EventBus.java:1353)
	at act.event.EventBus.emit(EventBus.java:807)
	at act.app.App.emit(App.java:1303)
	at act.app.App$5.run(App.java:842)
	at act.job.Job$4.apply(Job.java:454)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:112)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:93)
	at act.job.Job.runFollowingJobs(Job.java:435)
	at act.job.Job.run(Job.java:397)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:483)
	at act.event.EventBus.callOn(EventBus.java:1440)
	at act.event.EventBus.callOn(EventBus.java:1462)
	at act.event.EventBus.callOn(EventBus.java:1492)
	at act.event.EventBus._emit(EventBus.java:1353)
	at act.event.EventBus.emit(EventBus.java:807)
	at act.app.App.emit(App.java:1303)
	at act.app.App$4.run(App.java:817)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:535)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
When I set a breakpoint in place then it won't hit the exception, looks like the time sequence of enhancing the method with `@Named` annotation is not correct
