### ISSUE TITLE
Improve error reporting on "Unknown accept content type"

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#124]
Act website console has a lot of error messages like the follows:

```
org.osgl.exception.UnsupportedException: Unknown accept content type
        at org.osgl.util.E.unsupport(E.java:153)
        at act.view.RenderAny.apply(RenderAny.java:42)
        at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:247)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:177)
        at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:27)
        at act.route.Router$ContextualHandler.handle(Router.java:928)
        at act.xio.NetworkHandler$1.run(NetworkHandler.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

It would be good print out the request URL and the `Accept` header info for troubleshooting

**Comment by greenlaw110** [comment]
fixed in 1.2.0
