### ISSUE TITLE
Ehcache 在 热重载时 无法找到 EhCacheServiceProvider 的 _reset 方法。

### ISSUE THREAD

**Issue by IceCream-Open** [actframework/actframework#1243]
actframework 版本 1.8.29
ehcache 版本 2.10.5

错误栈：

```
org.osgl.exception.UnexpectedNoSuchMethodException: Method not found by name[_reset] and supplied arguments on class org.osgl.cache.impl.EhCacheServiceProvider
	at org.osgl.Lang.invokeMethod(Lang.java:8247)
	at org.osgl.Lang.invokeStatic(Lang.java:8043)
	at org.osgl.cache.CacheServiceProvider$Impl$3.reset(CacheServiceProvider.java:126)
	at org.osgl.cache.CacheServiceProvider$Impl$5.reset(CacheServiceProvider.java:213)
	at act.app.App.initCache(App.java:1601)
	at act.app.App.refresh(App.java:763)
	at act.app.App.refresh(App.java:677)
	at act.app.App.checkUpdates(App.java:545)
	at act.app.App.checkUpdates(App.java:515)
	at act.xio.NetworkHandler.handle(NetworkHandler.java:124)
	at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:58)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
```

![image](https://user-images.githubusercontent.com/32815944/68939979-f3a38180-07dc-11ea-8392-c119f88cad7d.png)

**Comment by greenlaw110** [comment]
This is due to `Lang.invokeMethod()` does not support non-public method. The issue has been fixed in osgl-tool-1.21.1
