### ISSUE TITLE
echo error when first run mvn package

### ISSUE THREAD

**Issue by flyingbeecd** [actframework/actframework#1251]
2019-11-21 10:20:45,595 INFO  a.a.App@[Thread-9] - App shutting down ....
2019-11-21 10:20:45,606 WARN  a.j.JobExceptionListenerManager@[jobs-thread-5] - Job exception encountered on running job[sql_db_service[default] - raise DbServiceInitialized event]
org.osgl.exception.UnexpectedException: Concurrent modification issue encountered on handling event: act.db.DbServiceInitialized
        at org.osgl.util.E.unexpected(E.java:179)
        at act.event.EventBus.callOn(EventBus.java:1482)
        at act.event.EventBus.callOn(EventBus.java:1497)
        at act.event.EventBus._emitWithOnceBus(EventBus.java:1413)
        at act.event.EventBus.emit(EventBus.java:975)
        at act.db.sql.SqlDbService$4.run(SqlDbService.java:142)
        at act.job.Job$4.apply(Job.java:454)
        at act.job.Job.doJob(Job.java:412)
        at act.job.Job.run(Job.java:336)
        at act.job.JobManager$ContextualJob$1.apply(JobManager.java:535)
        at act.job.Job.doJob(Job.java:412)
        at act.job.Job.run(Job.java:336)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-11-21 10:20:45,615 INFO  c.a.d.p.DruidDataSource@[Thread-9] - {dataSource-1} closing ...
2019-11-21 10:20:45,619 INFO  c.a.d.p.DruidDataSource@[Thread-9] - {dataSource-1} closed
-------
first run mvn package ，we will get this errors
and then run again,will be fine

**Comment by greenlaw110** [comment]
@flyingbeecd 

From the console log, it appears to be Hibernate DbService did not finish initialization before Act-Test shutdown the app. It is a clear problem, but the error can be ignore for you. It won't impact you from building the package.

**Comment by greenlaw110** [comment]
@flyingbeecd 

Can you help me to run `mvn clean package` on [todo-hibernate](https://github.com/act-gallery/todo-hibernate) project and see if you can get the similar issue happen in your environment ?
