### ISSUE TITLE
IE 9 browser，got a strange error！

### ISSUE THREAD

**Issue by flyingbeecd** [actframework/actframework#1260]
act version：1.8.29
browser: IE 9

Request	

```
GET /cmd/tk.list HTTP/1.1
Accept	application/x-ms-application, image/jpeg, application/xaml+xml, image/gif, imagepeg, application/x-ms-xbap, */*
Accept-Language	zh-CN
User-Agent	Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
Accept-Encoding	gzip, deflate
Host	localhost:8080
Connection	Keep-Alive
```

Error stack

```
2019-12-12_14:05:39.632 [XNIO-1 task-1] ERROR a.h.b.controller.RequestHandlerProxy - Server error encountered on handling request: [GET]/cmd/tk.list
org.osgl.exception.UnexpectedException: Cannot apply text result to format: jpg
	at org.osgl.util.E.unexpected(E.java:179)
	at act.controller.Controller$Util.inferPrimitiveResult(Controller.java:1796)
	at act.controller.Controller$Util.inferResult(Controller.java:1935)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.transform(ReflectedHandlerInvoker.java:1134)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1081)
	at 
act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:702)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:562)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:210)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1380)
	at act.route.Router$ContextualHandler.handle(Router.java:1771)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:191)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

![QQ图片20191213114005](https://user-images.githubusercontent.com/11328615/70767721-57e64080-1d9d-11ea-8013-d987d0fa02b9.png)

**Comment by greenlaw110** [comment]
Root cause: [Internet Explorer Accepts Polluting the Internet](https://www.newmediacampaigns.com/blog/browser-rest-http-accept-headers)
