### ISSUE TITLE
No response on certain error scenario

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1264]
I happened to put a request handler method as private:

```java
    @GetAction("/tst/vehicle-size")
    private int quoteVehicleNumber(int quoteId) {
        ...
    }
```

And when I call to that endpoint I got no response from app:

![image](https://user-images.githubusercontent.com/216930/71220458-a0ad7480-231c-11ea-8549-956dc5c2c54b.png)

The backend console logs the error stack as:

```
org.osgl.exception.UnexpectedException: java.lang.NoSuchMethodException: com.pixolut.mb.agent.QuoteService.quoteVehicleNumber(int)
	at org.osgl.util.E.unexpected(E.java:190)
	at act.xio.WebSocketConnectionHandler.<init>(WebSocketConnectionHandler.java:105)
	at act.xio.undertow.UndertowWebSocketConnectionHandler.<init>(UndertowWebSocketConnectionHandler.java:40)
	at act.xio.undertow.UndertowNetwork.internalCreateWsConnHandler(UndertowNetwork.java:118)
	at act.xio.NetworkBase.createWebSocketConnectionHandler(NetworkBase.java:124)
	at act.handler.builtin.controller.RequestHandlerProxy.tryGenerateWebSocketConnectionHandler(RequestHandlerProxy.java:413)
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:423)
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:352)
	at act.handler.builtin.controller.RequestHandlerProxy.express(RequestHandlerProxy.java:284)
	at act.handler.DelegateRequestHandler.express(DelegateRequestHandler.java:42)
	at act.xio.NetworkHandler.handle(NetworkHandler.java:241)
	at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:58)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
Caused by: java.lang.NoSuchMethodException: com.pixolut.mb.agent.QuoteService.quoteVehicleNumber(int)
	at java.lang.Class.getMethod(Class.java:1786)
	at act.xio.WebSocketConnectionHandler.<init>(WebSocketConnectionHandler.java:101)
	... 18 common frames omitted
```

**Comment by greenlaw110** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/216930/71227217-8bdbdb80-2332-11ea-8530-13740fb24bdf.png)
