### ISSUE TITLE
Exception handling controller with field class without generic parameter specified

### ISSUE THREAD

**Issue by IceCream-Open** [actframework/actframework#1286]
当 Controller 内拥有正常（并非通过依赖注入）的成员变量时，会将这个变量解析为 Action 的参数。

```
    public String test="";
    
    @GetAction
    public void home(@DefaultValue("World") @Output String who) {
    }
```

API Book: 

![image](https://user-images.githubusercontent.com/32815944/72964454-eca87900-3df4-11ea-8221-f92f5b758de8.png)

当成员变量为某个类，但为指定明确泛型，则会触发异常。
```
    public TestResp resp=new TestResp(0,null);
    public static class TestResp<T> {
        private Integer code;
        private T result;
        public TestResp(Integer code, T result) {
            this.code = code;
            this.result = result;
        }
    }
```
异常栈
```
2020-01-23 15:18:58,429 INFO  a.a.ApiManager@[jobs-thread-4] - start compiling API book
2020-01-23 15:18:58,437 WARN  a.j.JobExceptionListenerManager@[jobs-thread-4] - Job exception encountered on running job[compile-api-book]
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.osgl.util.ImmutableList.get(ImmutableList.java:143)
	at org.osgl.inject.BeanSpec.fields(BeanSpec.java:696)
	at org.osgl.inject.BeanSpec.nonStaticFields(BeanSpec.java:616)
	at act.inject.param.JsonDtoPatch.<init>(JsonDtoPatch.java:53)
	at act.inject.param.JsonDtoPatch.of(JsonDtoPatch.java:120)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:325)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createControllerAction(ReflectedHandlerInvoker.java:1229)
	at act.Act$Mode.createRequestHandler(Act.java:164)
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:435)
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:359)
	at act.handler.builtin.controller.RequestHandlerProxy.actionHandler(RequestHandlerProxy.java:174)
	at act.apidoc.Endpoint.explore(Endpoint.java:417)
	at act.apidoc.Endpoint.<init>(Endpoint.java:277)
	at act.apidoc.ApiManager$4.visit(ApiManager.java:230)
	at act.route.Router.visit(Router.java:221)
	at act.route.Router.accept(Router.java:180)
	at act.apidoc.ApiManager.load(ApiManager.java:225)
	at act.apidoc.ApiManager.load(ApiManager.java:147)
	at act.apidoc.ApiManager$1.run(ApiManager.java:103)
	at act.job.Job$4.apply(Job.java:454)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:112)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:93)
	at act.job.Job.runFollowingJobs(Job.java:435)
	at act.job.Job.run(Job.java:397)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:483)
	at act.event.EventBus.callOn(EventBus.java:1440)
	at act.event.EventBus.callOn(EventBus.java:1462)
	at act.event.EventBus.callOn(EventBus.java:1492)
	at act.event.EventBus._emit(EventBus.java:1353)
	at act.event.EventBus.emit(EventBus.java:807)
	at act.app.App.emit(App.java:1309)
	at act.app.App$5.run(App.java:844)
	at act.job.Job$4.apply(Job.java:454)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:535)
	at act.job.Job.doJob(Job.java:412)
	at act.job.Job.run(Job.java:336)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

经过我多次测试，类只存在一个泛型成员变量的时候则不会触发本异常。
触发异常后，API Book 无法正常访问，但主程序不受影响。

**Comment by greenlaw110** [comment]
Caused by https://github.com/osglworks/java-di/issues/57
