### ISSUE TITLE
vscode 运行报错

### ISSUE THREAD

**Issue by scofier** [actframework/actframework#1306]
```
13:32:29.485 [main] INFO  a.a.DbServiceManager - DB service not initialized: No DB plugin found
13:32:29.804 [Thread-4] INFO  a.a.App - App shutting down ....
Exception in thread "main" java.lang.NullPointerException
        at act.util.ClassInfoByteCodeScanner$_ByteCodeVisitor.visit(ClassInfoByteCodeScanner.java:78)
        at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
        at act.util.ClassFinderByteCodeScanner$_ByteCodeVisitor.visit(ClassFinderByteCodeScanner.java:59)
        at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
        at act.controller.bytecode.ControllerByteCodeScanner$_ByteCodeVisitor.visit(ControllerByteCodeScanner.java:129)
        at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
```

**Comment by greenlaw110** [comment]
@scofier please report the ActFramework version.

**Comment by scofier** [comment]
> @scofier please report the ActFramework version.

<parent>
    <groupId>org.actframework</groupId>
    <artifactId>act-starter-parent</artifactId>
    <version>1.8.31.0</version>
  </parent>

**Comment by greenlaw110** [comment]
@scofier what's the java version? And how do you run it in vscode? Do you have any issue if run the app from command line (`mvn compile act:run`) or other ide (idea/netbeans/eclipse)?

**Comment by scofier** [comment]
> @scofier what's the java version? And how do you run it in vscode? Do you have any issue if run the app from command line (`mvn compile act:run`) or other ide (idea/netbeans/eclipse)?

run with `Visual Studio Code`
