### ISSUE TITLE
"type not recognized: MODEL_TYPE" Error when using a DaoBase subclass as Controller

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#132]
Error stack:

```
org.osgl.exception.UnexpectedException: type not recognized: MODEL_TYPE
	at org.osgl.util.E.unexpected(E.java:96)
	at org.osgl.inject.BeanSpec.rawTypeOf(BeanSpec.java:535)
	at act.db.morphia.util.MorphiaDaoBaseLoader.load(MorphiaDaoBaseLoader.java:46)
	at act.db.morphia.util.MorphiaDaoBaseLoader.load(MorphiaDaoBaseLoader.java:33)
	at org.osgl.inject.Genie$4.get(Genie.java:628)
	at org.osgl.inject.Genie$5.get(Genie.java:670)
	at org.osgl.inject.Genie.get(Genie.java:345)
	at act.inject.genie.GenieInjector.get(GenieInjector.java:86)
	at act.inject.param.ProvidedValueLoader.load(ProvidedValueLoader.java:62)
	at act.inject.param.FieldLoader.applyTo(FieldLoader.java:42)
	at act.inject.param.ParamValueLoaderService$5.load(ParamValueLoaderService.java:550)
	at act.inject.param.JsonParamValueLoader.load(JsonParamValueLoader.java:71)
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:49)
	at act.inject.param.ParamValueLoaderService$3.load(ParamValueLoaderService.java:212)
	at act.inject.param.ParamValueLoaderService$6.load(ParamValueLoaderService.java:632)
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:49)
	at act.inject.param.ParamValueLoaderService.loadHostBean(ParamValueLoaderService.java:141)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.controllerInstance(ReflectedHandlerInvoker.java:402)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:201)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:42)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:445)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:187)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1226)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:98)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Souce code

```java
@Controller("/todo")
@ResponseContentType(H.MediaType.JSON)
public static class Service extends MorphiaDaoWithLongId<Todo> {

    private String sid;

    @PostAction
    public Todo create(Todo todo, Router router) {
        return save(todo);
    }

}
```

**Note** I won't get the the exception if there is no `private String sid` line, i.e. if framework identify the controller class is a singleton.

**Comment by greenlaw110** [comment]
Fixed in 1.0.7
