### ISSUE TITLE
org.osgl.exception.UnexpectedException: Cannot load type: Bookmark

### ISSUE THREAD

**Issue by ghost** [actframework/actframework#1327]
Hi support,

I download the simple-crud-service, when I run mvn clean install

I encounter this error,Please kindly see help, thanks. 

org.osgl.exception.UnexpectedException: Cannot load type: Bookmark
        at act.test.util.YamlLoader.loadModelType(YamlLoader.java:293)
        at act.test.util.YamlLoader.resolve(YamlLoader.java:213)
        at act.test.util.YamlLoader.parse(YamlLoader.java:185)
        at act.test.util.YamlLoader.loadFixture(YamlLoader.java:119)
        at act.test.Test.loadFixtures(Test.java:132)
        at act.test.TestMethodAccess.invoke(Unknown Source)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1086)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1072)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:702)
        at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
        at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:562)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:210)
        at act.app.ActionContext.proceedWithHandler(ActionContext.java:1380)
        at act.route.Router$ContextualHandler.handle(Router.java:1771)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:191)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by greenlaw110** [comment]
@dsun9 please try this one:
https://github.com/act-gallery/bookmark

**Comment by greenlaw110** [comment]
actually @dsun9 where did you get simple-crud-service project?

I tried the one at https://github.com/act-gallery/simple-crud-service and I don't have the issue when running `./test`:
![image](https://user-images.githubusercontent.com/216930/79626331-b881f180-8172-11ea-8ba8-3bf22bd7360b.png)

I just did a version update to the project, probably you want to checkout the latest version at https://github.com/act-gallery/simple-crud-service

**Comment by dsun9** [comment]
Thanks, I tried, same error. I remember the first time I ran mvn, windows firewall popup asking if allow, i chose cancel. is this the reason?

**Comment by greenlaw110** [comment]
Probably, mvn is trying to download dependencies and you literally prevent that from happening.
