### ISSUE TITLE
按用户手册启动时报错 Caused by: org.osgl.exception.UnexpectedException: java.lang.NoSuchMethodException: java.lang.String.<init>([C,boolean)

### ISSUE THREAD

**Issue by loveexception** [actframework/actframework#1334]
我使用学习手册： http://actframework.org/doc/get_start.md 
1。 java 
```
╰─➤  java -version                                                                                                                   1 ↵
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
```
2. maven 
```
╰─➤  mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 13.0.2, vendor: N/A, runtime: /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
Default locale: zh_CN_#Hans, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.3", arch: "x86_64", family: "mac"
```
3. 建立项目
```
╰─➤  mvn archetype:generate -B \
    -DgroupId=com.mycom.helloworld \
    -DartifactId=helloworld \
    -DappName=helloworld \
    -DarchetypeGroupId=org.actframework \
    -DarchetypeArtifactId=archetype-quickstart \
    -DarchetypeVersion=1.8.21.0
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.1.2:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.1.2:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.1.2:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Batch mode
[INFO] Archetype repository not defined. Using the one from [org.actframework:archetype-quickstart:1.8.8.9] found in catalog remote
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: archetype-quickstart:1.8.21.0
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.mycom.helloworld
[INFO] Parameter: artifactId, Value: helloworld
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: package, Value: com.mycom.helloworld
[INFO] Parameter: packageInPathFormat, Value: com/mycom/helloworld
[INFO] Parameter: package, Value: com.mycom.helloworld
[INFO] Parameter: groupId, Value: com.mycom.helloworld
[INFO] Parameter: artifactId, Value: helloworld
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Executing META-INF/archetype-post-generate.groovy post-generation script
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/mao/.m2/repository/org/codehaus/groovy/groovy/2.4.16/groovy-2.4.16.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Project created from Archetype in dir: /Users/mao/IdeaProjects/tico_work/act/helloworld
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:04 min
[INFO] Finished at: 2020-04-23T18:44:08+08:00
[INFO] ------------------------------------------------------------------------
```
╰─➤  tree
```
╰─➤  tree
.
├── act-db.log
├── act.log
├── pack
├── pack.bat
├── pom.xml
├── run_dev
├── run_dev.bat
├── run_prod
├── src
│   ├── main
│   │   ├── java
│   │   │   └── com
│   │   │       └── mycom
│   │   │           └── helloworld
│   │   │               └── AppEntry.java
│   │   └── resources
│   │       ├── com
│   │       │   └── mycom
│   │       │       └── helloworld
│   │       ├── conf
│   │       │   ├── app.properties
│   │       │   ├── prod
│   │       │   │   └── app.properties
│   │       │   └── uat
│   │       │       └── app.properties
│   │       ├── logback.xml
│   │       ├── rythm
│   │       │   └── com
│   │       │       └── mycom
│   │       │           └── helloworld
│   │       │               └── AppEntry
│   │       │                   └── home.html
│   │       └── test
│   │           └── scenarios.yml
│   └── test
│       └── java
│           └── com
│               └── mycom
│                   └── helloworld
├── target
│   ├── classes
│   │   ├── act_scripts
│   │   │   ├── run
│   │   │   ├── run.bat
│   │   │   ├── start
│   │   │   └── start.bat
│   │   ├── com
│   │   │   └── mycom
│   │   │       └── helloworld
│   │   │           └── AppEntry.class
│   │   ├── conf
│   │   │   ├── app.properties
│   │   │   ├── prod
│   │   │   │   └── app.properties
│   │   │   └── uat
│   │   │       └── app.properties
│   │   ├── logback.xml
│   │   ├── rythm
│   │   │   └── com
│   │   │       └── mycom
│   │   │           └── helloworld
│   │   │               └── AppEntry
│   │   │                   └── home.html
│   │   └── test
│   │       └── scenarios.yml
│   ├── dependency-maven-plugin-markers
│   │   └── org.actframework-act-starter-support-jar-1.8.181559338356
│   ├── dist
│   │   └── Dockerfile
│   ├── generated-sources
│   │   └── annotations
│   ├── maven-status
│   │   └── maven-compiler-plugin
│   │       └── compile
│   │           └── default-compile
│   │               ├── createdFiles.lst
│   │               └── inputFiles.lst
│   └── stage
│       └── act_scripts
│           ├── Dockerfile
│           ├── Dockerimage
│           ├── run
│           ├── run.bat
│           ├── start
│           └── start.bat
├── test
└── test.bat

49 directories, 38 files
```

4。 启动hello world 
```
╰─➤  mvn compile act:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.mycom.helloworld:helloworld >-------------------
[INFO] Building My Awesome Application 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ helloworld ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create-timestamp (default) @ helloworld ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.4:create (default) @ helloworld ---
[INFO] ShortRevision tag detected. The value is '4'.
[INFO] Executing: /bin/sh -c cd '/Users/mao/IdeaProjects/tico_work/act/helloworld' && 'git' 'rev-parse' '--verify' '--short=4' 'HEAD'
[INFO] Working directory: /Users/mao/IdeaProjects/tico_work/act/helloworld
[INFO] Storing buildNumber: 200423_1848 at timestamp: yyMMdd_HHmm
[WARNING] Cannot get the branch information from the git repository:
Detecting the current branch failed: fatal: 不是一个 git 仓库（或者任何父目录）：.git

[INFO] ShortRevision tag detected. The value is '4'.
[INFO] Executing: /bin/sh -c cd '/Users/mao/IdeaProjects/tico_work/act/helloworld' && 'git' 'rev-parse' '--verify' '--short=4' 'HEAD'
[INFO] Working directory: /Users/mao/IdeaProjects/tico_work/act/helloworld
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ helloworld ---
[INFO] argLine set to -javaagent:/Users/mao/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/Users/mao/IdeaProjects/tico_work/act/helloworld/target/jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ helloworld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-dependency-plugin:3.0.2:unpack (unpack) @ helloworld ---
[INFO] Configured Artifact: org.actframework:act-starter-support:1.8.18:jar
[INFO] Unpacking /Users/mao/.m2/repository/org/actframework/act-starter-support/1.8.18/act-starter-support-1.8.18.jar to /Users/mao/IdeaProjects/tico_work/act/helloworld/target/stage with includes "act_scripts/**" and excludes ""
[INFO]
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ helloworld ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/mao/IdeaProjects/tico_work/act/helloworld/target/classes
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:copy-resources (copy-scripts) @ helloworld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-resources-plugin:3.0.2:copy-resources (copy-dockerfile) @ helloworld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- act-maven-plugin:1.8.12.0:run (default-cli) @ helloworld ---
[INFO] Listening for jpda connection at 5005
Listening for transport dt_socket at address: 5005
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.osgl.util.Unsafe (file:/Users/mao/.m2/repository/org/osgl/osgl-tool/1.19.2/osgl-tool-1.19.2.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.osgl.util.Unsafe
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.osgl.util.FastStr.toString(FastStr.java:584)
	at org.osgl.util.FastStr.toLowerCase(FastStr.java:1276)
	at org.osgl.util.FastStr.toLowerCase(FastStr.java:47)
	at org.osgl.util.StrBase.toLowerCase(StrBase.java:1551)
	at org.osgl.util.Keyword.init(Keyword.java:509)
	at org.osgl.util.Keyword.<init>(Keyword.java:243)
	at org.osgl.util.Keyword.of(Keyword.java:442)
	at act.conf.Config.canonical(Config.java:214)
	at act.conf.AppConfigKey.<init>(AppConfigKey.java:1324)
	at act.conf.AppConfigKey.<init>(AppConfigKey.java:1320)
	at act.conf.AppConfigKey.<clinit>(AppConfigKey.java:61)
	at act.Act.bootstrap(Act.java:1161)
	at act.Act.start(Act.java:676)
	at com.mycom.helloworld.AppEntry.main(AppEntry.java:36)
Caused by: org.osgl.exception.UnexpectedException: java.lang.NoSuchMethodException: java.lang.String.<init>([C,boolean)
	at org.osgl.util.E.unexpected(E.java:189)
	at org.osgl.util.Unsafe.<clinit>(Unsafe.java:50)
	... 14 more
Caused by: java.lang.NoSuchMethodException: java.lang.String.<init>([C,boolean)
	at java.base/java.lang.Class.getConstructor0(Class.java:3350)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2554)
	at org.osgl.util.Unsafe.<clinit>(Unsafe.java:44)
	... 14 more
sub process returned with exit code: 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.111 s
[INFO] Finished at: 2020-04-23T18:48:50+08:00
[INFO] ------------------------------------------------------------------------

```
从日志上看是 osgl 安全 没有找到 一个方法。。。。
我想应该是一种设置问题。

**Comment by loveexception** [comment]
有关版本，我安装了三个版本 。 openjdk 1.8 ,openjdk 13 , oracle1.8 
还 是有这种问题。 
╰─➤ jenv versions
system
1.8
1.8.0.221
1.8.0.251
1.8.0.252
13.0
13.0.2
64-
Home
openjdk64-1.8.0.252
openjdk64-13.0.2 (set by /Users/mao/.jenv/version)
oracle64-1.8.0.221
oracle64-1.8.0.251

**Comment by loveexception** [comment]
OK 我删除了 其它的 版本 jdk 
基本确定是由于mvn 找jdk 方法是使用java_HOME 
所以 jenv 不能管理。
