### ISSUE TITLE
The error triggered during rendering response get warned twice

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#1341]
The error is caused by missing template.

The error log:

```
2020-06-28 08:38:20,399 WARN  a.Act@[XNIO-1 task-1] - Error:
org.osgl.exception.UnsupportedException: Template[com/mycom/helloworld/AppEntry/home] not found
	at org.osgl.util.E.unsupport(E.java:573)
	at act.view.RenderAny.apply(RenderAny.java:96)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:346)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:243)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1456)
	at act.route.Router$ContextualHandler.handle(Router.java:1818)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-06-28 08:38:20,402 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-1] - Server error encountered on handling request: [GET]/hello
org.osgl.exception.UnsupportedException: Template[com/mycom/helloworld/AppEntry/home] not found
	at org.osgl.util.E.unsupport(E.java:573)
	at act.view.RenderAny.apply(RenderAny.java:96)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:346)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:243)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1456)
	at act.route.Router$ContextualHandler.handle(Router.java:1818)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/216930/85941095-16e20200-b964-11ea-810d-49e756b4c80a.png)
