### ISSUE TITLE
excute "/~/test" fail

### ISSUE THREAD

**Issue by CrossLee** [actframework/actframework#1356]
my app has WebSocket implementation, while I run "http://localhost:5460/~/test" with chrome.
why the test request goes into my websocket controller?
websocket throws exception and the test can't continue.

error stack:
```
Connected to the target VM, address: '127.0.0.1:51454', transport: 'socket'
   _____              _        ______ 
  / ____|     /\     | |      |  ____|
 | (___      /  \    | |      | |__   
  \___ \    / /\ \   | |      |  __|  
  ____) |  / ____ \  | |____  | |____ 
 |_____/  /_/    \_\ |______| |______|
                                      
                                      

           $$$$$$@$$@$$$$$$
           $$$$@+W++W+@$$$$
           $$%++@%==%@++%$$
           $$%+@=%$$%=@+%$$
           $@+W+%@%%@%+W+@$
           $$$@$++@@++$@$$$
           $$$$$%+%%+%$$$$$
           $$$$$$$$$$$$$$$$

 powered by ActFramework r1.9.0a-abce

 version: v1.0-SNAPSHOT
scan pkg: com.hyc.sale
base dir: /Users/cross/Workspaceij/sale/sale/sale
     pid: 2462
 profile: devc
    mode: DEV
      OS: UNKNOWN
     jdk: Java HotSpot(TM) 64-Bit Server VM 1.8

     zen: Namespaces are one honking great idea -- let's do more of those!

2020-08-14 18:02:13,390 INFO  a.Act@[main] - loading application(s) ...
2020-08-14 18:02:13,411 INFO  a.a.App@[main] - App starting ....
2020-08-14 18:02:13,428 INFO  o.xnio@[Thread-0] - XNIO version 3.4.6.Final
2020-08-14 18:02:13,474 INFO  o.x.nio@[Thread-0] - XNIO NIO Implementation Version 3.4.6.Final
2020-08-14 18:02:14,502 WARN  a.h.b.ResourceGetter@[main] - URL base not exists: /asset/img/favicon.png
2020-08-14 18:02:14,576 INFO  a.a.DbServiceManager@[main] - db service[default] initialized
八月 14, 2020 6:02:14 下午 act.db.sql.util.EbeanAgentLoader loadAgent
信息: dynamically loading javaagent for /Users/cross/.m2/repository/org/avaje/ebean/ebean-agent/8.1.1/ebean-agent-8.1.1.jar
premain loading Transformer with args:debug=1;packages=com.hyc.sale
2020-08-14 18:02:19,673 INFO  a.m.MailerConfig@[jobs-thread-3] - smtp host configuration not found, will use mock smtp to send email
2020-08-14 18:02:19,688 INFO  c.z.h.HikariDataSource@[jobs-thread-1] - HikariPool-1 - Starting...
2020-08-14 18:02:20,059 INFO  c.z.h.HikariDataSource@[jobs-thread-1] - HikariPool-1 - Start completed.
2020-08-14 18:02:20,069 INFO  a.Act@[main] - network client hooked on port: 5460
2020-08-14 18:02:20,070 INFO  a.Act@[main] - network client hooked on port: 5462
2020-08-14 18:02:20,074 INFO  a.Act@[main] - network client hooked on port: 5463
2020-08-14 18:02:20,078 INFO  a.Act@[main] - CLI server started on port: 5461
2020-08-14 18:02:20,083 INFO  a.Act@[main] - app is ready in 10749ms at: http://192.168.3.63:5460

2020-08-14 18:02:23,995 INFO  a.a.ApiManager@[jobs-thread-3] - API book compiled
Start running test scenarios
---------------------------------------------------------------
2020-08-14 18:03:01,716 ERROR i.u.r.io@[XNIO-1 task-3] - UT005090: Unexpected failure
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at act.ws.WebSocketConnectionRegistry.ensureConnectionList(WebSocketConnectionRegistry.java:305)
	at act.ws.WebSocketConnectionRegistry.signIn(WebSocketConnectionRegistry.java:132)
	at act.ws.WebSocketConnectionRegistry.register(WebSocketConnectionRegistry.java:117)
	at act.ws.WebSocketConnectionManager$3.visit(WebSocketConnectionManager.java:108)
	at act.ws.WebSocketConnectionManager$3.visit(WebSocketConnectionManager.java:105)
	at org.osgl.Lang$Visitor.apply(Lang.java:2463)
	at org.osgl.Lang$Visitor.apply(Lang.java:2453)
	at act.ws.WebSocketConnectionRegistry.accept(WebSocketConnectionRegistry.java:91)
	at act.ws.WebSocketConnectionManager.subscribe(WebSocketConnectionManager.java:105)
	at com.hyc.sale.controller.socket.WSController.onConnect(WSController.java:42)
	at act.ws.WebSocketConnectionListener$Manager.notifyFreeListeners(WebSocketConnectionListener.java:102)
	at act.xio.WebSocketConnectionHandler._onConnect(WebSocketConnectionHandler.java:189)
	at act.xio.undertow.UndertowWebSocketConnectionHandler.access$1100(UndertowWebSocketConnectionHandler.java:37)
	at act.xio.undertow.UndertowWebSocketConnectionHandler$1.onConnect(UndertowWebSocketConnectionHandler.java:85)
	at io.undertow.websockets.WebSocketProtocolHandshakeHandler$1.handleUpgrade(WebSocketProtocolHandshakeHandler.java:198)
	at io.undertow.server.protocol.http.HttpReadListener.exchangeComplete(HttpReadListener.java:389)
	at io.undertow.server.protocol.http.HttpServerConnection.exchangeComplete(HttpServerConnection.java:244)
	at io.undertow.server.HttpServerExchange.invokeExchangeCompleteListeners(HttpServerExchange.java:1279)
	at io.undertow.server.HttpServerExchange.terminateResponse(HttpServerExchange.java:1563)
	at io.undertow.server.Connectors.terminateResponse(Connectors.java:159)
	at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:199)
	at io.undertow.server.protocol.http.HttpTransferEncoding$3.handleEvent(HttpTransferEncoding.java:197)
	at io.undertow.conduits.HeadStreamSinkConduit.exitFlush(HeadStreamSinkConduit.java:192)
	at io.undertow.conduits.HeadStreamSinkConduit.flush(HeadStreamSinkConduit.java:133)
	at org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162)
	at io.undertow.channels.DetachableStreamSinkChannel.flush(DetachableStreamSinkChannel.java:119)
	at io.undertow.server.HttpServerExchange.closeAndFlushResponse(HttpServerExchange.java:1723)
	at io.undertow.server.HttpServerExchange.endExchange(HttpServerExchange.java:1700)
	at io.undertow.websockets.spi.AsyncWebSocketHttpServerExchange.endExchange(AsyncWebSocketHttpServerExchange.java:213)
	at io.undertow.websockets.core.protocol.Handshake.upgradeChannel(Handshake.java:131)
	at io.undertow.websockets.core.protocol.Handshake.performUpgrade(Handshake.java:124)
	at io.undertow.websockets.core.protocol.Handshake.performUpgrade(Handshake.java:152)
	at io.undertow.websockets.core.protocol.version13.Hybi13Handshake.handshakeInternal(Hybi13Handshake.java:66)
	at io.undertow.websockets.core.protocol.Handshake.handshake(Handshake.java:102)
	at io.undertow.websockets.WebSocketProtocolHandshakeHandler.handleRequest(WebSocketProtocolHandshakeHandler.java:204)
	at act.xio.undertow.UndertowWebSocketConnectionHandler.handle(UndertowWebSocketConnectionHandler.java:88)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1456)
	at act.route.Router$ContextualHandler.handle(Router.java:1817)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
running [_default_]Hello World
 
```

test stop here
![image](https://user-images.githubusercontent.com/4584905/90238533-b5fd8300-de58-11ea-88bc-74bb27e69f22.png)

**Comment by CrossLee** [comment]
code :

```
@UrlContext("ws")
public class WSController implements WebSocketConnectionListener {

    private static Logger logger = L.get(WSController.class);
    private static final AtomicInteger CONN_COUNTER = new AtomicInteger(0);

    @Inject
    private WebSocketConnectionManager connectionManager;

    @WsAction("msg/{sid}")
    public void onMessage(String sid, WebSocketContext context) {
//        String sid = context.actionContext().paramVal("sid");
        String ip = context.actionContext().req().ip();
        logger.debug("[WS][Message][sid=%s][session=%s][count=%s][ip=%s]", sid, context.session().id(), CONN_COUNTER.get(), ip);
        context.sendToSelf(sid);
    }

    @Override
    public void onConnect(WebSocketContext context) {
        int count = CONN_COUNTER.incrementAndGet();
        String sid = context.actionContext().paramVal("sid");

        // 通过sid注册一个连接
        connectionManager.subscribe(context.session(), sid);
        String ip = context.actionContext().req().ip();
        logger.info("[WS][Connect][count=%s][sid=%s][session=%s][ip=%s]", count, sid, context.session().id(), ip);

        WebSocketConnectionRegistry tag = context.manager().tagRegistry();
        WebSocketConnectionRegistry session = context.manager().sessionRegistry();
        WebSocketConnectionRegistry url = context.manager().urlRegistry();
        WebSocketConnectionRegistry username = context.manager().usernameRegistry();
        logger.debug("[WS][Connect][tagRegistry=%s][sessionRegistry=%s][urlRegistry=%s][usernameRegistry=%s]", tag.count(), session.count(), url.count(), username.count());
    }

    @Override
    public void onClose(WebSocketContext context) {
        int count = CONN_COUNTER.decrementAndGet();
        String sid = context.actionContext().paramVal("sid");
        String ip = context.actionContext().req().ip();
        logger.info("[WS][Close][count=%s][sid=%s][session=%s][ip=%s]", count, sid, context.session().id(), ip);
    }
}
```

**Comment by greenlaw110** [comment]
@CrossLee 
In your testing context, the `sid` is `null`:
![image](https://user-images.githubusercontent.com/216930/90322941-1813d080-df9e-11ea-86e9-d8d6e32e8891.png)

which result in the `key` to access a map is `null`:
![image](https://user-images.githubusercontent.com/216930/90322947-2eba2780-df9e-11ea-8a1f-79b164535a62.png)

And then it leads to a `NullPointerException`

Try to add the following statement into your `onConnect` method:
![image](https://user-images.githubusercontent.com/216930/90322969-53ae9a80-df9e-11ea-8ba9-9dff748f8b7a.png)

**Comment by CrossLee** [comment]
the test scenarios.yml:

```
Scenario(Hello World):
  description: a web page says Hello
  interactions:
    - description: send request to the app without parameter
      request:
        headers:
          Accept: text/html
        method: GET
        url: /
      response:
        html:
          h1: Hello World
          head title:
            - contains: Hello World
            - contains: ActFramework
          p:
            <any>:
              - contains: Powered by ActFramework
    - description: send request to the app with [who = ActFramework]
      request:
        headers:
          Accept: text/html
        method: GET
        url: /?who=ActFramework
      response:
        html:
          h1: Hello ActFramework
```

expect:
the test cases have nothing to do with WebSocket, act should not hang up the test process.

workaround:
add @WsEndpoint)("ws") to the WSController

**Comment by greenlaw110** [comment]
The issue is superseded by #1357 1357
