### ISSUE TITLE
Error encountered requesting `/asset/extjs-all.js`

### ISSUE THREAD

**Issue by eddnb** [actframework/actframework#1359]
Error stack

```
Error handling network request
java.lang.IllegalArgumentException: config key cannot be empty
	at org.osgl.util.E.illegalArgumentIf(E.java:696)
	at act.conf.AppConfigKey.valueOfIgnoreCase(AppConfigKey.java:1516)
	at act.conf.AppConfig.keyOf(AppConfig.java:282)
	at act.conf.Config.get(Config.java:174)
	at act.conf.Config.getIgnoreCase(Config.java:184)
	at act.util.$$$1.transform($$.java:81)
	at act.util.$$$1.transform($$.java:78)
	at org.osgl.Lang$Transformer.apply(Lang.java:2831)
	at act.util.StringUtils.processStringSubstitution(StringUtils.java:66)
	at act.util.StringUtils.processStringSubstitution(StringUtils.java:47)
	at act.util.$$.processStringSubstitution($$.java:69)
	at act.handler.builtin.ResourceGetter.handle(ResourceGetter.java:276)
	at act.handler.builtin.ResourceGetter.handle(ResourceGetter.java:135)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:196)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
	at  #java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
I suspect this issue is relevant with https://github.com/actframework/actframework/issues/1151.
