### ISSUE TITLE
Inject ActionContext to @WsAction method cause NPE

### ISSUE THREAD

**Issue by CrossLee** [actframework/actframework#1364]
code to reproduce:

Controller:

```
package com.hyc.sale.controller.socket;

import act.app.ActionContext;
import act.controller.annotation.UrlContext;
import act.ws.*;
import org.osgl.logging.L;
import org.osgl.logging.Logger;
import org.osgl.mvc.annotation.WsAction;

import javax.inject.Inject;
import java.util.concurrent.atomic.AtomicInteger;

@UrlContext("ws")
@WsEndpoint("ws")
public class WSController implements WebSocketConnectionListener {

    private static Logger logger = L.get(WSController.class);
    private static final AtomicInteger CONN_COUNTER = new AtomicInteger(0);

    @Inject
    private WebSocketConnectionManager connectionManager;

    @WsAction("msg/{sid}")
    public void onMessage(String sid, ActionContext context) {
        String ip = context.req().ip();
        logger.debug("[WS][Message][sid=%s][session=%s][count=%s][ip=%s]", sid, context.session().id(), CONN_COUNTER.get(), ip);
    }

    @Override
    public void onConnect(WebSocketContext context) {
        int count = CONN_COUNTER.incrementAndGet();
        String sid = context.actionContext().paramVal("sid");

        // 通过sid注册一个连接
        connectionManager.subscribe(context.session(), sid);
        String ip = context.actionContext().req().ip();
        logger.info("[WS][Connect][count=%s][sid=%s][session=%s][ip=%s]", count, sid, context.session().id(), ip);

        WebSocketConnectionRegistry tag = context.manager().tagRegistry();
        WebSocketConnectionRegistry session = context.manager().sessionRegistry();
        WebSocketConnectionRegistry url = context.manager().urlRegistry();
        WebSocketConnectionRegistry username = context.manager().usernameRegistry();
        logger.debug("[WS][Connect][tagRegistry=%s][sessionRegistry=%s][urlRegistry=%s][usernameRegistry=%s]", tag.count(), session.count(), url.count(), username.count());
    }

    @Override
    public void onClose(WebSocketContext context) {
       
    }
}
```

HTML Code:

```
<script>
    var ws = new WebSocket("ws://localhost:5460/ws/msg?sid=1");

    ws.onopen = function(evt) {
        console.log("Connection open ...");
        ws.send("Hello WebSockets!");
    };

    ws.onmessage = function(evt) {
        console.log("Received Message: " + evt.data);
        ws.close();
    };

    ws.onclose = function(evt) {
        console.log("Connection closed.");
    };
</script>
```

call : http://localhost:5460/test/fileTest in Chrome and refresh the page several times, NPE occurred:

```
2020-09-19 23:31:22,861 DEBUG c.h.s.c.s.WSController@[XNIO-1 I/O-2] - [WS][Message][sid=Hello WebSockets!][session=595490da-1385-44b7-ac9c-0344b0b28918][count=0][ip=0:0:0:0:0:0:0:1]
2020-09-19 23:31:25,129 DEBUG c.h.s.c.s.WSController@[XNIO-1 I/O-1] - [WS][Message][sid=Hello WebSockets!][session=0fea51e4-b2d0-4a65-85e9-0e3e0e50a8b8][count=0][ip=0:0:0:0:0:0:0:1]
2020-09-19 23:31:26,560 DEBUG c.h.s.c.s.WSController@[XNIO-1 I/O-1] - [WS][Message][sid=Hello WebSockets!][session=54568552-a348-451b-bf3b-c25084d1c10f][count=0][ip=0:0:0:0:0:0:0:1]
2020-09-19 23:31:27,932 ERROR o.x.listener@[XNIO-1 I/O-2] - XNIO001007: A channel event listener threw an exception
java.lang.NullPointerException: null
	at com.hyc.sale.controller.socket.WSController.onMessage(WSController.java:31)
	at com.hyc.sale.controller.socket.WSControllerMethodAccess.invoke(Unknown Source)
	at act.xio.WebSocketConnectionHandler.invoke(WebSocketConnectionHandler.java:230)
	at act.xio.undertow.UndertowWebSocketConnectionHandler.access$700(UndertowWebSocketConnectionHandler.java:37)
	at act.xio.undertow.UndertowWebSocketConnectionHandler$1$1.onFullTextMessage(UndertowWebSocketConnectionHandler.java:70)
	at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:156)
	at io.undertow.websockets.core.AbstractReceiveListener$2.complete(AbstractReceiveListener.java:152)
	at io.undertow.websockets.core.BufferedTextMessage.read(BufferedTextMessage.java:105)
	at io.undertow.websockets.core.AbstractReceiveListener.readBufferedText(AbstractReceiveListener.java:152)
	at io.undertow.websockets.core.AbstractReceiveListener.bufferFullMessage(AbstractReceiveListener.java:90)
	at io.undertow.websockets.core.AbstractReceiveListener.onText(AbstractReceiveListener.java:70)
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:44)
	at io.undertow.websockets.core.AbstractReceiveListener.handleEvent(AbstractReceiveListener.java:33)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:952)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:932)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:571)

```

**Comment by greenlaw110** [comment]
@CrossLee `@WsAction` mark a websocket connection event handler which happens on a long connection, while `ActionContext` (maybe I should name it HttpContext) denote a normal HTTP request/response event. In other words you cannot inject `ActionContext` to a `@WsAction` annotated method. 

If you need the `ip` of remote connection, you can get it from the initial `onConnect` method:

```java
public void onConnect(WebSocketContext context) {
    String ip = context.actionContext().ip();
    ...
}
```

The ip will never change as long as the connection is still established.
