### ISSUE TITLE
1.9.0.1版本添加googleauth依赖，打包编译时报错

### ISSUE THREAD

**Issue by pcmanjack** [actframework/actframework#1365]
1.9.0.1版本添加googleauth
```
<!-- https://mvnrepository.com/artifact/com.warrenstrange/googleauth -->
        <dependency>
            <groupId>com.warrenstrange</groupId>
            <artifactId>googleauth</artifactId>
            <version>1.5.0</version>
        </dependency>
```
执行 mvn clean package
最后控制台最后会报
```
org.osgl.exception.UnexpectedException: Concurrent modification issue encountered on handling event: SINGLETON_PROVISIONED
        at org.osgl.util.E.unexpected(E.java:180)
        at act.event.EventBus.callOn(EventBus.java:1482)
        at act.event.EventBus.callOn(EventBus.java:1492)
        at act.event.EventBus._emit(EventBus.java:1353)
        at act.event.EventBus.emit(EventBus.java:807)
        at act.app.App.emit(App.java:1317)
        at act.app.App$4.run(App.java:826)
        at act.job.JobManager$ContextualJob$1.apply(JobManager.java:543)
        at act.job.Job.doJob(Job.java:413)
        at act.job.Job.run(Job.java:337)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
错误，但是可以打包成功也能正常部署。但是不知道有没有未知的影响

**Comment by greenlaw110** [comment]
Cannot reproduce this issue
