### ISSUE TITLE
Application start with exception when run from export jar file

### ISSUE THREAD

**Issue by zzeric** [actframework/actframework#1367]
```
java.lang.NullPointerException
        at act.metric.MetricMetaInfoRepo.mergeFromParents(MetricMetaInfoRepo.java:64)
        at act.metric.MetricMetaInfoRepo.access$000(MetricMetaInfoRepo.java:32)
        at act.metric.MetricMetaInfoRepo$1.run(MetricMetaInfoRepo.java:44)
        at act.job.Job$4.apply(Job.java:455)
        at act.job.Job.doJob(Job.java:413)
        at act.job.Job.run(Job.java:337)
        at act.job.Job$LockableJobList.runSubJobs(Job.java:113)
        at act.job.Job$LockableJobList.runSubJobs(Job.java:94)
        at act.job.Job.runPrecedenceJobs(Job.java:432)
        at act.job.Job.run(Job.java:329)
        at act.job.JobManager$_SysEventListener.on(JobManager.java:491)
        at act.event.EventBus.callOn(EventBus.java:1440)
        at act.event.EventBus.callOn(EventBus.java:1462)
        at act.event.EventBus.callOn(EventBus.java:1492)
        at act.event.EventBus._emit(EventBus.java:1353)
        at act.event.EventBus.emit(EventBus.java:807)
        at act.app.App.emit(App.java:1317)
        at act.app.App.refresh(App.java:786)
        at act.app.AppManager.load(AppManager.java:77)
        at act.app.AppManager$_F$1.visit(AppManager.java:145)
        at act.app.AppManager$_F$1.visit(AppManager.java:141)
        at org.osgl.Lang$Visitor.apply(Lang.java:2463)
        at org.osgl.Lang$Visitor.apply(Lang.java:2453)
        at act.app.AppScanner.scan(AppScanner.java:91)
        at act.app.AppScanner.scan(AppScanner.java:71)
        at act.app.AppManager.loadSingleApp(AppManager.java:55)
        at act.Act.startup(Act.java:338)
        at act.Act.startup(Act.java:1294)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.osgl.Lang.invokeStatic(Lang.java:8153)
        at act.Act.bootstrap(Act.java:1200)
        at act.Act.start(Act.java:682)
        at demo.AppEntry.main(AppEntry.java:8)
```

**Comment by greenlaw110** [comment]
@zzeric How did you export the jar file and run it?

The practice of building an ActFramework app is via maven command:

```bash
# build the package
mvn package
# the package should be located in ${PRJ_HOME}/target/dist
cd target/dist
# unpack the package
tar xzf *.tar.gz
# run the app
./run
```

**Comment by greenlaw110** [comment]
Close as no response from issue reporter
