### ISSUE TITLE
ApacheMultipartParser NullPointerException

### ISSUE THREAD

**Issue by jazzeWang** [actframework/actframework#1369]
```
java.lang.NullPointerException: null
	at act.data.ApacheMultipartParser.parse(ApacheMultipartParser.java:69)
	at act.app.ActionContext.bodyParams(ActionContext.java:899)
	at act.app.ActionContext.getBody(ActionContext.java:888)
	at act.app.ActionContext._paramVal(ActionContext.java:855)
	at act.app.ActionContext.paramVal(ActionContext.java:844)
	at act.inject.param.StringValueResolverValueLoader.load(StringValueResolverValueLoader.java:121)
	at act.inject.param.StringValueResolverValueLoader.load(StringValueResolverValueLoader.java:105)
	at act.inject.param.FieldLoader.applyTo(FieldLoader.java:66)
	at act.inject.param.PojoLoader.load(PojoLoader.java:79)
	at act.inject.param.JsonParamValueLoader.load(JsonParamValueLoader.java:79)
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:73)
	at act.inject.param.ParamValueLoaderService.loadMethodParams(ParamValueLoaderService.java:205)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.params(ReflectedHandlerInvoker.java:1259)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:616)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:584)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:213)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1456)
	at act.route.Router$ContextualHandler.handle(Router.java:1815)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

当使用form表单提交时， form设置了enctype="multipart/form-data"。 
如果form中有的内容是空， 比如一个input type="text" 没有输入任何东西， 
提交form表单，则会报NullPointerException错误。 

初步判断是
![image](https://user-images.githubusercontent.com/4670709/96700998-aa7f8880-13c2-11eb-9280-b0d574edc382.png)

**Comment by greenlaw110** [comment]
@jazzeWang what is your actframework version?

I tried on version 1.9.0a, and couldn't reproduce the issue. Here is my testing code

Controller.java

```java
public class Gh1369 extends BaseController {

    @GetAction("1369")
    public void form() {
        Controller.Util.renderTemplate("/1369.html");
    }

    @PostAction("1369")
    public String test(SObject file) {
        return null == file ? "null object" : file.asString();
    }

}
```

The form template:

```html
<html>
<head>
    <title>GH 1369 Test Form</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    <input type="file" name="file">
    <div>
        <button type="submit">Submit</button>
    </div>
</form>
</body>
</html>
```

Submit the form without selecting a file. There is no NPE and the controll code returns expected result:

![1](https://user-images.githubusercontent.com/216930/96857326-96af5180-14aa-11eb-814b-9b0fa11047a5.gif)

**Comment by greenlaw110** [comment]
Hi @jazzeWang 

I can reproduce the issue with a slightly changed code.

Controller.java

```java
public class Gh1369 extends BaseController {

    @GetAction("1369")
    public void form() {
        Controller.Util.renderTemplate("/1369.html");
    }

    @PostAction("1369")
    public String test(SObject file, String name) {
        return name + ": " + (null == file ? "null object" : file.asString());
    }

}
```

HTML form template

```html
<html>
<head>
    <title>GH 1369 Test Form</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    <div>
        <label>Name</label>
        <input type="text" name="name">
    </div>
    <div>
        <label>File</label>
        <input type="file" name="file">
    </div>
    <div>
        <button type="submit">Submit</button>
    </div>
</form>
</body>
</html>
```

Submit the form without filling the text input and the file input, it will raise the NPE and cause 500 error:

![image](https://user-images.githubusercontent.com/216930/96860498-8a2cf800-14ae-11eb-8af9-0f535dfa941c.png)

**Comment by greenlaw110** [comment]
hi @jazzeWang 

Can you try act-1.9.1-SNAPSHOT?

**Comment by jazzeWang** [comment]
the issue version is 1.9.0.1. I will change the pom.xml to version act-1.9.1-SNAPSHOT to try.  I will give you a feedback later. 
Thx.

**Comment by jazzeWang** [comment]
I checked the version we used before. it was act-1.9.1-SNAPSHOT. I re-compile the pom.xml. 
I found the source code was changed.   And It's working.  The issue is fixed.   
Thx.

**Comment by CrossLee** [comment]
@greenlaw110 The error reappeared in 1.9.1-SNAPSHOT ，could you please have a check?

**Comment by greenlaw110** [comment]
@CrossLee try refresh again
