### ISSUE TITLE
Web Site based on Act down!

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1393]
Error stack:

```
2021-05-08_16:38:47.668 [XNIO-1 I/O-6] ERROR act.app.App - Block issue encountered
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.initOutputVariables(ReflectedHandlerInvoker.java:1044)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:417)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createControllerAction(ReflectedHandlerInvoker.java:1289)
	at act.Act$Mode.createRequestHandler(Act.java:164)
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:450)
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:371)
	at act.handler.builtin.controller.RequestHandlerProxy.corsSpec(RequestHandlerProxy.java:567)
	at act.handler.DelegateRequestHandler.corsSpec(DelegateRequestHandler.java:71)
	at act.handler.OptionsInfoBase.createHandler(OptionsInfoBase.java:77)
	at act.handler.OptionsInfoBase.optionHandler(OptionsInfoBase.java:53)
	at act.route.Router.getInvoker(Router.java:250)
	at act.xio.NetworkHandler.handle(NetworkHandler.java:164)
	at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:58)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
2021-05-08_16:38:47.671 [Thread-9] INFO  act.app.App - Shutting down app [ZFW-Serve]....
2021-05-08_16:38:47.680 [Thread-9] DEBUG act.db.ebean.EbeanService - ebean shutdown: mysql
2021-05-08_16:38:47.680 [Thread-9] DEBUG act.db.ebean.EbeanService - ebean readonly shutdown: mysql
2021-05-08_16:38:47.695 [Thread-9] INFO  act.Act - All components shutdown, bye!
```

[log file](https://github.com/actframework/actframework/files/6449003/act.2021.05.10.log)

**Comment by greenlaw110** [comment]
@jiankian can you please provide Act version?

**Comment by jiankian** [comment]
The Server OS is CentOS 7，JDK： OpenJDk 1.8
Hardware： 4C8G

JVM Params：
        JAVA_OPTS="$JAVA_OPTS -Xms888M"
        JAVA_OPTS="$JAVA_OPTS -Xmx4G"

**Comment by greenlaw110** [comment]
@jiankian can you please try act-1.9.2-SNAPSHOT ?

```xml
    <dependency>
      <groupId>org.actframework</groupId>
      <artifactId>act</artifactId>
      <version>1.9.2-SNAPSHOT</version>
    </dependency>
```

**Comment by greenlaw110** [comment]
Hi @jiankian, how is it going? have you tried the new version?

**Comment by jiankian** [comment]
> Or if you don't want to update act version, try update your `osgl-tool` version:
> 
> ```
>     <dependency>
>       <groupId>org.osgl</groupId>
>       <artifactId>osgl-tool</artifactId>
>       <version>1.26.3-SNAPSHOT</version>
>     </dependency>
> ```

There is no problem at the moment
