### ISSUE TITLE
UnexpectedMethodInvocationException on app start 

### ISSUE THREAD

**Issue by CrossLee** [actframework/actframework#1404]
log:
```
powered by ActFramework v1.9.2-SNAPSHOT-267d8

 version: r1.2.1
scan pkg: com.qdstorm
base dir: /Users/cross/IdeaProjects/qdstorm/qdpay/qdpay
     pid: 10154
 profile: devc
    mode: DEV
      OS: macOS
     jdk: OpenJDK 64-Bit Server VM 1.8

     zen: Simple things should be simple, complex things should be possible. 

                                                            -  Zen of Python

Exception in thread "main" org.osgl.exception.UnexpectedMethodInvocationException: java.lang.IncompatibleClassChangeError: org.bouncycastle.jcajce.provider.digest.SM3 and org.bouncycastle.jcajce.provider.digest.SM3$KeyGenerator disagree on InnerClasses attribute
	at org.osgl.exception.UnexpectedMethodInvocationException.triage(UnexpectedMethodInvocationException.java:44)
	at org.osgl.Lang.invokeStatic(Lang.java:8152)
	at act.Act.bootstrap(Act.java:1221)
	at act.Act.start(Act.java:703)
	at com.qdstorm.AppEntry.main(AppEntry.java:51)
Caused by: java.lang.IncompatibleClassChangeError: org.bouncycastle.jcajce.provider.digest.SM3 and org.bouncycastle.jcajce.provider.digest.SM3$KeyGenerator disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at java.lang.Class.getEnclosingClass(Class.java:1277)
	at java.lang.Class.getCanonicalName(Class.java:1392)
	at act.util.ClassInfoRepository.canonicalName(ClassInfoRepository.java:157)
	at act.boot.app.FullStackAppBootstrapClassLoader.cache(FullStackAppBootstrapClassLoader.java:334)
	at act.boot.app.FullStackAppBootstrapClassLoader.pluginClasses(FullStackAppBootstrapClassLoader.java:114)
	at act.Act.pluginClasses(Act.java:266)
	at act.plugin.PluginScanner.scan(PluginScanner.java:45)
	at act.Act.loadPlugins(Act.java:1036)
	at act.Act.startup(Act.java:332)
	at act.Act.startup(Act.java:1322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Lang.invokeStatic(Lang.java:8150)
	... 3 more
Disconnected from the target VM, address: '127.0.0.1:57317', transport: 'socket'

Process finished with exit code 1

```

breakpoint:
![image](https://user-images.githubusercontent.com/4584905/130974176-278d0c98-77ba-40ff-afd7-f64e738a7d33.png)

**Comment by CrossLee** [comment]
@greenlaw110 有空看一下

**Comment by greenlaw110** [comment]
Act 本身不依赖 bouncycastle, 应该是你的项目对 bouncycastle 的依赖有冲突吧，你对你的项目运行一下 `mvn dependency:tree` 看看是如何依赖到两个不同 bouncycastle 版本的

**Comment by CrossLee** [comment]
> Act 本身不依赖 bouncycastle, 应该是你的项目对 bouncycastle 的依赖有冲突吧，你对你的项目运行一下 `mvn dependency:tree` 看看是如何依赖到两个不同 bouncycastle 版本的

ok, 确实冲突了。这太尴尬了，两个不同dependency的jar引用了不同的版本。

**Comment by CrossLee** [comment]
issue 你关了吧。
