### ISSUE TITLE
添加依赖hibernate-types-52异常

### ISSUE THREAD

**Issue by kukume** [actframework/actframework#1410]
添加如下依赖
```xml
<dependency>
            <groupId>com.vladmihalcea</groupId>
            <artifactId>hibernate-types-52</artifactId>
            <version>2.13.0</version>
        </dependency>
```
启动的时候如下异常
```
Exception in thread "main" org.osgl.exception.UnexpectedMethodInvocationException: java.lang.IncompatibleClassChangeError: javax.activation.CommandInfo and javax.activation.CommandInfo$Beans disagree on InnerClasses attribute
	at org.osgl.exception.UnexpectedMethodInvocationException.triage(UnexpectedMethodInvocationException.java:44)
	at org.osgl.Lang.invokeStatic(Lang.java:8152)
	at act.Act.bootstrap(Act.java:1221)
	at act.Act.start(Act.java:703)
	at me.kuku.sign.AppEntry.main(AppEntry.java:50)
Caused by: java.lang.IncompatibleClassChangeError: javax.activation.CommandInfo and javax.activation.CommandInfo$Beans disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at java.lang.Class.getEnclosingClass(Class.java:1277)
	at java.lang.Class.getCanonicalName(Class.java:1392)
	at act.util.ClassInfoRepository.canonicalName(ClassInfoRepository.java:157)
	at act.boot.app.FullStackAppBootstrapClassLoader.cache(FullStackAppBootstrapClassLoader.java:334)
	at act.boot.app.FullStackAppBootstrapClassLoader.pluginClasses(FullStackAppBootstrapClassLoader.java:114)
	at act.Act.pluginClasses(Act.java:266)
	at act.plugin.PluginScanner.scan(PluginScanner.java:45)
	at act.Act.loadPlugins(Act.java:1036)
	at act.Act.startup(Act.java:332)
	at act.Act.startup(Act.java:1322)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Lang.invokeStatic(Lang.java:8150)
	... 3 more
```

**Comment by greenlaw110** [comment]
This is caused by incompatible dependency jar files. Try to issue

```
mvn dependency:tree | grep activation
```

And check how many activation jar files exists in your dependency and follow https://www.baeldung.com/maven-version-collision to resolve the condliction
