### ISSUE TITLE
java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#149]
Running `https://git.oschina.net/greenlaw110/simple-bbs` triggered a `java.lang.VerificationError`

**Note** 

1. This error only happened on `dev` mode. Running app on prod mode doesn't have the issue
2. This error can be reproduced on both act-1.1.x and act-1.0.x version

Error stack:

```
Exception in thread "XNIO-1 task-7" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    simple_bbs/endpoint/BBSController.listMessages(I)V @49: invokevirtual
  Reason:
    Type 'act/app/ActionContext' (current frame, stack[0]) is not assignable to 'java/lang/String'
  Current Frame:
    bci: @49
    flags: { }
    locals: { 'simple_bbs/endpoint/BBSController', integer, 'java/lang/Iterable', double, double_2nd }
    stack: { 'act/app/ActionContext', 'java/lang/String' }
  Bytecode:
    0x0000000: 2ab4 002e 1bb6 0032 4d2a b400 2eb6 0036
    0x0000010: 8a14 0037 6f0f 674a b800 3e12 4029 b800
    0x0000020: 46b6 004a 124c 2cb6 004a 1240 29b8 0052
    0x0000030: 4ab6 004a 1254 b600 5857 29b8 0052 4a05
    0x0000040: bd00 5a59 032c 5359 0429 b800 4653 b800
    0x0000050: 5ebf                                   

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.osgl.Osgl.classForName(Osgl.java:5216)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:105)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createControllerAction(ReflectedHandlerInvoker.java:490)
	at act.Act$Mode.createRequestHandler(Act.java:130)
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:346)
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:287)
	at act.handler.builtin.controller.RequestHandlerProxy.sessionFree(RequestHandlerProxy.java:227)
	at act.handler.DelegateRequestHandler.sessionFree(DelegateRequestHandler.java:76)
	at act.app.ActionContext.resolve(ActionContext.java:674)
	at act.route.Router$ContextualHandler.handle(Router.java:1244)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by CrossLee** [comment]
开发有workaround吗？？
