### ISSUE TITLE
Deadlock while app boot up

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#150]
Randomly it might encounter deadlock during app boot up:

```
Found one Java-level deadlock:
=============================
"jobs-thread-1":
  waiting to lock monitor 0x00007fc33c6060e8 (object 0x00000006c7b40c50, a act.app.DevModeClassLoader),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007fc2f4006218 (object 0x00000006c8035b10, a act.app.SingletonRegistry),
  which is held by "jobs-thread-1"

Java stack information for the threads listed above:
===================================================
"jobs-thread-1":
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at org.osgl.inject.Genie.fieldInjectors(Genie.java:762)
	at org.osgl.inject.Genie.buildFieldMethodInjector(Genie.java:706)
	at org.osgl.inject.Genie.buildProvider(Genie.java:686)
	at org.osgl.inject.Genie.findProvider(Genie.java:644)
	at org.osgl.inject.Genie.getProvider(Genie.java:337)
	at org.osgl.inject.Genie.get(Genie.java:315)
	at act.inject.genie.GenieInjector.get(GenieInjector.java:77)
	at act.app.App.getInstance(App.java:755)
	at act.app.SingletonRegistry.doRegister(SingletonRegistry.java:77)
	- locked <0x00000006c8035b10> (a act.app.SingletonRegistry)
	at act.app.SingletonRegistry.access$000(SingletonRegistry.java:34)
	at act.app.SingletonRegistry$1.run(SingletonRegistry.java:50)
	at act.job._Job$2.apply(_Job.java:291)
	at act.job._Job.doJob(_Job.java:253)
	at act.job._Job.run(_Job.java:193)
	at act.job.AppJobManager$ContextualJob$1.apply(AppJobManager.java:352)
	at act.job._Job.doJob(_Job.java:253)
	at act.job._Job.run(_Job.java:193)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"main":
	at act.app.SingletonRegistry.get(SingletonRegistry.java:65)
	- waiting to lock <0x00000006c8035b10> (a act.app.SingletonRegistry)
	at act.app.App.singleton(App.java:733)
	at act.storage.EntityClassEnhancer.ssm(EntityClassEnhancer.java:133)
	- locked <0x00000007702f28e0> (a act.storage.EntityClassEnhancer)
	at act.storage.EntityClassEnhancer.visit(EntityClassEnhancer.java:45)
	at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at act.cli.bytecode.CommanderEnhancer.visit(CommanderEnhancer.java:60)
	at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at act.util.SimpleBean$ByteCodeEnhancer.visit(SimpleBean.java:242)
	at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at act.mail.bytecode.MailerEnhancer.visit(MailerEnhancer.java:70)
	at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at act.controller.bytecode.ControllerEnhancer.visit(ControllerEnhancer.java:63)
	at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at act.util.SingletonEnhancer.visit(SingletonEnhancer.java:54)
	at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at act.util.DataObjectEnhancer.visit(DataObjectEnhancer.java:58)
	at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at act.db.EntityClassEnhancer.visit(EntityClassEnhancer.java:56)
	at act.asm.ClassVisitor.visit(ClassVisitor.java:113)
	at act.db.ebean2.ModelBaseEnhancer.visit(ModelBaseEnhancer.java:28)
	at act.asm.ClassReader.accept(ClassReader.java:622)
	at act.app.AppClassLoader.asmEnhance(AppClassLoader.java:477)
	at act.app.AppClassLoader.enhance(AppClassLoader.java:464)
	at act.app.AppClassLoader.loadAppClass(AppClassLoader.java:441)
	at act.app.AppClassLoader.loadClass(AppClassLoader.java:230)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.osgl.Osgl.classForName(Osgl.java:5216)
	at act.util.ClassFinderData$By$3.visit(ClassFinderData.java:74)
	at act.util.ClassFinderData$By$3.visit(ClassFinderData.java:67)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at org.osgl.Osgl$14.visit(Osgl.java:2324)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at act.util.ClassNode.visitTree(ClassNode.java:173)
	at act.util.ClassNode.visitSubTree(ClassNode.java:180)
	at act.util.ClassNode.visitSubTree(ClassNode.java:220)
	at act.util.ClassNode.visitSubTree(ClassNode.java:233)
	at act.util.ClassFinderData$By$2.tryFind(ClassFinderData.java:56)
	at act.util.ClassFinderData$By.find(ClassFinderData.java:88)
	at act.util.ClassFinderData$1.run(ClassFinderData.java:177)
	at act.job._Job$2.apply(_Job.java:291)
	at act.job._Job.doJob(_Job.java:253)
	at act.job._Job.run(_Job.java:193)
	at act.job._Job$LockableJobList.runSubJobs(_Job.java:75)
	- locked <0x00000006c801b510> (a act.job._Job$LockableJobList)
	at act.job._Job.runPrecedenceJobs(_Job.java:268)
	at act.job._Job.run(_Job.java:188)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:313)
	at act.event.EventBus.callOn(EventBus.java:230)
	at act.event.EventBus.callOn(EventBus.java:254)
	at act.event.EventBus.callOn(EventBus.java:275)
	at act.event.EventBus.emit(EventBus.java:296)
	- locked <0x00000006c7ff89c0> (a act.event.EventBus)
	at act.event.EventBus.emit(EventBus.java:284)
	- locked <0x00000006c7ff89c0> (a act.event.EventBus)
	at act.app.App.emit(App.java:828)
	at act.app.App.refresh(App.java:585)
	- locked <0x00000006c7a8f1b8> (a act.app.App)
	at act.app.AppManager.load(AppManager.java:83)
	at act.app.AppManager$_F$1.visit(AppManager.java:155)
	at act.app.AppManager$_F$1.visit(AppManager.java:151)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at act.app.AppScanner.scan(AppScanner.java:94)
	at act.app.AppScanner.scan(AppScanner.java:74)
	at act.app.AppManager.loadSingleApp(AppManager.java:61)
	at act.Act.start(Act.java:319)
	at act.Act.startApp(Act.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at act.boot.app.RunApp.start(RunApp.java:84)
	at act.boot.app.RunApp.start(RunApp.java:62)
	at act.Act.start(Act.java:640)
	at com.yabonza.Yabonza.main(Yabonza.java:19)
```

**Comment by greenlaw110** [comment]
fixed in 1.1.2
