### ISSUE TITLE
Controller method enhancement failure with try block

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#158]
Source code:

```java
    @GetAction("db")
    public final void singleQuery() throws SQLException {
        try (PreparedStatement query = query(conn)) {
            json(findOne(query));
        }
    }
```

Error stack:

```
Exception in thread "XNIO-1 task-1" org.osgl.exception.UnexpectedException: Invalid statement after render result statement at line 48
	at org.osgl.util.E.unexpected(E.java:96)
	at act.controller.bytecode.HandlerEnhancer$Transformer$InvocationHandler.injectThrowCode(HandlerEnhancer.java:523)
	at act.controller.bytecode.HandlerEnhancer$Transformer$InvocationHandler.handle(HandlerEnhancer.java:265)
	at act.controller.bytecode.HandlerEnhancer$Transformer$Segment.handle(HandlerEnhancer.java:245)
	at act.controller.bytecode.HandlerEnhancer$Transformer.doIt(HandlerEnhancer.java:144)
	at act.controller.bytecode.HandlerEnhancer.transform(HandlerEnhancer.java:121)
	at act.controller.bytecode.HandlerEnhancer.visitEnd(HandlerEnhancer.java:105)
	at act.asm.ClassReader.readMethod(ClassReader.java:1021)
	at act.asm.ClassReader.accept(ClassReader.java:693)
	at act.asm.ClassReader.accept(ClassReader.java:506)
	at act.app.AppClassLoader.asmEnhance(AppClassLoader.java:477)
	at act.app.AppClassLoader.enhance(AppClassLoader.java:464)
	at act.app.AppClassLoader.loadAppClass(AppClassLoader.java:441)
	at act.app.AppClassLoader.loadClass(AppClassLoader.java:230)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.osgl.Osgl.classForName(Osgl.java:5216)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:105)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createControllerAction(ReflectedHandlerInvoker.java:490)
	at act.Act$Mode.createRequestHandler(Act.java:130)
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:346)
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:287)
	at act.handler.builtin.controller.RequestHandlerProxy.corsSpec(RequestHandlerProxy.java:428)
	at act.handler.DelegateRequestHandler.corsSpec(DelegateRequestHandler.java:66)
	at act.app.ActionContext.applyCorsSpec(ActionContext.java:427)
	at act.handler.event.ResultEvent$1.apply(ResultEvent.java:61)
	at act.handler.event.ResultEvent$1.apply(ResultEvent.java:57)
	at org.osgl.mvc.MvcConfig.applyBeforeCommitResultHandler(MvcConfig.java:150)
	at org.osgl.mvc.result.Result.applyBeforeCommitHandler(Result.java:133)
	at org.osgl.mvc.result.Result.apply(Result.java:150)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by greenlaw110** [comment]
The bytecode is a bit complicated in this case. We won't fix it in short time. However there are easy workarounds:

Workaround A:

```java
    @GetAction("db")
    public final void singleQuery() throws SQLException {
        try (PreparedStatement query = query(conn)) {
            throw json(findOne(query));
        }
    }
```

Workaround B:

```java
    @GetAction("db")
    public final Result singleQuery() throws SQLException {
        try (PreparedStatement query = query(conn)) {
            return json(findOne(query));
        }
    }
```
