### ISSUE TITLE
Regex in route not working

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#169]
Sample code:

```java
    @GetAction("/int/n:[0-9]+")
    public int n(int n) {
        return n;
    }
```

Error stack:

```
java.lang.UnsupportedOperationException: null
	at org.osgl.Osgl$Var.add(Osgl.java:3730)
	at act.route.Router$Node.parseDynaNameStyleA(Router.java:1148)
	at act.route.Router$Node.parseDynaName(Router.java:975)
	at act.route.Router$Node.<init>(Router.java:756)
	at act.route.Router$Node.addChild(Router.java:900)
	at act.route.Router._locate(Router.java:527)
	at act.route.Router.addMapping(Router.java:236)
	at act.route.Router.addMapping(Router.java:228)
	at act.controller.bytecode.ControllerByteCodeScanner$RouteRegister.registerOnContext(ControllerByteCodeScanner.java:796)
	at act.controller.bytecode.ControllerByteCodeScanner$RouteRegister.run(ControllerByteCodeScanner.java:744)
    ...
```

Another bug in this notation:

```java
    @GetAction("/int/{n<[0-9]+>}")
    public int n(int n) {
        return n;
    }
```

There is no error stack, but the pattern cannot be correctly parsed thus it will always return 400 bad request

**Comment by greenlaw110** [comment]
Workaround is:

```java
    @GetAction("/int/{<[0-9]+>n}")
    public int n(int n) {
        return n;
    }
```
