### ISSUE TITLE
NPE triggered on actframework official website

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#187]
Here is the console log:

```
08:31:06.922 [XNIO-1 task-2] ERROR a.x.NetworkHandler - Error handling network request
java.lang.NullPointerException: null
        at act.route.Router.inferFullActionPath(Router.java:329)
        at act.route.Router.inferFullActionPath(Router.java:312)
        at act.controller.Controller$Util.redirect(Controller.java:435)
        at act_site.DocLoader._handle(DocLoader.java:41)
        at act_site.DocLoader.handle(DocLoader.java:30)
        at act.xio.NetworkHandler$1.run(NetworkHandler.java:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by greenlaw110** [comment]
The line triggers the above error:

```java
throw Controller.Util.redirect("/doc/index.md");
```

**Comment by greenlaw110** [comment]
which is in turn triggered by a bug in `Router.inferFullActionPath(String, $.Function)`
