### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/persistence/Persistence

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#190]
The following error triggered when parameter validation is running by apache bval:

```
Exception in thread "XNIO-1 task-2" java.lang.NoClassDefFoundError: javax/persistence/Persistence
	at org.apache.bval.jsr.resolver.JPATraversableResolver.isReachable(JPATraversableResolver.java:33)
	at org.apache.bval.jsr.resolver.DefaultTraversableResolver.isReachable(DefaultTraversableResolver.java:58)
	at org.apache.bval.jsr.resolver.CachingTraversableResolver.isReachable(CachingTraversableResolver.java:81)
	at org.apache.bval.jsr.ConstraintValidation.isReachable(ConstraintValidation.java:454)
	at org.apache.bval.jsr.ConstraintValidation.validateGroupContext(ConstraintValidation.java:188)
	at org.apache.bval.jsr.ConstraintValidation.validate(ConstraintValidation.java:145)
	at org.apache.bval.util.ValidationHelper.validateProperty(ValidationHelper.java:236)
	at org.apache.bval.jsr.ClassValidator.validateBean(ClassValidator.java:460)
	at org.apache.bval.jsr.ClassValidator.validateBeanNet(ClassValidator.java:406)
	at org.apache.bval.jsr.ClassValidator$JsrValidationCallback.validate(ClassValidator.java:1152)
	at org.apache.bval.util.ValidationHelper.validateBeanInContext(ValidationHelper.java:89)
	at org.apache.bval.util.ValidationHelper.validateContext(ValidationHelper.java:70)
	at org.apache.bval.jsr.ClassValidator.validateInvocationParameters(ClassValidator.java:818)
	at org.apache.bval.jsr.ClassValidator.validateParameters(ClassValidator.java:1071)
	at act.inject.param.ParamValueLoaderService.loadMethodParams(ParamValueLoaderService.java:165)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.params(ReflectedHandlerInvoker.java:637)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:256)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:51)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:466)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:185)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1282)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javax.persistence.Persistence
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at act.boot.app.FullStackAppBootstrapClassLoader.loadClass(FullStackAppBootstrapClassLoader.java:303)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more
```

**Comment by greenlaw110** [comment]
This is caused by jpa dependency issue. On the system triggered this error it uses ebean-10's jpa-2.2.1 jar which does not have the `javax.persistence.Persistence` class inside.

Solution is force act to use JPA 2.1 by adding the following dependency

```
    <dependency>
      <groupId>org.hibernate.javax.persistence</groupId>
      <artifactId>hibernate-jpa-2.1-api</artifactId>
      <version>1.0.0.Final</version>
    </dependency>
```

**Comment by greenlaw110** [comment]
fixed in 1.3.1

**Comment by vishaldhardubey** [comment]
i couldn't find 1.3.1 in maven.

**Comment by greenlaw110** [comment]
@vishaldhardubey it's here: http://search.maven.org/#artifactdetails%7Corg.actframework%7Cact%7C1.3.1%7Cjar

However 1.3.1 is way outdated. The most recent version is 1.8.8-RC11.

**Comment by greenlaw110** [comment]
@hkhaghani do you mean you get the issue when you use ActFramework and EclipseLink? Can you share your code of `JpaTest.java`?

**Comment by hkhaghani** [comment]
@greenlaw110 
My problem is solved. 
I remove `<scope>provided</scope>` from `<dependency>` 

thank you

**Comment by ronatkumar6084** [comment]
This is error I' m getting

May 10, 2024 7:28:19 PM org.springframework.context.support.AbstractApplicationContext refresh
WARNING: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'factory' defined in class path resource [config.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/persistence/Entity
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'factory' defined in class path resource [config.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/persistence/Entity
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:860)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
	at com.spring.orm.App.main(App.java:14)
Caused by: java.lang.NoClassDefFoundError: javax/persistence/Entity
	at org.springframework.orm.hibernate5.LocalSessionFactoryBuilder.<clinit>(LocalSessionFactoryBuilder.java:104)
	at org.springframework.orm.hibernate5.LocalSessionFactoryBean.afterPropertiesSet(LocalSessionFactoryBean.java:495)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	... 12 more
Caused by: java.lang.ClassNotFoundException: javax.persistence.Entity
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 16 more


pom.xml

<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>3.8.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>5.2.3.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>5.2.3.RELEASE</version>
		</dependency>
		
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-orm</artifactId>
			<version>5.2.3.RELEASE</version>
		</dependency>
		
		<dependency>
			<groupId>org.hibernate.orm</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>6.3.1.Final</version>
		</dependency>
		
		<dependency>
			<groupId>com.mysql</groupId>
			<artifactId>mysql-connector-j</artifactId>
			<version>8.0.33</version>
		</dependency>
	</dependencies>

**Comment by ronatkumar6084** [comment]
> @vishaldhardubey it's here: http://search.maven.org/#artifactdetails%7Corg.actframework%7Cact%7C1.3.1%7Cjar
> 
> However 1.3.1 is way outdated. The most recent version is 1.8.8-RC11.

Not working for me

**Comment by ronatkumar6084** [comment]
Error creating bean with name 'factory' defined in class path resource [config.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/persistence/Entity
