### ISSUE TITLE
Log the URL with handler error message

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#192]
At the moment when there are error encountered in handler, it prints out:

```
10:28:08.046 [XNIO-1 task-12] ERROR a.h.b.c.RequestHandlerProxy - Error handling request
java.lang.IllegalArgumentException: null
        at org.bson.types.ObjectId.isValid(ObjectId.java:92)
        at org.bson.types.ObjectId.parseHexString(ObjectId.java:549)
        at org.bson.types.ObjectId.<init>(ObjectId.java:240)
        at act.db.morphia.MorphiaDao.findById(MorphiaDao.java:48)
        at com.yabonza.endpoint.MyPropertyService.updateProperty(MyPropertyService.java:206)
        at com.yabonza.endpoint.MyPropertyServiceMethodAccess.invoke(Unknown Source)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:572)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:267)
        at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:51)
        at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:466)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:185)
        at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
        at act.route.Router$ContextualHandler.handle(Router.java:1282)
        at act.xio.NetworkHandler$1.run(NetworkHandler.java:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

This request require it to log the current request additional information: the request URL and HTTP method

**Comment by greenlaw110** [comment]
Fixed:

```
11:13:38.116 [XNIO-1 task-1] ERROR a.h.b.c.RequestHandlerProxy - Error handling request: [GET] /gh/192
java.lang.NullPointerException: null
	at demo.helloworld.GH192.test(GH192.java:9)
	at demo.helloworld.GH192MethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:572)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:267)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:51)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:467)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:185)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1282)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
