### ISSUE TITLE
Source code refresh triggered error

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#2]
While I played around with the HelloWorld demo I run into this error:

```
SEVERE: Error handling request
java.lang.ClassCastException: act.fsa.helloworld.HelloWorldApp cannot be cast to act.fsa.helloworld.HelloWorldApp
        at act.fsa.helloworld.HelloWorldAppFieldAccess.set(Unknown Source)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker$2.apply(ReflectedHandlerInvoker.java:192)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker$2.apply(ReflectedHandlerInvoker.java:186)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.applyAppContext(ReflectedHandlerInvoker.java:119)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:82)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker$_Before.handle(ReflectedHandlerInvoker.java:235)
        at act.handler.builtin.controller.RequestHandlerProxy$GroupInterceptorWithResult.apply(RequestHandlerProxy.java:346)
        at act.handler.builtin.controller.RequestHandlerProxy.handleBefore(RequestHandlerProxy.java:251)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:120)
        at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:18)
        at act.route.Router$ContextualHandler.handle(Router.java:514)
        at act.xio.NetworkClient.handle(NetworkClient.java:40)
        at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:27)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:181)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:108)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:49)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:539)
```

**Comment by greenlaw110** [comment]
Fixed in 0.1.0 version
