### ISSUE TITLE
NPE after hot reload

### ISSUE THREAD

**Issue by koupeng** [actframework/actframework#204]
I got the following error stack after Act hot reload the app:

```
16:23:18.678 [cli-thread-1] WARN  a.m.MailerConfig - smtp host configuration not found, will use mock smtp to send email
16:23:18.678 [cli-thread-1] WARN  a.c.AppConfig - host is not configured. Use localhost as hostname
ebean-enhance> cls: com/unicom/app/role/Role_Menu  msg: enhanced 
ebean-enhance> cls: com/unicom/app/role/Role  msg: enhanced 
ebean-enhance> cls: com/unicom/app/role/User_Role  msg: enhanced 
ebean-enhance> cls: com/unicom/app/menu/Menu  msg: enhanced 
ebean-enhance> cls: com/unicom/app/user/User  msg: enhanced 
16:23:18.716 [cli-thread-1] INFO  o.a.d.p.ConnectionPool - DataSourcePool [default] autoCommit[false] transIsolation[READ_COMMITTED] min[2] max[100]
16:23:18.733 [cli-thread-1] WARN  a.j._Job - error executing job 2k8-Tn8H3
javax.persistence.PersistenceException: java.sql.SQLException: Interrupted getting connection from pool
	at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:347)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:99)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:42)
	at com.avaje.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:108)
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:67)
	at act.db.ebean.EbeanService.createDataSource(EbeanService.java:72)
	at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:96)
	at act.db.sql.SqlDbService.access$000(SqlDbService.java:23)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:36)
	at act.job._Job$2.apply(_Job.java:291)
	at act.job._Job.doJob(_Job.java:253)
	at act.job._Job.run(_Job.java:193)
	at act.job._Job$LockableJobList.runSubJobs(_Job.java:75)
	at act.job._Job.runPrecedenceJobs(_Job.java:268)
	at act.job._Job.run(_Job.java:188)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:313)
	at act.event.EventBus.callOn(EventBus.java:230)
	at act.event.EventBus.callOn(EventBus.java:254)
	at act.event.EventBus.callOn(EventBus.java:275)
	at act.event.EventBus.emit(EventBus.java:296)
	at act.event.EventBus.emit(EventBus.java:284)
	at act.app.App.emit(App.java:830)
	at act.app.App.refresh(App.java:588)
	at act.app.App.refresh(App.java:484)
	at act.app.App.checkUpdates(App.java:393)
	at act.app.CliServer$1.run(CliServer.java:153)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Interrupted getting connection from pool
	at org.avaje.datasource.pool.PooledConnectionQueue.getPooledConnection(PooledConnectionQueue.java:278)
	at org.avaje.datasource.pool.ConnectionPool.getPooledConnection(ConnectionPool.java:712)
	at org.avaje.datasource.pool.ConnectionPool.getConnection(ConnectionPool.java:700)
	at com.avaje.ebeaninternal.server.core.DefaultContainer.checkDataSource(DefaultContainer.java:340)
	... 32 common frames omitted
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at org.avaje.datasource.pool.PooledConnectionQueue._getPooledConnection(PooledConnectionQueue.java:295)
	at org.avaje.datasource.pool.PooledConnectionQueue.getPooledConnection(PooledConnectionQueue.java:271)
	... 35 common frames omitted
16:23:18.734 [cli-thread-1] INFO  a.Act - App[ActMVC] loaded in 777ms
16:42:33.717 [XNIO-1 task-94] ERROR a.h.b.c.RequestHandlerProxy - Error handling request
java.lang.NullPointerException: null
	at org.osgl.util.E.NPE(E.java:56)
	at org.osgl.Osgl.notNull(Osgl.java:5052)
	at act.db.ebean.EbeanDao.ebean(EbeanDao.java:63)
	at act.db.ebean.EbeanDao.<init>(EbeanDao.java:49)
	at act.db.ebean.EbeanService.defaultDao(EbeanService.java:96)
	at act.app.DbServiceManager.dao(DbServiceManager.java:131)
	at act.db.ebean.util.EbeanDaoLoader.load(EbeanDaoLoader.java:27)
	at act.db.ebean.util.EbeanDaoLoader.load(EbeanDaoLoader.java:13)
	at org.osgl.inject.Genie$4.get(Genie.java:628)
	at org.osgl.inject.Genie$5.get(Genie.java:670)
	at org.osgl.inject.Genie$FieldInjector.applyTo(Genie.java:217)
	at org.osgl.inject.Genie$7.get(Genie.java:724)
	at org.osgl.inject.Genie$5.get(Genie.java:670)
	at org.osgl.inject.Genie$FieldInjector.applyTo(Genie.java:217)
	at org.osgl.inject.Genie$7.get(Genie.java:724)
	at org.osgl.inject.Genie$5.get(Genie.java:670)
	at act.inject.param.ParamValueLoaderService$3.load(ParamValueLoaderService.java:202)
	at act.inject.param.ParamValueLoaderService$6.load(ParamValueLoaderService.java:649)
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:49)
	at act.inject.param.ParamValueLoaderService.loadHostBean(ParamValueLoaderService.java:140)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.controllerInstance(ReflectedHandlerInvoker.java:450)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:244)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker$_Before.handle(ReflectedHandlerInvoker.java:708)
	at act.handler.builtin.controller.RequestHandlerProxy$GroupInterceptorWithResult.apply(RequestHandlerProxy.java:587)
	at act.handler.builtin.controller.RequestHandlerProxy.handleBefore(RequestHandlerProxy.java:459)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:182)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1288)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by koupeng** [comment]
我在用act做一个后台web系统，调试的过程中，经常出现这个问题。感觉就是注入那个Dao,,,不知道为什么就变成了NULL。我有个疑问，，注入的这个Dao的生命周期是从什么时候开始的？比如，，下面我在全局拦截器中，使用dao,则直接为null。
`@Singleton
public class MyGlobalBeforeInterceptor extends BeforeInterceptor {
    private static Logger LOGGER= L.get(MyGlobalBeforeInterceptor.class);
    //审计Dao
    @Inject
    private EbeanDao<String,Audit> auditDao;`

**Comment by greenlaw110** [comment]
@koupeng `NullPointerException` 之后系统状态被破坏了，因此 `dao` 会变成`null`. 我会在 `1.3.4` 里面修复这个问题

**Comment by koupeng** [comment]
期待~~~~

**Comment by greenlaw110** [comment]
@koupeng 你用的是HikariCP吗？

**Comment by koupeng** [comment]
（1）我用的这个：
` 
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <version>${mysql.version}</version>
    </dependency>`
（2）我的db.*配置
`db.url=jdbc:mysql://localhost:3306/actmvc?useUnicode=true&characterEncoding=utf8`
是不是我配置的问题？？？

**Comment by greenlaw110** [comment]
这个是 jdbc driver。你的`pom.xml`文件里面有没有 HikariCP？

**Comment by koupeng** [comment]
没有那个！

**Comment by greenlaw110** [comment]
The following issues are used to track the root cause of this issue:

* #217 
* #216 

Also `act-sql-common-1.1.0` and `act-ebean2-1.2.0` which catch up to `act-1.4.0` contains the code fixes for this issue

**Comment by greenlaw110** [comment]
@koupeng please try on these versions:

* act-1.4.0-SNAPSHOT
* act-ebean2-1.1.0-SNAPSHOT (if you are using Java 8)
* act-ebean-1.2.0-SNAPSHOT (if you are using Java 7 or below)

**Comment by koupeng** [comment]
OK,I will try after the Dragon Boat Festival，hh。
