### ISSUE TITLE
Error running in prod mode: java.lang.IllegalStateException: Native library for Attach API not available in this JRE

### ISSUE THREAD

**Issue by koupeng** [actframework/actframework#213]
When I start the app in `prod` mode on my local environment I got the following error messages:

```
scan pkg: com.unicom.app
base dir: E:\gitsource\actframework\actmvc\target\dist
     pid: 8368
 profile: prod
    mode: PROD

     zen: Simple things should be simple, complex things should be possible.

2017-05-26 13:49:20,019 INFO  a.Act:57 - loading application(s) ...
2017-05-26 13:49:20,028 INFO  a.Act:57 - App starting ....
2017-05-26 13:49:20,221 WARN  a.c.AppConfig:72 - Application secret key not set! You are in the dangerous zone!!!
2017-05-26 13:49:20,686 INFO  a.d.DbService:57 - "agentPackage" configured: com.unicom.app
2017-05-26 13:49:20,686 INFO  a.a.DbServiceManager:57 - db service[default] initialized
五月 26, 2017 1:49:20 下午 act.db.ebean.EbeanAgentLoader loadAgent
信息: dynamically loading javaagent for E:/gitsource/actframework/actmvc/target/dist/lib/ebean-agent-8.1.1.jar
2017-05-26 13:49:20,761 INFO  a.Act:57 - App shutting down ....
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: Native library for Attach API not available in this JRE
        at act.db.ebean.EbeanAgentLoader.loadAgent(EbeanAgentLoader.java:86)
        at act.db.ebean.EbeanAgentLoader.loadAgentFromClasspath(EbeanAgentLoader.java:121)
        at act.db.ebean.EbeanService$1.on(EbeanService.java:48)
        at act.event.EventBus.callOn(EventBus.java:230)
        at act.event.EventBus.callOn(EventBus.java:254)
        at act.event.EventBus.callOn(EventBus.java:275)
        at act.event.EventBus.emit(EventBus.java:296)
        at act.event.EventBus.emit(EventBus.java:284)
        at act.app.App.emit(App.java:830)
        at act.app.App.refresh(App.java:548)
        at act.app.AppManager.load(AppManager.java:83)
        at act.app.AppManager$_F$1.visit(AppManager.java:155)
        at act.app.AppManager$_F$1.visit(AppManager.java:151)
        at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
        at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
        at act.app.AppScanner.scan(AppScanner.java:94)
        at act.app.AppScanner.scan(AppScanner.java:74)
        at act.app.AppManager.loadSingleApp(AppManager.java:61)
        at act.Act.start(Act.java:319)
        at act.Act.startApp(Act.java:290)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at act.boot.app.RunApp.start(RunApp.java:84)
        at act.boot.app.RunApp.start(RunApp.java:62)
        at act.Act.start(Act.java:648)
        at com.unicom.app.App.main(App.java:27)
Caused by: java.lang.IllegalStateException: Native library for Attach API not available in this JRE
        at act.db.ebean.EbeanAgentLoader.getVirtualMachineImplementationFromEmbeddedOnes(EbeanAgentLoader.java:179)
        at act.db.ebean.EbeanAgentLoader.loadAgent(EbeanAgentLoader.java:77)
        ... 27 more
Caused by: java.lang.UnsatisfiedLinkError: no attach in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at sun.tools.attach.WindowsVirtualMachine.<clinit>(WindowsVirtualMachine.java:185)
        at act.db.ebean.EbeanAgentLoader.getVirtualMachineImplementationFromEmbeddedOnes(EbeanAgentLoader.java:157)
        ... 28 more
```

**Comment by greenlaw110** [comment]
Can you check out these links and see if they will help out?

* https://stackoverflow.com/questions/11961571/jmockit-native-library-for-attach-api-not-available-in-this-jre-error
* https://stackoverflow.com/questions/31486622/native-library-for-attach-api-not-available-in-this-jre

**Comment by koupeng** [comment]
Thank you!!!
I add my jre path"%JAVA_HOME%\jre\bin" to the environment variable:Path。Then restart computer and it worked!
