### ISSUE TITLE
Cannot start app: java.lang.LinkageError

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#218]
Error stack:

```
Exception in thread "main" org.osgl.exception.UnexpectedException: Unknown error captured starting the application
	at org.osgl.util.E.unexpected(E.java:104)
	at act.boot.app.RunApp.start(RunApp.java:90)
	at act.boot.app.RunApp.start(RunApp.java:62)
	at act.Act.start(Act.java:648)
	at com.myapp.AppEntry.main(Yabonza.java:20)
Caused by: java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/stevesoft/pat/ReplaceRule"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.stevesoft.pat.Regex.compile(Regex.java:459)
	at com.stevesoft.pat.Regex.<init>(Regex.java:295)
	at org.rythmengine.internal.parser.build_in.ExtendsParser.<clinit>(ExtendsParser.java:83)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.rythmengine.internal.dialect.DialectBase.registerBuildInParsers(DialectBase.java:49)
	at org.rythmengine.internal.dialect.DialectBase.<init>(DialectBase.java:20)
	at org.rythmengine.internal.dialect.Rythm.<init>(Rythm.java:21)
	at org.rythmengine.internal.dialect.Rythm.<clinit>(Rythm.java:19)
	at org.rythmengine.internal.dialect.DialectManager.<clinit>(DialectManager.java:20)
	at org.rythmengine.RythmEngine.<init>(RythmEngine.java:296)
	at org.rythmengine.RythmEngine.<init>(RythmEngine.java:534)
	at act.view.rythm.RythmView.createEngine(RythmView.java:161)
	at act.view.rythm.RythmView.getEngine(RythmView.java:95)
	at act.view.rythm.RythmView.registerBuiltInTransformer(RythmView.java:175)
	at act.app.App.registerBuiltInRythmTransformers(App.java:1211)
	at act.app.App.initViewManager(App.java:1206)
	at act.app.App.refresh(App.java:588)
	at act.app.AppManager.load(AppManager.java:83)
	at act.app.AppManager$_F$1.visit(AppManager.java:155)
	at act.app.AppManager$_F$1.visit(AppManager.java:151)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at act.app.AppScanner.scan(AppScanner.java:94)
	at act.app.AppScanner.scan(AppScanner.java:74)
	at act.app.AppManager.loadSingleApp(AppManager.java:61)
	at act.Act.start(Act.java:319)
	at act.Act.startApp(Act.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at act.boot.app.RunApp.start(RunApp.java:84)
	... 3 more
```

**Comment by greenlaw110** [comment]
This issue is caused by upgrading `ebean-agent` from `10.1.7` to `10.2.1`. An issue report to `ebean-agent` has been submitted: 

https://github.com/ebean-orm/ebean-agent/issues/56

**Comment by greenlaw110** [comment]
Downgrade `ebean-agent` version in [act-ebean2](http://github.com/actframework/act-ebean2) solved the issue
