### ISSUE TITLE
Generate ASCII banner for favicon

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#228]
When anyone of the following files found it shall generate corresponding ASCII in the banner text:

1. `/asset/favicon.png`
2. `/asset/img/favicon.png` 
3. `/asset/image/favicon.png`
4. `/asset/favicon.ico`
5. `/asset/img/favicon.ico` 
6. `/asset/image/favicon.ico`

**Comment by greenlaw110** [comment]
![image](https://cloud.githubusercontent.com/assets/216930/26757946/77f99ae2-4911-11e7-944b-fc38591fa640.png)

**Comment by greenlaw110** [comment]
Got the following error when running on remote server:

```
Exception in thread "main" org.osgl.exception.UnexpectedException: Unknown error captured starting the application
        at org.osgl.util.E.unexpected(E.java:104)
        at act.boot.app.RunApp.start(RunApp.java:90)
        at act.boot.app.RunApp.start(RunApp.java:62)
        at act.Act.start(Act.java:681)
        at com.yabonza.Yabonza.main(Yabonza.java:20)
Caused by: java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
        at ascii.Image2ascii.scale(Image2ascii.java:97)
        at ascii.Image2ascii.scale(Image2ascii.java:145)
        at ascii.Image2ascii.convert(Image2ascii.java:59)
        at ascii.Image2ascii.render(Image2ascii.java:176)
        at act.util.Banner.favicon(Banner.java:161)
        at act.util.Banner.banner(Banner.java:72)
        at act.util.Banner.print(Banner.java:51)
        at act.Act.start(Act.java:336)
        at act.Act.startApp(Act.java:308)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at act.boot.app.RunApp.start(RunApp.java:84)
```

**Comment by greenlaw110** [comment]
The solution is to add JVM argument `-Djava.awt.headless=true` to start up scripts. However the framework shall NOT raise out the issue even render favor icon failure
