### ISSUE TITLE
`OnAppStart` event handler randomly missed the trigger

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#249]
One of the issue with #247 is the following code failed to be triggered on app start:

```java
	@OnAppStart
	public void routing() {
		Act.LOGGER.info("R+ Add JSON route mapping");
		Act.getNonblock("/json", context -> context.resp()
				.contentType(H.Format.JSON.contentType())
				.writeContent(JSON.toJSONString(new Message(HELLO_WORLD))));
	}
```

This issue happens randomly

**Comment by greenlaw110** [comment]
Found it randomly failed to run logic that should be triggered upon  `DB_SVC_LOADED` event in `act.App.refresh()` 

![image](https://user-images.githubusercontent.com/216930/27512645-12816368-598b-11e7-8510-f6f6b84c6145.png)

The console log shows no `PRE_START`, `STATELESS_PROVISIONED` and `START` event triggered:

![image](https://user-images.githubusercontent.com/216930/27512400-ce14c12e-5981-11e7-9ec3-aff354f07fd6.png)

**Comment by greenlaw110** [comment]
New findings:

Two db initialization thread never stop:

![image](https://user-images.githubusercontent.com/216930/27513814-93b2db38-59b8-11e7-9dcf-af775123f847.png)

And the stack info:

```java
"jobs-thread-4" #24 prio=5 os_prio=0 tid=0x00007fa5f56a3000 nid=0x76bf in Object.wait() [0x00007fa56f564000]
   java.lang.Thread.State: RUNNABLE
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.sql.DriverManager$2.run(DriverManager.java:603)
	at java.sql.DriverManager$2.run(DriverManager.java:583)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.sql.DriverManager.loadInitialDrivers(DriverManager.java:583)
	at java.sql.DriverManager.<clinit>(DriverManager.java:101)
	at com.mysql.cj.jdbc.Driver.<clinit>(Driver.java:49)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at act.db.sql.DataSourceConfig.ensureDefaultDatasourceConfig(DataSourceConfig.java:152)
	at act.db.sql.DataSourceConfig.<init>(DataSourceConfig.java:109)
	at act.db.sql.SqlDbServiceConfig.<init>(SqlDbServiceConfig.java:35)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:54)
	at act.db.sql.SqlDbService$1.on(SqlDbService.java:46)
	at act.event.EventBus.callOn(EventBus.java:236)
	at act.event.EventBus.access$100(EventBus.java:50)
	at act.event.EventBus$2.run(EventBus.java:268)
	at act.job.AppJobManager$ContextualJob$1.apply(AppJobManager.java:371)
	at act.job._Job.doJob(_Job.java:272)
	at act.job._Job.run(_Job.java:212)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000006c96587c0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"jobs-thread-3" #23 prio=5 os_prio=0 tid=0x00007fa5f56a2800 nid=0x76be in Object.wait() [0x00007fa56fafc000]
   java.lang.Thread.State: RUNNABLE
	at org.postgresql.Driver.register(Driver.java:687)
	at org.postgresql.Driver.<clinit>(Driver.java:73)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:318)
	at act.db.sql.datasource.HikariDataSourceProvider.createDataSource(HikariDataSourceProvider.java:38)
	at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:178)
	at act.db.sql.SqlDbService.access$500(SqlDbService.java:29)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:59)
	at act.db.sql.SqlDbService$1.on(SqlDbService.java:46)
	at act.event.EventBus.callOn(EventBus.java:236)
	at act.event.EventBus.access$100(EventBus.java:50)
	at act.event.EventBus$2.run(EventBus.java:268)
	at act.job.AppJobManager$ContextualJob$1.apply(AppJobManager.java:371)
	at act.job._Job.doJob(_Job.java:272)
	at act.job._Job.run(_Job.java:212)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000006c9658168> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

**Comment by greenlaw110** [comment]
It's caused by concurrent issue with `java.sql.DriverManager`. Fixed in https://github.com/actframework/act-sql-common/commit/ac5318cabafa930a25c2af4631bf56878af30cda
