### ISSUE TITLE
It shall report `405 Method Not Allowed` for HTTP method not recongized

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#269]
Issue a HTTP LINK request to Act application will cause `500 Internal Server Error`. Instead it shall respond with `405 Method Not Allowed`

**Comment by greenlaw110** [comment]
The error stack:

```
java.lang.IllegalArgumentException: No enum constant org.osgl.http.H.Method.LINK
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.osgl.http.H$Method.valueOf(H.java:35)
	at org.osgl.http.H$Method.valueOfIgnoreCase(H.java:64)
	at act.xio.undertow.UndertowRequest._method(UndertowRequest.java:66)
	at act.RequestImplBase.method(RequestImplBase.java:56)
	at act.app.ActionContext.<init>(ActionContext.java:115)
	at act.app.ActionContext.create(ActionContext.java:941)
	at act.xio.undertow.ActHttpHandler.createActionContext(ActHttpHandler.java:53)
	at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:46)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:244)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:135)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:148)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:92)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:51)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:128)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)
```
