### ISSUE TITLE
发送邮件时出错：系统找不到指定的路径

### ISSUE THREAD

**Issue by tanqimin** [actframework/actframework#283]
日志如下：

> DEBUG: setDebug: JavaMail version 1.5.0-b01
16:52:40.299 [jobs-thread-5] ERROR act.mail.MailerContext - Error sending email: act.mail.MailerContext@2eaeb467
java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\tanqimin\AppData\Local\Temp\__rythm_Server start...\tanqimin_mail_Report_sendDaily_html__R_T_C__.java (系统找不到指定的路径。)
	at org.rythmengine.internal.compiler.TemplateClassCache.cacheTemplateClassSource(TemplateClassCache.java:159)
	at org.rythmengine.internal.compiler.TemplateClass.refresh(TemplateClass.java:615)
	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:362)
	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:332)
	at org.rythmengine.internal.compiler.TemplateClass.<init>(TemplateClass.java:324)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:887)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:910)
	at act.view.rythm.RythmTemplate.template(RythmTemplate.java:65)
	at act.view.rythm.RythmTemplate.render(RythmTemplate.java:60)
	at act.view.TemplateBase.render(TemplateBase.java:60)
	at act.mail.MailerContext.createMessage(MailerContext.java:356)
	at act.mail.MailerContext.send(MailerContext.java:280)
	at act.mail.Mailer$Util$1.call(Mailer.java:98)
	at act.mail.Mailer$Util$1.call(Mailer.java:95)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: C:\Users\tanqimin\AppData\Local\Temp\__rythm_Server start...\tanqimin_mail_Report_sendDaily_html__R_T_C__.java (系统找不到指定的路径。)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.rythmengine.internal.compiler.TemplateClassCache.cacheTemplateClassSource(TemplateClassCache.java:155)
	... 19 common frames omitted
DEBUG: setDebug: JavaMail version 1.5.0-b01
16:52:45.290 [jobs-thread-7] ERROR act.mail.MailerContext - Error sending email: act.mail.MailerContext@68055276
java.lang.RuntimeException: Error load template instance for /tanqimin/mail/Report/sendDaily.html
	at org.rythmengine.internal.compiler.TemplateClass.templateInstance_(TemplateClass.java:409)
	at org.rythmengine.internal.compiler.TemplateClass.asTemplate(TemplateClass.java:428)
	at org.rythmengine.internal.compiler.TemplateClass.asTemplate(TemplateClass.java:436)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:889)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:910)
	at act.view.rythm.RythmTemplate.template(RythmTemplate.java:65)
	at act.view.rythm.RythmTemplate.render(RythmTemplate.java:60)
	at act.view.TemplateBase.render(TemplateBase.java:60)
	at act.mail.MailerContext.createMessage(MailerContext.java:356)
	at act.mail.MailerContext.send(MailerContext.java:280)
	at act.mail.Mailer$Util$1.call(Mailer.java:98)
	at act.mail.Mailer$Util$1.call(Mailer.java:95)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\tanqimin\AppData\Local\Temp\__rythm_Server start...\tanqimin_mail_Report_sendDaily_html__R_T_C__.rythm (系统找不到指定的路径。)
	at org.rythmengine.internal.compiler.TemplateClassCache.cacheTemplateClass(TemplateClassCache.java:207)
	at org.rythmengine.internal.compiler.TemplateClass.enhance(TemplateClass.java:743)
	at org.rythmengine.internal.compiler.TemplateClass.compiled(TemplateClass.java:785)
	at org.rythmengine.internal.compiler.TemplateCompiler$2.acceptResult(TemplateCompiler.java:306)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:563)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:462)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:417)
	at org.rythmengine.internal.compiler.TemplateCompiler.compile(TemplateCompiler.java:323)
	at org.rythmengine.internal.compiler.TemplateClass.compile(TemplateClass.java:673)
	at org.rythmengine.internal.compiler.TemplateClassLoader.loadTemplateClass(TemplateClassLoader.java:294)
	at org.rythmengine.internal.compiler.TemplateClassLoader.loadClass(TemplateClassLoader.java:240)
	at org.rythmengine.internal.compiler.TemplateClass.loadJavaClass(TemplateClass.java:387)
	at org.rythmengine.internal.compiler.TemplateClass.templateInstance_(TemplateClass.java:400)
	... 17 common frames omitted
Caused by: java.io.FileNotFoundException: C:\Users\tanqimin\AppData\Local\Temp\__rythm_Server start...\tanqimin_mail_Report_sendDaily_html__R_T_C__.rythm (系统找不到指定的路径。)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.rythmengine.internal.compiler.TemplateClassCache.cacheTemplateClass(TemplateClassCache.java:171)
	... 29 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:61312', transport: 'socket'
Process finished with exit code 1

**Comment by greenlaw110** [comment]
试过你的项目，不能重现这个问题啊

**Comment by greenlaw110** [comment]
closed as no response from issue submitter
