### ISSUE TITLE
Post request with query parameters and no form body cause 500 error

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#296]
Error stack:

```
java.lang.NullPointerException: null
	at act.inject.param.ParamTree.buildNode(ParamTree.java:47)
	at act.inject.param.ParamTree.build(ParamTree.java:40)
	at act.inject.param.ParamValueLoaderService.ensureParamTree(ParamValueLoaderService.java:554)
	at act.inject.param.CollectionLoader.load(CollectionLoader.java:85)
	at act.inject.param.JsonParamValueLoader.load(JsonParamValueLoader.java:70)
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:49)
	at act.inject.param.ParamValueLoaderService.loadMethodParams(ParamValueLoaderService.java:173)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.params(ReflectedHandlerInvoker.java:666)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:262)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:51)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:484)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:193)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1296)
	at act.xio.NetworkHandler$2.run(NetworkHandler.java:145)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by greenlaw110** [comment]
This is caused by the parameter binding logic trying to evaluate an `null` value `_body` param

**Comment by greenlaw110** [comment]
Cannot reproduce
