### ISSUE TITLE
JSON binding doesn't work well with @DbBind annotation

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#297]
Java source:

```java
@PostAction("service/book")
public void bookService(@DbBind("propertyId") @NotNull Property property, Set<String> services, PostOffice postOffice) {
    postOffice.sendServiceBookNotification(me, property, services);
}
```

When sending sample data like:

```json
{
	"propertyId": "58abf33a623174708771bb41",
	"services": ["abc service"]
}
```

always get `400 BadRequest` and the server side log is:

```
com.alibaba.fastjson.JSONException: exepct '[', but {, pos 14, json : {"services": {
	"propertyId": "58abf33a623174708771bb41",
	"services": ["abc service"]
}}
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseArray(DefaultJSONParser.java:662)
	at com.alibaba.fastjson.serializer.CollectionCodec.deserialze(CollectionCodec.java:120)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:78)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:632)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:230)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:226)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:630)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:358)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:262)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:475)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.ensureJsonDTOGenerated(ReflectedHandlerInvoker.java:329)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:249)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:51)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:484)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:193)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1296)
	at act.xio.NetworkHandler$2.run(NetworkHandler.java:145)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by greenlaw110** [comment]
The root cause is in the `JsonDTOClassManager`:

![image](https://user-images.githubusercontent.com/216930/28147367-4e362fc4-67c3-11e7-985e-5751da14c0a6.png)

Here althought `Property` is **provided** (injected) it still needs the request parameter named "property", thus we can't simply say it is provided and waive the request parameter binding on that
