### ISSUE TITLE
java.lang.IllegalStateException: parent context not found

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#307]
```
java.lang.IllegalStateException: parent context not found
	at act.asm.AsmContext.enterSubContext(AsmContext.java:134)
	at act.asm.AsmContext.enterMethod(AsmContext.java:92)
	at act.asm.ClassReader.readMethod(ClassReader.java:926)
	at act.asm.ClassReader.accept(ClassReader.java:697)
	at act.asm.ClassReader.accept(ClassReader.java:506)
	at act.app.AppClassLoader.scanByteCode(AppClassLoader.java:285)
	at act.app.DevModeClassLoader.scanSources(DevModeClassLoader.java:202)
	at act.app.DevModeClassLoader.scan(DevModeClassLoader.java:93)
	at act.app.App.scanAppCodes(App.java:1270)
	at act.app.App.refresh(App.java:562)
	at act.app.AppManager.load(AppManager.java:83)
	at act.app.AppManager$_F$1.visit(AppManager.java:155)
	at act.app.AppManager$_F$1.visit(AppManager.java:151)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at act.app.AppScanner.scan(AppScanner.java:94)
	at act.app.AppScanner.scan(AppScanner.java:74)
	at act.app.AppManager.loadSingleApp(AppManager.java:61)
	at act.Act.start(Act.java:319)
	at act.Act.startApp(Act.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at act.boot.app.RunApp.start(RunApp.java:84)
	at act.Act.start(Act.java:613)
	at tanqimin.AppEntry.main(AppEntry.java:32)
```

**Comment by greenlaw110** [comment]
This is caused by https://github.com/actframework/act-asm/issues/1
