### ISSUE TITLE
Error enhancing sender method using chained call on `MailerContext`

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#308]
Java source:

```java
    @OnEvent
    public void sendHi() {
        mailer().to("someone@gmail.com")
                .from("someone@hotmail.com")
                .subject("Hi")
                .send();
    }
```

Error stack:

```
Caused by: java.lang.NullPointerException: null
	at act.mail.bytecode.SenderEnhancer$Transformer$InvocationHandler.injectCreatingMailerContextCode(SenderEnhancer.java:233)
	at act.mail.bytecode.SenderEnhancer$Transformer$InvocationHandler.handle(SenderEnhancer.java:180)
	at act.mail.bytecode.SenderEnhancer$Transformer$Segment.handle(SenderEnhancer.java:159)
	at act.mail.bytecode.SenderEnhancer$Transformer.doIt(SenderEnhancer.java:111)
	at act.mail.bytecode.SenderEnhancer.transform(SenderEnhancer.java:88)
	at act.mail.bytecode.SenderEnhancer.visitEnd(SenderEnhancer.java:82)
	at act.asm.MethodVisitor.visitEnd(MethodVisitor.java:877)
	at act.asm.ClassReader.readMethod(ClassReader.java:1038)
	at act.asm.ClassReader.accept(ClassReader.java:697)
	at act.asm.ClassReader.accept(ClassReader.java:506)
	at act.app.AppClassLoader.asmEnhance(AppClassLoader.java:497)
	at act.app.AppClassLoader.enhance(AppClassLoader.java:481)
	at act.app.AppClassLoader.loadAppClass(AppClassLoader.java:458)
	at act.app.AppClassLoader.loadClass(AppClassLoader.java:233)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.osgl.Osgl.classForName(Osgl.java:5367)
	at act.event.meta.SimpleEventListenerMetaInfo.convert(SimpleEventListenerMetaInfo.java:126)
	at act.event.meta.SimpleEventListenerMetaInfo$1.run(SimpleEventListenerMetaInfo.java:78)
	at act.job._Job$2.apply(_Job.java:310)
	at act.job._Job.doJob(_Job.java:272)
	at act.job._Job.run(_Job.java:212)
	at act.job._Job$LockableJobList.runSubJobs(_Job.java:91)
	at act.job._Job$LockableJobList.runSubJobs(_Job.java:72)
	at act.job._Job.runPrecedenceJobs(_Job.java:287)
	at act.job._Job.run(_Job.java:207)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:332)
	at act.event.EventBus.callOn(EventBus.java:233)
	at act.event.EventBus.callOn(EventBus.java:257)
	at act.event.EventBus.callOn(EventBus.java:278)
	at act.event.EventBus.emit(EventBus.java:302)
	at act.event.EventBus.emit(EventBus.java:287)
	at act.app.App.emit(App.java:889)
	at act.app.App.refresh(App.java:610)
	at act.app.AppManager.load(AppManager.java:83)
	at act.app.AppManager$_F$1.visit(AppManager.java:155)
	at act.app.AppManager$_F$1.visit(AppManager.java:151)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2226)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2216)
	at act.app.AppScanner.scan(AppScanner.java:94)
	at act.app.AppScanner.scan(AppScanner.java:74)
	at act.app.AppManager.loadSingleApp(AppManager.java:61)
	at act.Act.start(Act.java:319)
	at act.Act.startApp(Act.java:290)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at act.boot.app.RunApp.start(RunApp.java:84)
	at act.Act.start(Act.java:613)
```

**Comment by greenlaw110** [comment]
Note for the same method without `OnEvent` annotation there is not such issue:

```java
    public void sendHi(HiEvent hi) {
        mailer().to("someone@gmail.com")
                .from("someone@hotmail.com")
                .subject(hi.source())
                .send();
    }
```
