### ISSUE TITLE
Template not found in `prod` mode

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#346]
The app works in `dev` mode, however it looks like cannot locate template resource when running in `prod` mode:

```
2017-08-21 12:04:35,885 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-2] - Error handling request: [GET] /admin/login
org.osgl.exception.UnsupportedException: Template[/admin/login] not found
	at org.osgl.util.E.unsupport(E.java:153)
	at act.view.RenderAny.apply(RenderAny.java:107)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:284)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:208)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1303)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:150)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by greenlaw110** [comment]
The root cause is it caches the template probe result (not found) in the first time and the controller updated template path inside the handler method which is not respected

**Comment by greenlaw110** [comment]
A more interesting thing is if the handler logic choose different template based on different conditions (e.g. request parameters etc), then cached template get staling immediately. We need to provide a mechanism to allow developer to address this case
