### ISSUE TITLE
 invalid LOC header (bad signature)

### ISSUE THREAD

**Issue by z589533** [actframework/actframework#358]
```
Exception in thread "main" org.osgl.exception.UnexpectedIOException: java.util.zip.ZipException: invalid LOC header (bad signature)
	at org.osgl.util.E.ioException(E.java:115)
	at org.osgl.util.IO.copy(IO.java:605)
	at org.osgl.util.IO.copy(IO.java:583)
	at act.util.Jars.getBytes(Jars.java:157)
	at act.util.Jars$F$1.apply(Jars.java:188)
	at act.util.Jars$F$1.apply(Jars.java:183)
	at act.util.Jars.scanFile(Jars.java:141)
	at act.util.Jars.scanList(Jars.java:103)
	at act.util.Jars.buildClassNameIndex(Jars.java:66)
	at act.util.Jars.buildClassNameIndex(Jars.java:60)
	at act.boot.app.FullStackAppBootstrapClassLoader.buildIndex(FullStackAppBootstrapClassLoader.java:292)
	at act.boot.app.FullStackAppBootstrapClassLoader.preload(FullStackAppBootstrapClassLoader.java:120)
	at act.boot.app.FullStackAppBootstrapClassLoader.<init>(FullStackAppBootstrapClassLoader.java:81)
	at act.boot.app.RunApp.start(RunApp.java:77)
	at act.boot.app.RunApp.start(RunApp.java:60)
	at testapp.TestApp.main(TestApp.java:35)
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.osgl.util.IO.copy(IO.java:599)
	... 14 more
```

**Comment by z589533** [comment]
运行了testapp的代码和我自己写的都说加载不了jar，jdk8，act1.4.10

**Comment by greenlaw110** [comment]
@z589533 你试试删除本地的 maven repository ($HOME/.m2/repository),然后重新运行一下 `mvn package`

**Comment by z589533** [comment]
我已经删除过了

**Comment by greenlaw110** [comment]
你能不能在这里放一个断点:
![image](https://user-images.githubusercontent.com/216930/29906516-e7567f5e-8e58-11e7-88fb-55d96689a0d2.png)

看看是那个 jar 文件出错的

**Comment by z589533** [comment]
等会，我把项目提一下

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/29907094-1019f284-8e4c-11e7-8ae7-8d1e5fcdbab3.png)
看不见

**Comment by greenlaw110** [comment]
在你的 debugger frames 里面回退到前面几个 frame 来看啊:
![image](https://user-images.githubusercontent.com/216930/29907129-007307b0-8e5d-11e7-8698-9c4bad248d63.png)

**Comment by greenlaw110** [comment]
你的断点捕获到之后在 debugger 的 frames 里面回退到这里来看:
![image](https://user-images.githubusercontent.com/216930/29907203-5444d404-8e5d-11e7-8627-c957b0cebb18.png)

**Comment by z589533** [comment]
现在是不提供spring boot那种打包的插件吗？直接打成一个整体的jar

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/29909125-07e1519c-8e57-11e7-974b-1b5f0606e0b2.png)
![image](https://user-images.githubusercontent.com/12063612/29909131-0ee17a80-8e57-11e7-9328-08e17ff44664.png)
需要看那个Frames或者threads

**Comment by greenlaw110** [comment]
![image](https://user-images.githubusercontent.com/216930/29909186-0faa5746-8e68-11e7-9ec7-53675da4337f.png)

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/29909283-c8df33a0-8e57-11e7-82dc-c763c034ba4d.png)

**Comment by greenlaw110** [comment]
![image](https://user-images.githubusercontent.com/216930/29909339-befbb7e4-8e68-11e7-97a2-a59cfbd1c366.png)

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/29909510-cf380aa0-8e58-11e7-89f1-b39c289e17bb.png)

**Comment by greenlaw110** [comment]
不是 thread,是 Frame 里面:
![image](https://user-images.githubusercontent.com/216930/29909559-ccf75a5a-8e69-11e7-95f9-5032b7eac3dd.png)

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/29909599-406bd8f0-8e59-11e7-9899-7b6573ed1b34.png)
E:\maven\jars\org\jboss\logging\jboss-logging\3.2.1.Final\jboss-logging-3.2.1.Final.jar
这个有啥问题？你意思我删了再试试

**Comment by z589533** [comment]
删了，就启动了jboss-logging-3.2.1.Final.jar怎么会出问题，神了

**Comment by greenlaw110** [comment]
不知道这个包有啥问题. 这个是 undertow 的依赖包,目前就只有你一个人遇到这个问题

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/29909718-c99de1e0-8e59-11e7-8436-71023eb4ff4f.png)
![image](https://user-images.githubusercontent.com/12063612/29909726-d48c70d0-8e59-11e7-820e-58fc9ab1367a.png)

**Comment by greenlaw110** [comment]
虽然启动了,但是还是会出麻烦,因为 Undertow (Act 的网络层)依赖这个包

**Comment by greenlaw110** [comment]
刚刚那个问题是你没有下载到 act-1.4.8

**Comment by z589533** [comment]
undertow 我知道我在用，但是没出现过这个事，还有hellword的demo也不行，说找不到类，而且act包不管什么版本引用都会标红，是为啥

**Comment by z589533** [comment]
下载到了jar包
![image](https://user-images.githubusercontent.com/12063612/29909821-30625b72-8e5a-11e7-8dba-a95baa62c1dc.png)
![image](https://user-images.githubusercontent.com/12063612/29909826-345bd2f8-8e5a-11e7-97ea-f81c2aeafc3c.png)
每个版本的包我都用

**Comment by greenlaw110** [comment]
就是 maven 下载包的问题. 你可以到 QQ 群(283919975)里, 国内有其他用户也遇到过这样的问题,你咨询一下他们吧.

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/29909846-485daad8-8e5a-11e7-941d-ea97e274d840.png)
这是那个act-demo-apps的例子，还不是testapp的例子

**Comment by greenlaw110** [comment]
那你在 Intellij IDEA 里面按 ctrl-shift-a ,然后输入 reimport All maven project
![image](https://user-images.githubusercontent.com/216930/29909889-293c6728-8e6b-11e7-8347-c8aad46ff306.png)

**Comment by greenlaw110** [comment]
`testapp` 不是给用户使用的,是我用来对 act 框架做 e2e 测试用的

**Comment by z589533** [comment]
已经刷了很多次了，不行，jar阿里云的有问题？

**Comment by greenlaw110** [comment]
这个真的不知道了,你还是去群里问问吧. 我在国外,不了解情况

**Comment by z589533** [comment]
好的，谢谢
