### ISSUE TITLE
`Cannot find out Dao for model type[class act.db.ModelBase]` issue

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#386]
With the following give code:

```java
@PrePersist
private void updateVersion() {
    Page.Service pageDao = Page.dao();  // the error line
    List<Page> pages = new ArrayList<>();
    for (String pageId : this.pages) {
        pages.add(pageDao.findById(pageId));
    }
    version = VersionUtil.getVersion(name.hashCode(), pages);
}
```

It raised `IllegalArgumentException` at the error line:

```
Caused by: java.lang.IllegalArgumentException: Cannot find out Dao for model type[class act.db.ModelBase]: unable to identify the ID type
	at org.osgl.util.E.illegalArgumentIf(E.java:249)
	at act.db.morphia.MorphiaService.defaultDao(MorphiaService.java:133)
	at act.app.DbServiceManager.dao(DbServiceManager.java:174)
	at act.db.ModelBase.dao(ModelBase.java:76)
	at com.macquarie.lbb.Chapter.updateVersion(Chapter.java:65)
	... 25 common frames omitted
```

**Comment by greenlaw110** [comment]
The reason is there is no entity annotation tagged on the entity class `Page`.

It suggest produce better error message to help developer easier to address the root cause

**Comment by greenlaw110** [comment]
Fixed. Now we get better error message:

![image](https://user-images.githubusercontent.com/216930/30840505-029ad51e-a2bb-11e7-89cb-b1d8cf7d1e40.png)
