### ISSUE TITLE
Cannot inject `AppCrypto`

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#403]
Java source:

```java
@Singleton
public static class Dao extends MorphiaDao<XyzModel>  {
    @Inject
    private AppCrypto crypto;
    ...
}
```

When app started it report the error:

```
Caused by: java.lang.NoSuchMethodException: act.app.util.AppCrypto.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.osgl.inject.Genie.buildFieldMethodInjector(Genie.java:988)
```

**Comment by greenlaw110** [comment]
Not an issue, caused by bad scanning package
