### ISSUE TITLE
Exception with interceptor on base class

### ISSUE THREAD

**Issue by ttbadr** [actframework/actframework#433]
The base class with interceptor:

```java
public class BaseController extends Controller.Util {

    @Inject
    protected SysUserService sysUserService;

    @Before
    void checkAuthentication(ActionContext context) {
        ...
    }

}
```

The controller class that extends the base class:

```java
@Controller("/admin")
public class LoginController extends BaseController {
    @PostAction("login")
    public void login(String name, String password, ActionContext context) {
       ...
    }
}
```

Exception stack while starting the app:

```
19:35:07.509 INFO  a.a.App(61) - App[admin] loaded in 3090ms
19:35:07.557 INFO  a.Act(61) - start compiling API book
19:35:07.658 WARN  a.j.Job(81) - error executing job compile-api-book
org.osgl.exception.UnexpectedException: java.lang.NoSuchMethodException: com.ttb.admin.controller.LoginController.checkAuthentication(act.app.ActionContext)
	at org.osgl.util.E.unexpected(E.java:120) ~[osgl-tool-1.4.4.jar:?]
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:143) ~[act-1.5.3.jar:?]
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createBeforeInterceptor(ReflectedHandlerInvoker.java:737) ~[act-1.5.3.jar:?]
	at act.Act$Mode.createBeforeInterceptor(Act.java:153) ~[act-1.5.3.jar:?]
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:410) ~[act-1.5.3.jar:?]
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:315) ~[act-1.5.3.jar:?]
	at act.handler.builtin.controller.RequestHandlerProxy.actionHandler(RequestHandlerProxy.java:167) ~[act-1.5.3.jar:?]
	at act.apidoc.Endpoint.explore(Endpoint.java:262) ~[act-1.5.3.jar:?]
	at act.apidoc.Endpoint.<init>(Endpoint.java:193) ~[act-1.5.3.jar:?]
	at act.apidoc.ApiManager$2.visit(ApiManager.java:94) ~[act-1.5.3.jar:?]
	at act.route.Router.visit(Router.java:182) ~[act-1.5.3.jar:?]
	at act.route.Router.visit(Router.java:188) ~[act-1.5.3.jar:?]
	at act.route.Router.visit(Router.java:188) ~[act-1.5.3.jar:?]
	at act.route.Router.accept(Router.java:169) ~[act-1.5.3.jar:?]
	at act.apidoc.ApiManager.load(ApiManager.java:90) ~[act-1.5.3.jar:?]
	at act.apidoc.ApiManager.load(ApiManager.java:81) ~[act-1.5.3.jar:?]
	at act.apidoc.ApiManager$1.run(ApiManager.java:65) ~[act-1.5.3.jar:?]
	at act.job.Job$3.apply(Job.java:351) ~[act-1.5.3.jar:?]
	at act.job.Job.doJob(Job.java:313) ~[act-1.5.3.jar:?]
	at act.job.Job.run(Job.java:250) [act-1.5.3.jar:?]
	at act.job.Job$LockableJobList$1.run(Job.java:91) [act-1.5.3.jar:?]
	at act.job.AppJobManager$ContextualJob$1.apply(AppJobManager.java:431) [act-1.5.3.jar:?]
	at act.job.Job.doJob(Job.java:313) [act-1.5.3.jar:?]
	at act.job.Job.run(Job.java:250) [act-1.5.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511) [?:1.8.0_92]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NoSuchMethodException: com.ttb.admin.controller.LoginController.checkAuthentication(act.app.ActionContext)
	at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_92]
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:141) ~[act-1.5.3.jar:?]
	... 31 more
```

**Note** the issue is found on `act-1.5.3`

**Comment by greenlaw110** [comment]
@ttbadr 能不错误栈贴上来吗?

**Comment by ttbadr** [comment]
```shell
19:35:07.509 INFO  a.a.App(61) - App[admin] loaded in 3090ms
19:35:07.557 INFO  a.Act(61) - start compiling API book
19:35:07.658 WARN  a.j.Job(81) - error executing job compile-api-book
org.osgl.exception.UnexpectedException: java.lang.NoSuchMethodException: com.ttb.admin.controller.LoginController.checkAuthentication(act.app.ActionContext)
	at org.osgl.util.E.unexpected(E.java:120) ~[osgl-tool-1.4.4.jar:?]
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:143) ~[act-1.5.3.jar:?]
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createBeforeInterceptor(ReflectedHandlerInvoker.java:737) ~[act-1.5.3.jar:?]
	at act.Act$Mode.createBeforeInterceptor(Act.java:153) ~[act-1.5.3.jar:?]
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:410) ~[act-1.5.3.jar:?]
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:315) ~[act-1.5.3.jar:?]
	at act.handler.builtin.controller.RequestHandlerProxy.actionHandler(RequestHandlerProxy.java:167) ~[act-1.5.3.jar:?]
	at act.apidoc.Endpoint.explore(Endpoint.java:262) ~[act-1.5.3.jar:?]
	at act.apidoc.Endpoint.<init>(Endpoint.java:193) ~[act-1.5.3.jar:?]
	at act.apidoc.ApiManager$2.visit(ApiManager.java:94) ~[act-1.5.3.jar:?]
	at act.route.Router.visit(Router.java:182) ~[act-1.5.3.jar:?]
	at act.route.Router.visit(Router.java:188) ~[act-1.5.3.jar:?]
	at act.route.Router.visit(Router.java:188) ~[act-1.5.3.jar:?]
	at act.route.Router.accept(Router.java:169) ~[act-1.5.3.jar:?]
	at act.apidoc.ApiManager.load(ApiManager.java:90) ~[act-1.5.3.jar:?]
	at act.apidoc.ApiManager.load(ApiManager.java:81) ~[act-1.5.3.jar:?]
	at act.apidoc.ApiManager$1.run(ApiManager.java:65) ~[act-1.5.3.jar:?]
	at act.job.Job$3.apply(Job.java:351) ~[act-1.5.3.jar:?]
	at act.job.Job.doJob(Job.java:313) ~[act-1.5.3.jar:?]
	at act.job.Job.run(Job.java:250) [act-1.5.3.jar:?]
	at act.job.Job$LockableJobList$1.run(Job.java:91) [act-1.5.3.jar:?]
	at act.job.AppJobManager$ContextualJob$1.apply(AppJobManager.java:431) [act-1.5.3.jar:?]
	at act.job.Job.doJob(Job.java:313) [act-1.5.3.jar:?]
	at act.job.Job.run(Job.java:250) [act-1.5.3.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511) [?:1.8.0_92]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_92]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.NoSuchMethodException: com.ttb.admin.controller.LoginController.checkAuthentication(act.app.ActionContext)
	at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_92]
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:141) ~[act-1.5.3.jar:?]
	... 31 more
```

**Comment by greenlaw110** [comment]
我知道了,你的 `checkAuthentication` 必须是 `public` 的才行

**Comment by greenlaw110** [comment]
@ttbadr let me know if changing `checkAuthentication` to `public` works for you.
