### ISSUE TITLE
rythm extends

### ISSUE THREAD

**Issue by d925529** [actframework/actframework#436]
例子使用[http://fiddle.rythmengine.org/#/editor/6dce16866b7b4fbdb4d0095f17c296eb](http://fiddle.rythmengine.org/#/editor/6dce16866b7b4fbdb4d0095f17c296eb)

**main.html**

```
@args(){
  String name
}
@extends(aaa, title: "后台管理系统",desc = "描述")
@section (head) {
	main's head,main's @name
}
this is main's body
@section (script) {
	main's script
}
```

**aaa.html**

```
@args(){
    String title,
    String desc
}
@bbb(title,desc)
@render(head){}
@render()
@render(script) { }
```

**bbb.html**

```
@args(){
 String title,
 String desc
}

@title
@desc
```

在线运行得到结果:

```
后台管理系统
描述
main's head,main's velocity

this is main's body
main's script
```

但是在`act-1.6.0-RC2`中出现：

` java.lang.ClassCastException: java.lang.String cannot be cast to org.osgl.http.H$Flash`

**源码**
```
_flash = __safeCast(v, org.osgl.http.H.Flash.class);
```

**错误栈**
```
at pro_my_project_code_craft_src_main_resources_rythm_meta_html__R_T_C__.__setRenderArg(pro_my_project_code_craft_src_main_resources_rythm_meta_html__R_T_C__.java:166)
at pro_my_project_code_craft_src_main_resources_rythm_meta_html__R_T_C__.__setRenderArg(pro_my_project_code_craft_src_main_resources_rythm_meta_html__R_T_C__.java:1)
at org.rythmengine.RythmEngine.invokeTemplate(RythmEngine.java:1768)
at org.rythmengine.template.TemplateBase.__invokeTag(TemplateBase.java:190)
at pro_my_project_code_craft_src_main_resources_rythm_emptyLayout_html__R_T_C__.build(pro_my_project_code_craft_src_main_resources_rythm_emptyLayout_html__R_T_C__.java:265)
at org.rythmengine.template.TemplateBase.__internalBuild(TemplateBase.java:740)
at org.rythmengine.template.TemplateBase.__internalRender(TemplateBase.java:771)
at org.rythmengine.template.TemplateBase.render(TemplateBase.java:588)
at org.rythmengine.template.TemplateBase.__internalRender(TemplateBase.java:778)
at org.rythmengine.template.TemplateBase.render(TemplateBase.java:588)
```

**Comment by greenlaw110** [comment]
Fixed and verified by https://github.com/greenlaw110/act-projects/tree/master/gh436
