### ISSUE TITLE
Job method in an embedded class cause app failed to start

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#44]
Stacktrace:

```
Exception in thread "main" org.osgl.exception.UnexpectedException: Unknown error captured starting the application
        at org.osgl.util.E.unexpected(E.java:127)
        at act.boot.app.RunApp.start(RunApp.java:66)
        at act.boot.app.RunApp.start(RunApp.java:32)
        at com.p.c.Conn.main(Conn.java:20)
Caused by: java.lang.NoClassDefFoundError: com/p/c/model/NotificationModel$DaoMethodAccess (wrong name: com/p/c/model/NotificationModel)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at act.app.AppClassLoader.loadAppClass(AppClassLoader.java:379)
        at act.app.AppClassLoader.loadClass(AppClassLoader.java:181)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at com.esotericsoftware.reflectasm.AccessClassLoader.loadClass(AccessClassLoader.java:79)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.esotericsoftware.reflectasm.MethodAccess.get(MethodAccess.java:99)
        at act.job.bytecode.ReflectedJobInvoker.init(ReflectedJobInvoker.java:48)
        at act.job.bytecode.ReflectedJobInvoker.apply(ReflectedJobInvoker.java:63)
        at act.job._Job.doJob(_Job.java:200)
        at act.job._Job.run(_Job.java:162)
        at act.job._Job.runFollowingJobs(_Job.java:215)
        at act.job._Job.run(_Job.java:194)
        at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:252)
        at act.event.EventBus.callOn(EventBus.java:203)
        at act.event.EventBus.callOn(EventBus.java:227)
        at act.event.EventBus.callOn(EventBus.java:248)
        at act.event.EventBus.emit(EventBus.java:269)
        at act.event.EventBus.emit(EventBus.java:257)
        at act.app.App.emit(App.java:582)
        at act.app.App.refresh(App.java:334)
        at act.app.AppManager.load(AppManager.java:50)
        at act.app.AppManager$_F$1.visit(AppManager.java:115)
        at act.app.AppManager$_F$1.visit(AppManager.java:112)
        at org.osgl.Osgl$Visitor.apply(Osgl.java:2227)
        at org.osgl.Osgl$Visitor.apply(Osgl.java:2217)
        at act.app.AppScanner.scan(AppScanner.java:74)
        at act.app.AppScanner.scan(AppScanner.java:54)
        at act.app.AppManager.loadSingleApp(AppManager.java:28)
        at act.Act.start(Act.java:244)
        at act.Act.startApp(Act.java:218)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at act.boot.app.RunApp.start(RunApp.java:60)
```

**Comment by greenlaw110** [comment]
Not this happens only when it runs in PROD mode. Running app in DEV mode doesn't have the issue
