### ISSUE TITLE
if use multiple datasource,throw class registered  warning/error when app start 

### ISSUE THREAD

**Issue by d925529** [actframework/actframework#468]
```
org.osgl.inject.InjectException: Provider has already registered for spec: interface com.mk.cloud.domain.FrComment$Mapper
	at org.osgl.inject.Genie.addIntoRegistry(Genie.java:758)
	at org.osgl.inject.Genie.addIntoRegistry(Genie.java:771)
	at org.osgl.inject.Genie.bindProviderToClass(Genie.java:716)
	at org.osgl.inject.Genie.registerProvider(Genie.java:612)
	at org.osgl.inject.Genie.registerProvider(Genie.java:607)
	at act.db.beetlsql.BeetlSqlService.prepareMapperClass(BeetlSqlService.java:103)
	at act.db.beetlsql.BeetlClassFinder.foundMapper(BeetlClassFinder.java:60)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Osgl.invokeMethod(Osgl.java:6051)
	at org.osgl.Osgl.invokeVirtual(Osgl.java:5957)
	at act.util.ClassFinderData$By$3.visit(ClassFinderData.java:101)
	at act.util.ClassFinderData$By$3.visit(ClassFinderData.java:84)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2246)
	at org.osgl.Osgl$14.visit(Osgl.java:2344)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2246)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2236)
	at act.util.ClassNode.visitTree(ClassNode.java:173)
	at act.util.ClassNode.visitSubTree(ClassNode.java:180)
	at act.util.ClassNode.visitSubTree(ClassNode.java:220)
	at act.util.ClassNode.visitSubTree(ClassNode.java:233)
	at act.util.ClassFinderData$By$2.tryFind(ClassFinderData.java:65)
	at act.util.ClassFinderData$By.find(ClassFinderData.java:105)
	at act.util.ClassFinderData$1.run(ClassFinderData.java:203)
	at act.job.Job$4.apply(Job.java:378)
	at act.job.Job.doJob(Job.java:340)
	at act.job.Job.run(Job.java:277)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:98)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:79)
	at act.job.Job.runPrecedenceJobs(Job.java:355)
	at act.job.Job.run(Job.java:272)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:414)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.callOn(EventBus.java:256)
	at act.event.EventBus.callOn(EventBus.java:277)
	at act.event.EventBus.emit(EventBus.java:305)
	at act.event.EventBus.emit(EventBus.java:294)
	at act.app.App.emit(App.java:971)
	at act.app.App$3.run(App.java:665)
	at act.job.Job$4.apply(Job.java:378)
	at act.job.Job.doJob(Job.java:340)
	at act.job.Job.run(Job.java:277)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:98)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:79)
	at act.job.Job.runPrecedenceJobs(Job.java:355)
	at act.job.Job.run(Job.java:272)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:414)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.callOn(EventBus.java:256)
	at act.event.EventBus.callOn(EventBus.java:277)
	at act.event.EventBus.emit(EventBus.java:305)
	at act.event.EventBus.emit(EventBus.java:294)
	at act.app.App.emit(App.java:971)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:127)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:121)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.callOn(EventBus.java:256)
	at act.event.EventBus.callOn(EventBus.java:282)
	at act.event.EventBus.emit(EventBus.java:391)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:111)
	at act.db.sql.SqlDbService$1.on(SqlDbService.java:77)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.access$100(EventBus.java:49)
	at act.event.EventBus$2.run(EventBus.java:264)
	at act.job.AppJobManager$ContextualJob$1.apply(AppJobManager.java:461)
	at act.job.Job.doJob(Job.java:340)
	at act.job.Job.run(Job.java:277)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

```
java.lang.IllegalStateException: job already registered: daemon-keeper
	at org.osgl.util.E.illegalStateIf(E.java:267)
	at act.job.AppJobManager.addJob(AppJobManager.java:373)
	at act.job.Job.<init>(Job.java:169)
	at act.job.Job.of(Job.java:375)
	at act.job.Job.multipleTimes(Job.java:401)
	at act.job.AppJobManager.fixedDelay(AppJobManager.java:179)
	at act.app.App$5.run(App.java:1052)
	at act.job.Job$4.apply(Job.java:378)
	at act.job.Job.doJob(Job.java:340)
	at act.job.Job.run(Job.java:277)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:98)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:79)
	at act.job.Job.runPrecedenceJobs(Job.java:355)
	at act.job.Job.run(Job.java:272)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:414)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.callOn(EventBus.java:256)
	at act.event.EventBus.callOn(EventBus.java:277)
	at act.event.EventBus.emit(EventBus.java:305)
	at act.event.EventBus.emit(EventBus.java:294)
	at act.app.App.emit(App.java:971)
	at act.app.App$3.run(App.java:667)
	at act.job.Job$4.apply(Job.java:378)
	at act.job.Job.doJob(Job.java:340)
	at act.job.Job.run(Job.java:277)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:98)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:79)
	at act.job.Job.runPrecedenceJobs(Job.java:355)
	at act.job.Job.run(Job.java:272)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:414)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.callOn(EventBus.java:256)
	at act.event.EventBus.callOn(EventBus.java:277)
	at act.event.EventBus.emit(EventBus.java:305)
	at act.event.EventBus.emit(EventBus.java:294)
	at act.app.App.emit(App.java:971)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:127)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:121)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.callOn(EventBus.java:256)
	at act.event.EventBus.callOn(EventBus.java:282)
	at act.event.EventBus.emit(EventBus.java:391)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:111)
	at act.db.sql.SqlDbService$1.on(SqlDbService.java:77)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.access$100(EventBus.java:49)
	at act.event.EventBus$2.run(EventBus.java:264)
	at act.job.AppJobManager$ContextualJob$1.apply(AppJobManager.java:461)
	at act.job.Job.doJob(Job.java:340)
	at act.job.Job.run(Job.java:277)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

if drop ` .act.class-registry` , will not throw these no longer

**Comment by greenlaw110** [comment]
@d925529 can you please provide a simple project demonstrate this issue?

**Comment by d925529** [comment]
@greenlaw110 
https://github.com/d925529/act-db-demo

**Comment by greenlaw110** [comment]
Not able to reproduce the `Provider has already registered for spec` issue

However I do reproduce the `job already registered: daemon-keeper` issue. The reason is the following code has been executed twice on App Start event:

![image](https://user-images.githubusercontent.com/216930/37180967-23c95b6c-237f-11e8-8571-6edc9d77eae1.png)

**Comment by d925529** [comment]
```
org.osgl.inject.InjectException: Provider has already registered for spec: interface com.mk.college.common.domain.CpMsgTemplete$Mapper
	at org.osgl.inject.Genie.addIntoRegistry(Genie.java:758)
	at org.osgl.inject.Genie.addIntoRegistry(Genie.java:771)
	at org.osgl.inject.Genie.bindProviderToClass(Genie.java:716)
	at org.osgl.inject.Genie.registerProvider(Genie.java:612)
	at org.osgl.inject.Genie.registerProvider(Genie.java:607)
	at act.db.beetlsql.BeetlSqlService.prepareMapperClass(BeetlSqlService.java:103)
	at act.db.beetlsql.BeetlClassFinder.foundMapper(BeetlClassFinder.java:60)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Osgl.invokeMethod(Osgl.java:6051)
	at org.osgl.Osgl.invokeVirtual(Osgl.java:5957)
	at act.util.ClassFinderData$By$3.visit(ClassFinderData.java:101)
	at act.util.ClassFinderData$By$3.visit(ClassFinderData.java:84)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2246)
	at org.osgl.Osgl$14.visit(Osgl.java:2344)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2246)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2236)
	at act.util.ClassNode.visitTree(ClassNode.java:173)
	at act.util.ClassNode.visitSubTree(ClassNode.java:180)
	at act.util.ClassNode.visitSubTree(ClassNode.java:220)
	at act.util.ClassNode.visitSubTree(ClassNode.java:233)
	at act.util.ClassFinderData$By$2.tryFind(ClassFinderData.java:65)
	at act.util.ClassFinderData$By.find(ClassFinderData.java:105)
	at act.util.ClassFinderData$1.run(ClassFinderData.java:203)
	at act.job.Job$4.apply(Job.java:383)
	at act.job.Job.doJob(Job.java:345)
	at act.job.Job.run(Job.java:282)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:98)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:79)
	at act.job.Job.runPrecedenceJobs(Job.java:360)
	at act.job.Job.run(Job.java:277)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:414)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.callOn(EventBus.java:256)
	at act.event.EventBus.callOn(EventBus.java:277)
	at act.event.EventBus.emit(EventBus.java:305)
	at act.event.EventBus.emit(EventBus.java:294)
	at act.app.App.emit(App.java:971)
	at act.app.App$3.run(App.java:665)
	at act.job.Job$4.apply(Job.java:383)
	at act.job.Job.doJob(Job.java:345)
	at act.job.Job.run(Job.java:282)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:98)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:79)
	at act.job.Job.runPrecedenceJobs(Job.java:360)
	at act.job.Job.run(Job.java:277)
	at act.job.AppJobManager$_AppEventListener.on(AppJobManager.java:414)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.callOn(EventBus.java:256)
	at act.event.EventBus.callOn(EventBus.java:277)
	at act.event.EventBus.emit(EventBus.java:305)
	at act.event.EventBus.emit(EventBus.java:294)
	at act.app.App.emit(App.java:971)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:127)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:121)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.callOn(EventBus.java:256)
	at act.event.EventBus.callOn(EventBus.java:282)
	at act.event.EventBus.emit(EventBus.java:391)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:111)
	at act.db.sql.SqlDbService$1.on(SqlDbService.java:77)
	at act.event.EventBus.callOn(EventBus.java:235)
	at act.event.EventBus.access$100(EventBus.java:49)
	at act.event.EventBus$2.run(EventBus.java:264)
	at act.job.AppJobManager$ContextualJob$1.apply(AppJobManager.java:461)
	at act.job.Job.doJob(Job.java:345)
	at act.job.Job.run(Job.java:282)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

```

也许是因为我提交的demo中没有domain\Mapper导致无法重现，现在我在demo项目中添加了一个实体类，它对应一个数据库表：`gl_area`,字段只有一个`areacode`(`varchar`) 您可以再次尝试下

**Comment by greenlaw110** [comment]
@d925529 still can't reproduce the issue. Can you try to change your act to 1.8.1-SNAPSHOT and try on your side?

```xml
<act.version>1.8.1-SNAPSHOT</act.version>
```
