### ISSUE TITLE
`NullPointerException` after app reloaded from an ASM error in dev mode

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#509]
Reproduce steps:

1. Make an ASM error, e.g. make two controller action handler method be the same name
2. Run the app, it will report the error in dev mode
3. Fix the issue by renaming one of the action handler method
4. refresh web page and then it will trigger the following error stacks:

```
java.lang.NullPointerException: null
	at act.app.ActionContext.resolveSession(ActionContext.java:1145)
	at act.app.ActionContext.resolve(ActionContext.java:934)
	at act.route.Router$ContextualHandler.handle(Router.java:1494)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by greenlaw110** [comment]
Cause analysis:

1. App start failure at code scanning phase, raised an exception, before SessionManager is initialized.
2. developer modified the code and fixed previous issue
3. developer hit F5 to refresh
4. ActionContext initialized, get SessionManager from App, which obviously is `null`
5. ActFramework detect changes in source code, refresh app, including SessionManager initialization, however this is not get passed to the current ActionContext
6. ActionContext call SessionManager to resolve session, and you get NPE
