### ISSUE TITLE
Act does not work with Java9

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#514]
First issue is:

```
Exception in thread "main" org.osgl.exception.UnexpectedMethodInvocationException: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.osgl.exception.UnexpectedMethodInvocationException.triage(UnexpectedMethodInvocationException.java:44)
	at org.osgl.Osgl.invokeStatic(Osgl.java:5948)
	at act.Act.bootstrap(Act.java:913)
	at act.Act.start(Act.java:569)
	at demo.helloworld.HelloWorldApp.main(HelloWorldApp.java:128)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.apache.bval.jsr.ConfigurationImpl.parseValidationXml(ConfigurationImpl.java:357)
	at org.apache.bval.jsr.ConfigurationImpl.createBootstrapConfiguration(ConfigurationImpl.java:349)
	at org.apache.bval.jsr.ConfigurationImpl.prepare(ConfigurationImpl.java:340)
	at org.apache.bval.jsr.ConfigurationImpl.__privileged_doBuildValidatorFactory(ConfigurationImpl.java:329)
	at org.apache.bval.jsr.ConfigurationImpl.doBuildValidatorFactory(ConfigurationImpl.java)
	at org.apache.bval.jsr.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:324)
	at act.validation.ValidationPlugin.ensureFactoryValidator(ValidationPlugin.java:56)
	at act.validation.ValidationPlugin.init(ValidationPlugin.java:48)
	at act.validation.ValidationPlugin.applyTo(ValidationPlugin.java:41)
	at act.plugin.AppServicePluginManager.applyTo(AppServicePluginManager.java:43)
	at act.app.App.loadGlobalPlugin(App.java:1310)
	at act.app.App.refresh(App.java:619)
	at act.app.AppManager.load(AppManager.java:77)
	at act.app.AppManager$_F$1.visit(AppManager.java:145)
	at act.app.AppManager$_F$1.visit(AppManager.java:141)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2246)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2236)
	at act.app.AppScanner.scan(AppScanner.java:91)
	at act.app.AppScanner.scan(AppScanner.java:71)
	at act.app.AppManager.loadSingleApp(AppManager.java:55)
	at act.Act.startup(Act.java:306)
	at act.Act.startup(Act.java:1006)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.osgl.Osgl.invokeStatic(Osgl.java:5946)
```

**Comment by greenlaw110** [comment]
This is superseded by #1342
