### ISSUE TITLE
testapp apidoc error

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#519]
Running [testapp](https://github.com/actframework/actframework/tree/master/testapp) it will print out the following error log:

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.osgl.util.ImmutableList.get(ImmutableList.java:143)
	at act.apidoc.Endpoint.generateSampleQuery(Endpoint.java:427)
	at act.apidoc.Endpoint.generateSampleQuery(Endpoint.java:448)
	at act.apidoc.Endpoint.exploreParamInfo(Endpoint.java:328)
	at act.apidoc.Endpoint.explore(Endpoint.java:270)
	at act.apidoc.Endpoint.<init>(Endpoint.java:193)
	at act.apidoc.ApiManager$2.visit(ApiManager.java:94)
	at act.route.Router.visit(Router.java:190)
	at act.route.Router.visit(Router.java:196)
	at act.route.Router.visit(Router.java:196)
	at act.route.Router.accept(Router.java:177)
	at act.apidoc.ApiManager.load(ApiManager.java:90)
	at act.apidoc.ApiManager.load(ApiManager.java:81)
	at act.apidoc.ApiManager$1.run(ApiManager.java:65)
	at act.job.Job$4.apply(Job.java:383)
	at act.job.Job.doJob(Job.java:345)
	at act.job.Job.run(Job.java:282)
	at act.job.Job$LockableJobList$1.run(Job.java:94)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:461)
	at act.job.Job.doJob(Job.java:345)
	at act.job.Job.run(Job.java:282)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
This is caused by [this entity model class](https://github.com/actframework/actframework/blob/master/testapp/src/main/java/testapp/endpoint/ghissues/gh446/DataTable.java#L45) defines a `List` typed field without type parameter:

```
    private List data;
```
