### ISSUE TITLE
NPE running config sample

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#524]
Act version: 1.7.0

Running https://github.com/actframework/act-demo-apps/tree/master/config got the following issue during app bootstrap:

```
2018-02-21 05:29:11,801 ERROR a.a.App@[main] - Block issue encountered
java.lang.NullPointerException: null
	at org.osgl.util.E.NPE(E.java:76)
	at org.osgl.Osgl.notNull(Osgl.java:5234)
	at org.osgl.cache.CacheServiceProvider$Impl.setClassLoader(CacheServiceProvider.java:201)
	at act.conf.AppConfig.cacheService(AppConfig.java:2489)
	at act.handler.builtin.controller.RequestHandlerProxy.<init>(RequestHandlerProxy.java:120)
	at act.route.Router$1.resolve(Router.java:112)
	at act.route.Router.resolveActionHandler(Router.java:745)
	at act.route.Router.addMapping(Router.java:295)
	at act.route.RouteTableRouterBuilder.process(RouteTableRouterBuilder.java:166)
	at act.route.RouteTableRouterBuilder.build(RouteTableRouterBuilder.java:125)
	at act.app.App.loadRoutes(App.java:1359)
	at act.app.App.refresh(App.java:605)
	at act.app.App.refresh(App.java:553)
	at act.app.App.checkUpdates(App.java:452)
	at act.job.Job.run(Job.java:280)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:414)
	at act.event.EventBus.callOn(EventBus.java:1313)
	at act.event.EventBus.callOn(EventBus.java:1334)
	at act.event.EventBus.callOn(EventBus.java:1355)
	at act.event.EventBus._emit(EventBus.java:1226)
	at act.event.EventBus.emit(EventBus.java:679)
	at act.app.App.emit(App.java:1025)
	at act.Act.emit(Act.java:450)
	at act.Act.startup(Act.java:314)
	at act.Act.startup(Act.java:1006)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Osgl.invokeStatic(Osgl.java:5946)
	at act.Act.bootstrap(Act.java:913)
	at act.Act.start(Act.java:569)
	at demo.config.ConfigDemo.main(ConfigDemo.java:56)
Exception in thread "main" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at act.event.EventBus.callOn(EventBus.java:1332)
	at act.event.EventBus.callOn(EventBus.java:1355)
	at act.event.EventBus._emit(EventBus.java:1226)
	at act.event.EventBus.emit(EventBus.java:679)
	at act.app.App.emit(App.java:1025)
	at act.Act.emit(Act.java:450)
	at act.Act.startup(Act.java:314)
	at act.Act.startup(Act.java:1006)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Osgl.invokeStatic(Osgl.java:5946)
	at act.Act.bootstrap(Act.java:913)
	at act.Act.start(Act.java:569)
	at demo.config.ConfigDemo.main(ConfigDemo.java:56)
```

**Comment by greenlaw110** [comment]
## Root cause analysis:

The `config` sample has a `routes.conf` file contains routes to action handler methods:

```
GET /hi demo.config.Extra.hi
GET /bye demo.config.Extra.bye
```

The `routes.conf` file is parsed and loaded before app classloader initialized. Unfortunately the parsed request handler will construct a `RequestHandlerProxy` instance, and from that constructor it tried to initialize cache, which needs a app classloader instance.
