### ISSUE TITLE
Cannot run a groovy program even in PROD mode

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#540]
gradle:

```gradle
group 'per.apricot'
version '1.0.0-SNAPSHOT'

apply plugin: 'groovy'
apply plugin: 'java'
apply plugin: 'application'

mainClassName = "demo.AppEntry"


sourceCompatibility = 1.8

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}

dependencies {
    compile 'org.actframework:act:1.7.3'
    compile 'org.codehaus.groovy:groovy-all:2.4.13'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

The source code:

```groovy
package demo

import act.Act
import org.osgl.mvc.annotation.GetAction

class AppEntry {

    @GetAction("/txt")
    String text() {
        'hello world'
    }

    static void main(String[] args) {
        Act.start()
    }
}
```

The error stack:

```
Exception in thread "main" org.osgl.exception.UnexpectedClassNotFoundException: act.Act$start
	at org.osgl.Osgl.classForName(Osgl.java:5414)
	at act.Act.getCallerClass(Act.java:891)
	at act.Act.start(Act.java:569)
	at act.Act$start.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at demo.AppEntry.main(AppEntry.groovy:14)
```

**Comment by bitsnaps** [comment]
Still have the issue here:
```
dependencies {
    compile 'org.slf4j:slf4j-api:1.7.22'
    compile 'org.actframework:act:1.7.3'
    compile 'org.codehaus.groovy:groovy-all:2.5.1'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```
