### ISSUE TITLE
Param binding failure on 1.8.0

### ISSUE THREAD

**Issue by ttbadr** [actframework/actframework#547]
Act version: 1.8.0

Error stack:

```
15:05:26.329 ERROR a.h.b.c.RequestHandlerProxy(116) - Error handling request: [POST] /admin/game/updateRule/list
java.lang.NullPointerException: null
	at act.inject.param.ParamValueLoaderService.buildLoader(ParamValueLoaderService.java:483) ~[act-1.8.0.jar:?]
	at act.inject.param.CollectionLoader.buildChildLoader(CollectionLoader.java:149) ~[act-1.8.0.jar:?]
	at act.inject.param.CollectionLoader.childLoader(CollectionLoader.java:142) ~[act-1.8.0.jar:?]
	at act.inject.param.CollectionLoader.load(CollectionLoader.java:129) ~[act-1.8.0.jar:?]
	at act.inject.param.FieldLoader.applyTo(FieldLoader.java:42) ~[act-1.8.0.jar:?]
	at act.inject.param.PojoLoader.load(PojoLoader.java:75) ~[act-1.8.0.jar:?]
	at act.inject.param.JsonParamValueLoader.load(JsonParamValueLoader.java:67) ~[act-1.8.0.jar:?]
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:49) ~[act-1.8.0.jar:?]
	at act.inject.param.ParamValueLoaderService.loadMethodParams(ParamValueLoaderService.java:183) ~[act-1.8.0.jar:?]
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.params(ReflectedHandlerInvoker.java:837) ~[act-1.8.0.jar:?]
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:425) ~[act-1.8.0.jar:?]
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48) ~[act-1.8.0.jar:?]
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:512) ~[act-1.8.0.jar:?]
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:202) [act-1.8.0.jar:?]
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47) [act-1.8.0.jar:?]
	at act.route.Router$ContextualHandler.handle(Router.java:1505) [act-1.8.0.jar:?]
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:155) [act-1.8.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
15:05:26.330 ERROR admin(78) - Illegal state java.lang.NullPointerException
	at act.inject.param.ParamValueLoaderService.buildLoader(ParamValueLoaderService.java:483)
	at act.inject.param.CollectionLoader.buildChildLoader(CollectionLoader.java:149)
	at act.inject.param.CollectionLoader.childLoader(CollectionLoader.java:142)
	at act.inject.param.CollectionLoader.load(CollectionLoader.java:129)
	at act.inject.param.FieldLoader.applyTo(FieldLoader.java:42)
	at act.inject.param.PojoLoader.load(PojoLoader.java:75)
	at act.inject.param.JsonParamValueLoader.load(JsonParamValueLoader.java:67)
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:49)
	at act.inject.param.ParamValueLoaderService.loadMethodParams(ParamValueLoaderService.java:183)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.params(ReflectedHandlerInvoker.java:837)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:425)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:512)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:202)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1505)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

POST parameters：

```
table[draw]:1
table[columns][0][data]:name
table[columns][0][name]:name
table[columns][0][searchable]:true
table[columns][0][orderable]:true
table[columns][0][search][value]:
table[columns][0][search][regex]:false
table[columns][1][data]:vip
table[columns][1][name]:is_vip
table[columns][1][searchable]:true
table[columns][1][orderable]:false
table[columns][1][search][value]:
table[columns][1][search][regex]:false
table[columns][2][data]:vipStartTime
table[columns][2][name]:vipStartTime
table[columns][2][searchable]:true
table[columns][2][orderable]:false
table[columns][2][search][value]:
table[columns][2][search][regex]:false
table[columns][3][data]:vipEndTime
table[columns][3][name]:vipEndTime
table[columns][3][searchable]:true
table[columns][3][orderable]:false
table[columns][3][search][value]:
table[columns][3][search][regex]:false
table[columns][4][data]:lastGoodsName
table[columns][4][name]:lastGoodsName
table[columns][4][searchable]:true
table[columns][4][orderable]:false
table[columns][4][search][value]:
table[columns][4][search][regex]:false
table[columns][5][data]:regTime
table[columns][5][name]:regTime
table[columns][5][searchable]:true
table[columns][5][orderable]:true
table[columns][5][search][value]:
table[columns][5][search][regex]:false
table[columns][6][data]:id
table[columns][6][name]:id
table[columns][6][searchable]:true
table[columns][6][orderable]:false
table[columns][6][search][value]:
table[columns][6][search][regex]:false
table[order][0][column]:0
table[order][0][dir]:asc
table[start]:0
table[length]:30
table[search][value]:
table[search][regex]:false
```

The data (POJO) class:

```java
public class DataTable {

    @Data
    public static class Search implements SimpleBean {
        public String value;
        public boolean regex;
    }

    @Data
    public static class Column implements SimpleBean {
        public String id;
        public String data;
        public String name;
        public boolean searchable;
        public boolean orderable;
        public Search search;
    }

    @Data
    public static class Order implements SimpleBean {
        public Integer column;
        public String dir;
    }

    private int draw;
    private int recordsTotal;

    private int recordsFiltered;

    private List data;

    private String error;

    private int start;
    private int length;
    private Map<String, String> search;
    private List<Column> columns;
    private List<Order> order;


    public Order getOrderProperty() {
        if (order != null && order.size() > 0) {
            return order.get(0);
        } else {
            return null;
        }
    }

    public int getStart() {
        return start;
    }

    public void setStart(int start) {
        this.start = start;
    }

    public int getLength() {
        return length;
    }

    public void setLength(int length) {
        this.length = length;
    }

    public Map<String, String> getSearch() {
        return search;
    }

    public void setSearch(Map<String, String> search) {
        this.search = search;
    }

    public List<Column> getColumns() {
        return columns;
    }

    public void setColumns(List<Column> columns) {
        this.columns = columns;
    }

    public List<Order> getOrder() {
        return order;
    }

    public void setOrder(List<Order> order) {
        this.order = order;
    }

    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public int getDraw() {
        return draw;
    }

    public void setDraw(int draw) {
        this.draw = draw;
    }

    public int getRecordsTotal() {
        return recordsTotal;
    }

    public void setRecordsTotal(int recordsTotal) {
        this.recordsTotal = recordsTotal;
    }

    public int getRecordsFiltered() {
        return recordsFiltered;
    }

    public void setRecordsFiltered(int recordsFiltered) {
        this.recordsFiltered = recordsFiltered;
    }

    public List getData() {
        return data;
    }

    public void setData(List data) {
        this.data = data;
    }
}
```

The request handler

```java
@PostAction("list")
public DataTable list(DataTable table) {
    return userService.page(table);
}
```

**Comment by greenlaw110** [comment]
Can not reproduce. 

Test case: 
https://github.com/actframework/actframework/commit/59920bc17d21860d4eb706715b6455b137f3b0db
