### ISSUE TITLE
@ResponseContentType 支持jpeg以及javascript

### ISSUE THREAD

**Issue by d925529** [actframework/actframework#552]
I need to create a js by java enum for page format:

```java
//region 用户类型
USERTYPE_0("0", "平台员工"),
USERTYPE_1("1", "用户"),
//endregion
```
so i have a method like this:

```java
@GetAction("GlobalValues.jsx")
public Result getConfigJs(H.Response response) {
    Osgl.T4 t = readConfigs();
    String Glovalues = "var GlobalValues =" + JSON.toJSONString(t._1) + ";var GlobalConfigs = " + JSON.toJSONString(t._3) + ";" + "var GlobalValues2 = " + JSON.toJSONString(t._2) + ";" + "var SysConfig = " + JSON.toJSONString(t._4) + ";";

    response.addHeader("Access-Control-Allow-Methods", "GET");
    response.addHeader("Content-Type", "application/javascript;charset=UTF-8");
    return binary(out -> {
        try {
            out.write(Glovalues.getBytes("UTF-8"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        IO.close(out);
        return null;
    });
}
```

but in `1.8.x' , `binary` is not supported,so I change the method like this

```java
@GetAction("GlobalValues.jsx")
@ResponseContentType(H.MediaType.JAVASCRIPT)
public String getConfigJs(H.Response response) {
    Osgl.T4 t = readConfigs();
    return "var GlobalValues =" + JSON.toJSONString(t._1) + ";var GlobalConfigs = " + JSON.toJSONString(t._3) + ";" + "var GlobalValues2 = " + JSON.toJSONString(t._2) + ";" + "var SysConfig = " + JSON.toJSONString(t._4) + ";";
}
```

and it still not working:

```
org.osgl.exception.UnexpectedException: Cannot apply text result to format: javascript
	at org.osgl.util.E.unexpected(E.java:177)
	at act.controller.Controller$Util.inferPrimitiveResult(Controller.java:1332)
	at act.controller.Controller$Util.inferResult(Controller.java:1446)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:799)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:452)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:512)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:202)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1505)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

In addition，I have a method for create Verification code:

```java
@GetAction("validateCode.jpegx")
public Result validatePicCode() {
    String code = V.outputVerifyImage(4);
    context.session().cacheFor30Min(AppConfig.base.pic_key.get(), code);
    return binary(out -> {
        V.outputImage(100, 36, code, out);
        IO.close(out);
        return null;
    });
}
```

in `1.8.x`,I dont know how to impl it

**Comment by greenlaw110** [comment]
@d925529  if you need to write directly to outputstream, try this:

```java
        final byte[] ba = "你好吗".getBytes(StandardCharsets.UTF_8);
        return binary(new $.Visitor<org.osgl.util.Output>() {
            @Override
            public void visit(org.osgl.util.Output out) throws Osgl.Break {
                IO.write(ba, out.asOutputStream());
            }
        });
```

**Comment by d925529** [comment]
```
return binary(out -> {
        
    });
```
**Cannot resolve method  binary(<lambda expression>)**

**Comment by greenlaw110** [comment]
@d925529 the API is:

```java
public static RenderBinary binary($.Visitor<Output> outputStreamWriter);
```

Note the visit object is `org.osgl.util.Output`, not `java.io.OutputStream`

**Comment by d925529** [comment]
it is:
```
    public Result validatePicCode() {
        String code = VerifyCodeUtils.outputVerifyImage(4);
        CookieUtil.addCookie(GlobalValues.COOKIE_KEYPICCODE.value(), code,context.resp());
        return binary(Osgl.visitor(out -> {
            VerifyCodeUtils.outputImage(100, 36, code, out.asOutputStream());
            return null;
        }));
    }
```

**Comment by greenlaw110** [comment]
@d925529  how about this?

```java
    public Result validatePicCode() {
        String code = VerifyCodeUtils.outputVerifyImage(4);
        CookieUtil.addCookie(GlobalValues.COOKIE_KEYPICCODE.value(), code,context.resp());
        return binary(out -> {
            VerifyCodeUtils.outputImage(100, 36, code, out.asOutputStream());
        });
    }
```
