### ISSUE TITLE
Random `NullPointerException` on act-1.6.6

### ISSUE THREAD

**Issue by pcmanjack** [actframework/actframework#553]
Found on act-1.6.6

Error stack:

```-03-09 12:53:39.494 [XNIO-1 task-226] ERROR a.h.b.controller.RequestHandlerProxy - Error handling request: [GET] /
java.lang.NullPointerException: null
	at org.osgl.cache.impl.SimpleCacheService$Item.compareTo(SimpleCacheService.java:105)
	at org.osgl.cache.impl.SimpleCacheService$Item.compareTo(SimpleCacheService.java:90)
	at java.util.PriorityQueue.siftUpComparable(PriorityQueue.java:657)
	at java.util.PriorityQueue.siftUp(PriorityQueue.java:648)
	at java.util.PriorityQueue.offer(PriorityQueue.java:345)
	at org.osgl.cache.impl.SimpleCacheService.put(SimpleCacheService.java:127)
	at org.osgl.cache.impl.CacheServiceBase.incr(CacheServiceBase.java:44)
	at org.osgl.cache.impl.SimpleCacheService.incr(SimpleCacheService.java:55)
	at act.controller.builtin.ThrottleFilter.handle(ThrottleFilter.java:60)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:329)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:53)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:509)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:202)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1494)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:150)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
Root cause is inside `SimpleCacheService`. See https://github.com/osglworks/java-cache/issues/2
