### ISSUE TITLE
`org.osgl.exception.UnexpectedException: Invalid event type`

### ISSUE THREAD

**Issue by d925529** [actframework/actframework#554]
Event listener:

```java
    @On(value = "message-send", async = true)
    public void send(MsgTemplate template) {
        Map<String, String> params = template.params();
        if (params == null) params = new HashMap<>();
        String sms_code = template._sms_code();
        if (S.isNotBlank(sms_code)) params.put("sms_code", sms_code);


        CpMsg cpMsg = new CpMsg();
        cpMsg.setTitle(S.stringBuild(template.title(), params));
        cpMsg.setMtime(DateUtils.formatTimeNow(DateUtils.DEFAULT_TIME_FORMAT));
        cpMsg.setMstate(GlobalValues.MSSTATE_0.value());
        cpMsg.setMsg(S.stringBuild(template.msg(), params));
        cpMsg.setMtype(template._mtype());
        cpMsg.setMurl(S.stringBuild(template.murl(), params));
        cpMsg.setPic(template.pic());
        cpMsg.setParams(params);

        int channel = template._channels();
        Set<String> phone = template.phones();
        Set<String> userid = template.userids();
        Set<String> usertype = template.usertypes();
        App app = App.instance();

        CpUser.Mapper mapper = app.getInstance(CpUser.Mapper.class);
        CpMsg.Mapper msMapper = app.getInstance(CpMsg.Mapper.class);
        //纯短信、针对系统外部人员
        if (MsgTemplate.MessChannel.SMS.isEnabled(channel) && C.notEmpty(phone)) {
            phone.forEach(p -> {
                CpMsg m = new CpMsg(cpMsg);
                m.setPhone(p);
                sms(m);
            });
        }
        //ps用户过滤条件
        Map<String, Object> ps = new HashMap<>();
        if (C.notEmpty(userid))
            ps.put("userid", userid);
        if (C.notEmpty(usertype))
            ps.put("usertype", template.usertypes());
        if (C.notEmpty(ps)) {
            List<Map> us = mapper.getSQLManager().select("user.select_contact", Map.class, ps);
            us.forEach(u -> {
                CpMsg m = new CpMsg(cpMsg);
                m.setUserid(MapUtils.getString(u, "userid"));
                m.setPhone(MapUtils.getString(u, "phone"));
                if (template._save()) msMapper.insertTemplate(m, true);
                else m.setMid("0");
                if (MsgTemplate.MessChannel.SMS.isEnabled(channel) && (C.empty(phone) || C.notEmpty(phone) && phone.add(m.getPhone())))
                    sms(m);
                if (MsgTemplate.MessChannel.APP.isEnabled(channel))
                    appPush(m);
                if(MsgTemplate.MessChannel.WEB.isEnabled(channel))
                    webPush(m);
            });
        }
    }
```

Event dispatch

``` java
    public static void excute(MsgTemplate template) {
        EventBus eventBus = App.instance().getInstance(EventBus.class);
        eventBus.trigger(GlobalValues.EVENT_SEND_MSG.value(), template);
    }
```

CpMsg

```java
@Table(name = "cp_msg")
@DB("college")
@SuppressWarnings("unused")
public class CpMsg {
    @AssignID
    private String mid ;
    //扩展参数
    private String advparams ;
    private String appid ;
    //所属企业
    private String coid ;
    //是否用于展示
    private String forshow ;
    //级别
    private String mlevel ;
    //打开页面标题
    private String mopentitle ;
    //图片
    private String mpic ;
    //消息内容
    private String msg ;
    //创建时间
    private String mtime ;
    //标题
    private String mtitle ;
    //顶级类型
    private String mtopone ;
    //打开地址
    private String murl ;
    //电话
    private String phone ;
    //它的展示消息ID
    private String pmid ;
    //是否已读
    private String readabled ;
    //阅读时间
    private String readtime ;
    //接受消息的用户id
    private String userid ;
    //模板参数
    private String wparams ;

    //标题
    private String title;
//    private String userid;
    //消息类型,随便定义,为了以后按类型查看消息的扩展
    private String mtype;
    //消息参数,json类型
    private String paramstring;
    //平台消息id
    private String mtid;
    //参数扩展
    @Transient
    private Map<String, String> params;
    //时间
//    private String mtime;
    //0=未读 1=已读 2=删除
    private String mstate;
    //图片
    private String pic;

    public CpMsg() {
    }

    public CpMsg(CpMsg msg_old) {
        setTitle(msg_old.getTitle());
        setMtime(msg_old.getMtime());
        setMstate(msg_old.getMstate());
        setMsg(msg_old.getMsg());
        setMtype(msg_old.getMtype());
        setMurl(msg_old.getMurl());
        setParams(msg_old.getParams());

        if (params != null) {
            if (S.isNotBlank(title)) params.put("mtitle", title);
            if (S.isNotBlank(murl)) params.put("murl", murl);
            if (S.isNotBlank(pic)) params.put("pic", pic);
        }
    }

    public String getMtid() {
        return mtid;
    }

    public void setMtid(String mtid) {
        this.mtid = mtid;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getMtime() {
        return mtime;
    }

    public void setMtime(String mtime) {
        this.mtime = mtime;
    }

    public String getMstate() {
        return mstate;
    }

    public void setMstate(String mstate) {
        this.mstate = mstate;
    }

    @Deprecated
    public String getParamstring() {
        return JSON.toJSONString(params);
    }

    @Deprecated
    public void setParamstring(String paramstring) {
        this.paramstring = paramstring;
        if (params != null) {
            JSONObject oo = JSON.parseObject(paramstring);
            for (Object o : oo.entrySet()) {
                Map.Entry entry = (Map.Entry) o;
                if (entry.getValue() != null) {
                    params.put(entry.getKey().toString(), entry.getValue().toString());
                }
            }
        }
    }

    public String getMtype() {
        return mtype;
    }

    public void setMtype(String mtype) {
        this.mtype = mtype;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getMid() {
        return mid;
    }

    public void setMid(String mid) {
        this.mid = mid;
        if (params != null) params.put("mid", mid.toString());
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getMurl() {
        return murl;
    }

    public void setMurl(String murl) {
        this.murl = murl;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public Map<String, String> getParams() {
        return params;
    }

    public void setParams(Map<String, String> params) {
        this.params = params;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAdvparams() {
        return advparams;
    }

    public void setAdvparams(String advparams) {
        this.advparams = advparams;
    }

    public String getAppid() {
        return appid;
    }

    public void setAppid(String appid) {
        this.appid = appid;
    }

    public String getCoid() {
        return coid;
    }

    public void setCoid(String coid) {
        this.coid = coid;
    }

    public String getForshow() {
        return forshow;
    }

    public void setForshow(String forshow) {
        this.forshow = forshow;
    }

    public String getMlevel() {
        return mlevel;
    }

    public void setMlevel(String mlevel) {
        this.mlevel = mlevel;
    }

    public String getMopentitle() {
        return mopentitle;
    }

    public void setMopentitle(String mopentitle) {
        this.mopentitle = mopentitle;
    }

    public String getMpic() {
        return mpic;
    }

    public void setMpic(String mpic) {
        this.mpic = mpic;
    }

    public String getMtitle() {
        return mtitle;
    }

    public void setMtitle(String mtitle) {
        this.mtitle = mtitle;
    }

    public String getMtopone() {
        return mtopone;
    }

    public void setMtopone(String mtopone) {
        this.mtopone = mtopone;
    }

    public String getPmid() {
        return pmid;
    }

    public void setPmid(String pmid) {
        this.pmid = pmid;
    }

    public String getReadabled() {
        return readabled;
    }

    public void setReadabled(String readabled) {
        this.readabled = readabled;
    }

    public String getReadtime() {
        return readtime;
    }

    public void setReadtime(String readtime) {
        this.readtime = readtime;
    }

    public String getWparams() {
        return wparams;
    }

    public void setWparams(String wparams) {
        this.wparams = wparams;
    }

    public interface Mapper extends BaseMapper<CpMsg> {
    }
}
```

MsgTemplate

```
public interface MsgTemplate {
    /**
     * 消息主体,短信不会直接发送此内容
     * 支持魔术字符串
     */
    String msg();

    /**
     * 路由地址
     * 支持魔术字符串
     */
    String murl();

    /**
     * 消息标题
     * 支持魔术字符串
     */
    String title();

    /**
     * 图片code
     */
    String pic();

    /**
     * 扩展参数
     */
    Map<String, String> params();


    /**
     * 指定接收电话号码，一般用于指定非系统用户
     * 系统用户直接指定userid即可
     * 当同时制定phone和userid时，都会发送，但不会重复发同样的号码
     */
    Set<String> phones();

    /**
     * 指定用户id,
     * 将会查询到这些用户的手机号码进行发送短信
     * 发送app推送
     * 发送页面推送
     */
    Set<String> userids();

    /**
     * 用户类型,参见GlobalValues.USERTYPE;
     * 用于指定哪些用户收消息
     */
    Set<String> usertypes();

    /**
     * 消息渠道
     * MessChannel.xxx.mask | MessChannel.xxx.mask
     */
    int _channels();

    /**
     * 消息类型,随便定义,为了以后按类型查看消息的扩展
     * 最好使用Glovalues
     */
    String _mtype();

    /**
     * 指定短信编码
     */
    String _sms_code();

    /**
     * 存储到数据库吗
     *
     * @return
     */
    boolean _save();


    enum MessChannel {
        SMS, APP, WEB, EMAIL;

        public final int mask;

        MessChannel() {
            mask = (1 << ordinal());
        }

        public boolean isEnabled(int channels) {
            return (channels & mask) != 0;
        }

        public boolean isNotEnabled(int channels) {
            return !isEnabled(channels);
        }
    }

}
```

Error stack:

```
2018-03-10 12:12:37,543 WARN  a.j.Job@[jobs-thread-2] - error executing job act.event.bytecode.SimpleEventListenerByteCodeScanner$1@5d43206f
org.osgl.exception.UnexpectedException: Invalid event type: class com.mk.college.common.domain.CpMsg
	at org.osgl.util.E.unexpected(E.java:177)
	at act.event.EventBus$Key.typeOf(EventBus.java:117)
	at act.event.EventBus$Key.setId(EventBus.java:103)
	at act.event.EventBus$Key.<init>(EventBus.java:73)
	at act.event.EventBus._bind(EventBus.java:1150)
	at act.event.EventBus.bind(EventBus.java:553)
	at act.event.bytecode.SimpleEventListenerByteCodeScanner$1.run(SimpleEventListenerByteCodeScanner.java:74)
	at act.job.Job$4.apply(Job.java:383)
	at act.job.Job.doJob(Job.java:345)
	at act.job.Job.run(Job.java:282)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:98)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:79)
	at act.job.Job.runPrecedenceJobs(Job.java:360)
	at act.job.Job.run(Job.java:277)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:414)
	at act.event.EventBus.callOn(EventBus.java:1313)
	at act.event.EventBus.callOn(EventBus.java:1334)
	at act.event.EventBus.callOn(EventBus.java:1355)
	at act.event.EventBus._emit(EventBus.java:1226)
	at act.event.EventBus.emit(EventBus.java:679)
	at act.app.App.emit(App.java:1031)
	at act.app.App$3.run(App.java:698)
	at act.job.Job$4.apply(Job.java:383)
	at act.job.Job.doJob(Job.java:345)
	at act.job.Job.run(Job.java:282)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:98)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:79)
	at act.job.Job.runPrecedenceJobs(Job.java:360)
	at act.job.Job.run(Job.java:277)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:414)
	at act.event.EventBus.callOn(EventBus.java:1313)
	at act.event.EventBus.callOn(EventBus.java:1334)
	at act.event.EventBus.callOn(EventBus.java:1355)
	at act.event.EventBus._emit(EventBus.java:1226)
	at act.event.EventBus.emit(EventBus.java:679)
	at act.app.App.emit(App.java:1031)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:127)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:121)
	at act.event.EventBus.callOn(EventBus.java:1313)
	at act.event.EventBus.callOn(EventBus.java:1334)
	at act.event.EventBus.callOn(EventBus.java:1360)
	at act.event.EventBus._emitWithOnceBus(EventBus.java:1286)
	at act.event.EventBus.emit(EventBus.java:847)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:111)
	at act.db.sql.SqlDbService$1.on(SqlDbService.java:77)
	at act.event.EventBus.callOn(EventBus.java:1313)
	at act.event.EventBus.access$1400(EventBus.java:53)
	at act.event.EventBus$4.run(EventBus.java:1342)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:461)
	at act.job.Job.doJob(Job.java:345)
	at act.job.Job.run(Job.java:282)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
@d925529 can you put the source code of  `GlobalValues`?

**Comment by d925529** [comment]
这个问题是因为使用`@OnEvent`定义的方法，第一个参数类型不符合规定，与框架无关

`@OnEvent`  和 `@On` 都是定义 接受事件分发的功能
`@OnEvent` 只接收方法第一个参数对应的事件分发，第一个参数可以是枚举、可以是ActEvent<T>
例如 emit(new ActEvent<X>(x))将触发 第一个参数类型是ActEvent<X>的事件分发
而`@On` 只接收string类型的事件分发
二者定义的方法，都可以是任意个数、类型的参数，但有一个问题需要注意：
举例说明：
```
@On("test-event")
public void test(String name,String uri){
}
//触发代码
EventBus.emit("test-event",null,"this is a uri")
```
这种情况下，是不会触发的
