### ISSUE TITLE
Error with sending large response: UT000043: Data is already being sent. You must wait for the completion callback to be be invoked before calling send() again

### ISSUE THREAD

**Issue by penguin290** [actframework/actframework#560]
Java source:

```java
public class TestController {
    public static class Foo implements SimpleBean {
        public String bar;
        public String blob;

        public Foo() {
            bar = S.random(5);
            blob = S.random(1024 * 1024 * 2);
        }
    }

    @GetAction("foo")
    @JsonView
    public Iterable<Foo> loadFoos() {
        final AtomicInteger counter = new AtomicInteger(200);
        return new Iterable<Foo>() {
            @Override
            public Iterator<Foo> iterator() {
                return new Iterator<Foo>() {
                    @Override
                    public boolean hasNext() {
                        return counter.decrementAndGet() > 0;
                    }

                    @Override
                    public Foo next() {
                        return new Foo();
                    }

                    @Override
                    public void remove() {
                        E.unsupport();
                    }
                };
            }
        };
    }
}
```

Sending `GET` request to `http://localhost:5406/foo` will trigger the issue:

```
java.lang.IllegalStateException: UT000043: Data is already being sent. You must wait for the completion callback to be be invoked before calling send() again
	at io.undertow.io.AsyncSenderImpl.send(AsyncSenderImpl.java:195)
	at io.undertow.io.AsyncSenderImpl.send(AsyncSenderImpl.java:327)
	at io.undertow.io.AsyncSenderImpl.send(AsyncSenderImpl.java:295)
	at act.xio.undertow.UndertowResponse.writeContentPart(UndertowResponse.java:110)
	at act.xio.undertow.UndertowResponseOutput.append(UndertowResponseOutput.java:54)
	at org.osgl.util.Output$Adaptors$5.write(Output.java:499)
	at com.alibaba.fastjson.serializer.SerializeWriter.flush(SerializeWriter.java:2440)
	at com.alibaba.fastjson.serializer.SerializeWriter.close(SerializeWriter.java:474)
	at act.util.JsonUtilConfig.writeJson(JsonUtilConfig.java:254)
	at act.util.JsonUtilConfig.access$000(JsonUtilConfig.java:52)
	at act.util.JsonUtilConfig$JsonWriter.visit(JsonUtilConfig.java:178)
	at act.util.JsonUtilConfig$JsonWriter.visit(JsonUtilConfig.java:54)
	at org.osgl.Osgl$Visitor.apply(Osgl.java:2246)
	at act.util.JsonUtilConfig$1.apply(JsonUtilConfig.java:223)
	at act.util.JsonUtilConfig$1.apply(JsonUtilConfig.java:220)
	at org.osgl.mvc.MvcConfig$4.visit(MvcConfig.java:214)
	at org.osgl.mvc.MvcConfig$4.visit(MvcConfig.java:211)
	at org.osgl.mvc.result.RenderContent.apply(RenderContent.java:217)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:298)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:215)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1505)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
Yes we can reproduce the issue:

```java
public class TestController {
    public static class Foo implements SimpleBean {
        public String bar;
        public String blob;

        public Foo() {
            bar = S.random(5);
            blob = S.random(1024 * 1024 * 2);
        }
    }

    @GetAction("foo")
    @JsonView
    public Iterable<Foo> loadFoos() {
        final AtomicInteger counter = new AtomicInteger(200);
        return new Iterable<Foo>() {
            @Override
            public Iterator<Foo> iterator() {
                return new Iterator<Foo>() {
                    @Override
                    public boolean hasNext() {
                        return counter.decrementAndGet() > 0;
                    }

                    @Override
                    public Foo next() {
                        return new Foo();
                    }

                    @Override
                    public void remove() {
                        E.unsupport();
                    }
                };
            }
        };
    }
}
```

Sending `GET` request to `http://localhost:5406/foo` will trigger the issue
