### ISSUE TITLE
`NoSuchMethodError` with Morphia entity

### ISSUE THREAD

**Issue by moonmanbu** [actframework/actframework#565]
Found on 1.8.2-SNAPSHOT

Error stack:

```
Exception in thread "XNIO-1 task-29" java.lang.NoSuchMethodError: api.ticket.model.Ticket.getMember()Lapi/ticket/model/Member;
	at api.ticket.model.Ticket$Dao.check(Ticket.java:622)
	at api.ticket.controller.TicketController.create(TicketController.java:267)
	at api.ticket.controller.TicketControllerMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:776)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:452)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:512)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:202)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1566)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
@moonmanbu can you add the source code of `Ticket` and `Ticket.Dao` into the issue description?
