### ISSUE TITLE
是否有必要支持List<Order>类型的参数注入

### ISSUE THREAD

**Issue by penguin290** [actframework/actframework#578]
现在ACT是支持接收jsonStr参数注入为Bean类型的，像这样
`@PostAction("/order")
public void createOrder(Order order) {
    orderService.save(order);
}`
请问是否有必要支持接收jsonArray参数注入为List<Order>这种需求？
感觉很多情况下都会有同时传输多条记录的需求的。
仅供参考

**Comment by greenlaw110** [comment]
@penguin290 这个现在不行吗？

**Comment by penguin290** [comment]
我试的时候不可以，不知道是不是用法不对

**Comment by greenlaw110** [comment]
你把 Order 和 POST 数据发上了看看

**Comment by greenlaw110** [comment]
刚刚做的试验：

`Order` entity:

```java
package demo.helloworld;

import act.db.morphia.MorphiaAdaptiveRecord;
import org.mongodb.morphia.annotations.Entity;

@Entity("order")
public class Order extends MorphiaAdaptiveRecord<Order> {

    public String prod;
    public int qty;

}
```

控制器方法：

```java
@PostAction("orders")
public List<Order> batchOrders(List<Order> orders, MorphiaDao<Order> dao) {
    dao.save(orders);
    return orders;
}
```

测试截图:

![image](https://user-images.githubusercontent.com/216930/37929858-c2a3e8fe-318c-11e8-91b9-6da7d0c6e7eb.png)

测试截图2:

![image](https://user-images.githubusercontent.com/216930/37929876-cf170116-318c-11e8-965a-aaf66aa92d28.png)

**Comment by penguin290** [comment]
应该是因为我没有加header

**Comment by penguin290** [comment]
我加了header，还是会报错，和morphia应该没关系吧。如果控制器方法参数类型是com.alibaba.fastjson.JSONArray就没有问题，换成List<User>就会报错。
User和控制器方法如下：
`public class User {
    private String name;
    private String desc;

    public User(String name, String desc) {
        this.name = name;
        this.desc = desc;
    }
    public User() {
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getDesc() {
        return desc;
    }
    public void setDesc(String desc) {
        this.desc = desc;
    }
}`
`@PostAction
    public String addSalPrc(List<User> userList) {
        System.out.println(userList.size());
        return Result.ERROR;
    }`
![image](https://user-images.githubusercontent.com/20235337/37941268-05b303a6-31a0-11e8-9317-3f915610252c.png)
错误信息：
`2018-03-27 09:16:18,559 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-4] - Error handling request: [POST] /test
java.lang.NullPointerException: null
	at act.inject.param.CollectionLoader.resolveInto(CollectionLoader.java:184)
	at act.inject.param.CollectionLoader.load(CollectionLoader.java:134)
	at act.inject.param.JsonParamValueLoader.load(JsonParamValueLoader.java:67)
	at act.inject.param.ScopedParamValueLoader.load(ScopedParamValueLoader.java:49)
	at act.inject.param.ParamValueLoaderService.loadMethodParams(ParamValueLoaderService.java:183)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.params(ReflectedHandlerInvoker.java:837)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:425)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:512)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:202)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:47)
	at act.route.Router$ContextualHandler.handle(Router.java:1505)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by flian** [comment]
你酱紫写肯定报错。。
java泛型是编译擦除的， 运行时肯定不知道类型，然后就悲剧了。。

MorphiaAdaptiveRecord里面肯定有处理的，按这个来在试试。

**Comment by greenlaw110** [comment]
@penguin290 问题在 POST 的方式上面，

方式1 - 成功：
* Content-Type: application/json
* POST 内容在 raw body 中：
![image](https://user-images.githubusercontent.com/216930/37956580-7b96cd12-31f7-11e8-9d97-45db26ec8058.png)

方式2 - 成功：
* Content-Type: [{"key":"Content-Type","value":"application/x-www-form-urlencoded","description":""}]
* POST 内容为 form field：
![image](https://user-images.githubusercontent.com/216930/37956677-ba513092-31f7-11e8-845b-734fcff654fd.png)

方式3 - 失败
* POST 内容作为 query parameters
![image](https://user-images.githubusercontent.com/216930/37956827-1ff8e5f2-31f8-11e8-912f-d33ee984a0ad.png)

**Comment by greenlaw110** [comment]
@penguin290 我可以增加逻辑来处理通过 query parameter 来传递 JSON 内容的，但是对于应用非常不建议采用这种方式。POST 的内容应该是在 body 中

**Comment by penguin290** [comment]
是我用法的问题，既然不是规范的用法，那应该就没必要支持了，专心文档吧 (ง •̀_•́)ง (*•̀ㅂ•́)و

**Comment by greenlaw110** [comment]
@penguin290 好的，谢谢支持
@flian 这个问题和 MorphiaAdaptiveRecord 没有关系，Act 可以支持泛型类型参数绑定的
