### ISSUE TITLE
同时引入beetlsql和ebean插件，程序无法启动

### ISSUE THREAD

**Issue by donald2150** [actframework/actframework#621]

**Comment by greenlaw110** [comment]
@donald2150 错误栈贴出来

**Comment by donald2150** [comment]
Exception in thread "main" org.osgl.exception.UnexpectedIOException: java.util.zip.ZipException: invalid LOC header (bad signature)
	at org.osgl.util.E.ioException(E.java:245)
	at org.osgl.util.IO.copy(IO.java:1501)
	at org.osgl.util.IO.copy(IO.java:1475)
	at act.util.Jars.getBytes(Jars.java:157)
	at act.util.Jars$F$1.apply(Jars.java:188)
	at act.util.Jars$F$1.apply(Jars.java:183)
	at act.util.Jars.scanFile(Jars.java:141)
	at act.util.Jars.scanList(Jars.java:103)
	at act.util.Jars.buildClassNameIndex(Jars.java:66)
	at act.util.Jars.buildClassNameIndex(Jars.java:60)
	at act.boot.app.FullStackAppBootstrapClassLoader.buildIndex(FullStackAppBootstrapClassLoader.java:293)
	at act.boot.app.FullStackAppBootstrapClassLoader.preload(FullStackAppBootstrapClassLoader.java:121)
	at act.boot.app.FullStackAppBootstrapClassLoader.<init>(FullStackAppBootstrapClassLoader.java:82)
	at act.Act.bootstrap(Act.java:917)
	at act.Act.start(Act.java:585)
	at com.moses.AppStart.main(AppStart.java:18)
Caused by: java.util.zip.ZipException: invalid LOC header (bad signature)
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:717)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:419)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.osgl.util.IO.copy(IO.java:1495)
	... 14 more
