### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by dai875939260** [actframework/actframework#627]
1.beetlsql自定义Function无法注册会提示转换异常(ConvertDateEndFunction已实现org.beetl.core.Function)。
> error
```java
Caused by: java.lang.ClassCastException: com.sys.common.beetlsql.ConvertDateEndFunction cannot be cast to org.beetl.core.Function
	at org.beetl.core.GroupTemplate.initFunction(GroupTemplate.java:192)
	at org.beetl.core.GroupTemplate.init(GroupTemplate.java:165)
	at org.beetl.core.GroupTemplate.<init>(GroupTemplate.java:141)
	... 24 common frames omitted
```
2.使用了一个拷贝属性的类也会提示转换异常

> pom

```xml
    <dependency>
      <groupId>com.github.yangtu222</groupId>
      <artifactId>BeanUtils</artifactId>
      <version>1.0.5</version>
    </dependency>
```
> java
```java
    FromBean fromBean = new FromBean();
    fromBean.setId(11L);
    FromBean toBean = new FromBean();
    BeanCopyUtils.copyBean(fromBean, toBean);
```
> error
```java
java.lang.ClassCastException: ghissue.FromBean cannot be cast to ghissue.FromBean
	at com.tuyang.beanutils.internal.javassist.impl.BeanCopier$$javassist0.copyBean(BeanCopier$$javassist0.java)
	at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:238)
	at com.tuyang.beanutils.BeanCopyUtils.copyBean(BeanCopyUtils.java:162)
	at ghissue.AppEntry.route1(AppEntry.java:23)
```

**Comment by greenlaw110** [comment]
act 和 act-beetl 的版本是多少?

**Comment by dai875939260** [comment]
```xml

    <parent>
        <groupId>org.actframework</groupId>
        <artifactId>act-starter-parent</artifactId>
        <version>1.8.7.0</version>
    </parent>

    <dependency>
        <groupId>org.actframework</groupId>
        <artifactId>act</artifactId>
        <version>1.8.8-SNAPSHOT</version>
    </dependency>
```

**Comment by dai875939260** [comment]
找到问题了么，发现beetl的tag也是无法注册，对比一下就发现classloader不一样
![image](https://user-images.githubusercontent.com/6057326/38992491-7c90ab92-4413-11e8-9166-39ae701208b6.png)

**Comment by greenlaw110** [comment]
关于 BeanUtil 的问题, 因为没有设置正确的 `ClassLoader`, 因此导致获得的 Bean 类型和需要的 Bean 类型不在同一个 ClassLoader 中. 我已經向相关项目提交了[一个需求](https://github.com/yangtu222/BeanUtils/issues/8). 在对方实现这个需求之前你需要这样来使用:

```java
    @GetAction("bean-util")
    public FromBean beanUtilTest() {
        ClassPool.getDefault();
        FromBean from = new FromBean();
        from.setId(11L);
        FromBean to = new FromBean();
        Thread currentThread = Thread.currentThread();
        ClassLoader previousClassLoader = currentThread.getContextClassLoader();
        currentThread.setContextClassLoader(Act.app().classLoader());
        try {
            BeanCopyUtils.copyBean(from, to);
        } finally {
            currentThread.setContextClassLoader(previousClassLoader);
        }
        return to;
    }
```

**Comment by greenlaw110** [comment]
Beetlsql 也是有一样的问题. 我也向 beetl 项目提了一个[需求](https://github.com/javamonkey/beetl2.0/issues/346), 在这个需求实现以前, 你对 Beetlsql/Beetl 的使用也需要按照上面类似的方式来使用.

**Comment by dai875939260** [comment]
@greenlaw110 非常感谢解答，期待Act变得越来越强大

**Comment by javamonkey** [comment]
好的，我看看如何改善这个问题
