### ISSUE TITLE
如何使项目的同名class优先生效

### ISSUE THREAD

**Issue by dai875939260** [actframework/actframework#632]
有一种场景，由于第三方jar有bug或者自己想扩展。之前的项目只要建同一个包，一样的类就能实现。
但是act是没办法生效的，有什么办法吗？

**Comment by dai875939260** [comment]
是不是scan_package的问题呢？但是scan_package不能指定多个包名，主类也没办法放到没有包名的目录下，无法从最顶级的包开始扫描。

**Comment by greenlaw110** [comment]
scan_package 可以指定多个报名, 用 ; 分割即可.

不过你这个问题应该和扫描无关, 不管是否扫描你都会面临包名和类名冲突的问题. 对于这样的情况加载具体实现的顺序是无法预测的.

**Comment by dai875939260** [comment]
Act.start("*","package;package" ) 这个会报错，看了代码好像也没支持
```java
// 1
AppDescriptor.of(appName, scanPackage)
// 2 这个分隔符包校验就不通过了
Version.ofPackage(packageName)
// 3 这个分割完取的是第一个
String[] packages = packageName.split(S.COMMON_SEP);
String effectPackageName = packageName;
if (packages.length > 0) {
    effectPackageName = packages[0];
}
```

**Comment by greenlaw110** [comment]
你贴的代码不是 scan_package 真正生效的地方

具体报什么错?

**Comment by dai875939260** [comment]
```java
Exception in thread "main" java.lang.IllegalArgumentException: package name is not valid: com.*;org.*
	at osgl.version.Version.ofPackage(Version.java:285)
	at act.internal.util.AppDescriptor.of(AppDescriptor.java:212)
	at act.Act.start(Act.java:610)
	at com.sys.ActApp.main(ActApp.java:11)
`
``
还有配置文件app.properties配置scan_package是无法生效的

**Comment by greenlaw110** [comment]
下面的代码中 `*` 是错误根源:

```java
Act.start("*","package;package" )
```

正确的例子:

```java
Act.start("My App","com.mycomp.myproj;com.thirdparty.proja" )
```

**Comment by greenlaw110** [comment]
@dai875939260 谢谢你哦, 帮我发现了两个 bug. #633 和 #634 现在都已经修复了. 你可以试用一下 act-1.8.8-SNAPSHOT

**Comment by dai875939260** [comment]
网上说包含新类的路径设置在classpath的最后，是不是就可以覆盖了？因为不了解act的实现机制，不知道从哪下手，设置了多个扫描路径也无法覆盖jar中的类。

**Comment by greenlaw110** [comment]
你的这个问题和 scan package 设置没有关系, scan package 仅仅用于设置需要类增强的包, 而不是需要加载到系统中的包.

**Comment by greenlaw110** [comment]
如果是这种情况你在 resources 下面加一个名为 `act.scan.list` 文件, 把你需要覆盖的类名字写进去, 每个名字写一行, 就像这样:

```
# Put package/class names that needs Act to scan. It can be regular expressions
act\..*Admin
act.app.SingletonFinder
act.app.util.SimpleRestfulServiceBase
act.app.conf.AppConfigPlugin
act.controller.builtin.CliOverHttp
act.db.DbBind
act.handler.builtin.controller.RequestHandlerProxy
act.i18n.TimeZoneResolver
act.i18n.LocaleResolver
act.inject.DependencyInjectorBase
act.inject.genie.GenieInjector
act.Info
act.meta.ClassMetaInfoManager
act.util.AdaptiveRecordCodec
act.validation.ValidationPlugin
act.Zen
act.apidoc.Endpoint.Service
org.osgl.util.FastJsonKvCodec
act.ws.WebSocketAdminConsole
act.job.JobAdmin.WebsocketEndpoints.JobProgress
```
