### ISSUE TITLE
prod下session获取问题

### ISSUE THREAD

**Issue by dai875939260** [actframework/actframework#651]
ActionContext.current().session()，不知道为啥拿不到东西。
```java
ERROR a.x.NetworkHandler@[XNIO-2 task-31] - Error handling network request
java.lang.IllegalStateException: UT000002: The response has already been started
	at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1406)
	at act.xio.undertow.UndertowResponse._setStatusCode(UndertowResponse.java:331)
	at act.ActResponse.status(ActResponse.java:122)
	at act.controller.ResponseCache._setStatusCode(ResponseCache.java:333)
	at act.ActResponse.status(ActResponse.java:122)
	at act.ActResponse.status(ActResponse.java:36)
	at org.osgl.mvc.result.Result.applyStatus(Result.java:228)
	at org.osgl.mvc.result.Result.apply(Result.java:248)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:298)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:234)
	at act.xio.undertow.UndertowRequest$1.handle(UndertowRequest.java:149)
	at io.undertow.io.AsyncReceiverImpl.receiveFullBytes(AsyncReceiverImpl.java:366)
	at io.undertow.io.AsyncReceiverImpl.receiveFullBytes(AsyncReceiverImpl.java:481)
	at act.xio.undertow.UndertowRequest.receiveFullBytesAndProceed(UndertowRequest.java:144)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1025)
	at act.route.Router$ContextualHandler.handle(Router.java:1582)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "XNIO-2 task-31" java.lang.NullPointerException
	at act.handler.event.ResultEvent$2.apply(ResultEvent.java:74)
	at act.handler.event.ResultEvent$2.apply(ResultEvent.java:69)
	at org.osgl.mvc.MvcConfig.applyAfterCommitResultHandler(MvcConfig.java:214)
	at org.osgl.mvc.result.Result.applyAfterCommitHandler(Result.java:236)
	at org.osgl.mvc.result.Result.apply(Result.java:256)
	at act.xio.NetworkHandler.handleException(NetworkHandler.java:219)
	at act.xio.NetworkHandler.access$500(NetworkHandler.java:59)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:181)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
你的 prod 环境是 https 吗? 如果不是, 设置一下 `http.secure=false` 试试

**Comment by greenlaw110** [comment]
@dai875939260 [这里](https://github.com/actframework/archetype-support/blob/master/src/main/resources/archetype-resources/src/main/resources/conf/app.properties)有详尽的配置说明, 你可以参考一下.

另外感觉你的代码可以更简单一点:

首先 `UserInfo` 可以不要了

`login` 的改进版:

```java
@PostAction("login")
public Object login(ActionContext context) {
    context.login("22");
    return C.Map("user", context.username());
}
```

`getUser` 改进版:

```java
public Object getUser(ActionContext context) {
    return C.Map("user", context.username());
}
```

这样的变化对于前端来讲是完全透明的. 

另外, 建议使用 POJO 来定义 `User`, 这样 APIDoc 可以很清楚地标明返回值类型. JSONObject 的实质就是一个 Map, 无法帮助 APIDoc 提供类型信息

**Comment by dai875939260** [comment]
嗯，我程序是用pojo，只是模拟这个issue的时候图方便才这样的。对于这个UserInfo，是因为要在service层获取用户。希望作者可以在文档添加一些最佳实践
