### ISSUE TITLE
A weird `ClassCastException` 

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#660]
Found on act-1.8.7

Source code:

```java
    @GetAction("657/2")
    @JsonView
    public void list2() {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("date", new Date());
        renderJson(C.list(jsonObject));
    }
```

Sending request to the above endpoint will result in `ClassCastException`:

```
[XNIO-1 task-3] ERROR act.handler.builtin.controller.RequestHandlerProxy - Error handling request: [GET] /gh/657/2
java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to java.lang.String
	at org.osgl.mvc.result.RenderJSON$1.content(RenderJSON.java:37)
	at org.osgl.mvc.result.RenderContent.apply(RenderContent.java:265)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:298)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:215)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1027)
	at act.route.Router$ContextualHandler.handle(Router.java:1582)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
Root case analysis:

First, `C.list(jsonObject)` will create a list of single element anything, however, it uses `org.osgl.Lang.Val` to implement the list, which also implement the `org.osgl.Lang.Func0` interface.

Second, `renderJson` put result of `C.list(...)` into JSON result payload

Finally when rendering the response, the logic found the payload is an instance of `org.osgl.Lang.Func0` and in turn call it to generate the String. which is actually a jsonObject
