### ISSUE TITLE
@CacheFor have problems

### ISSUE THREAD

**Issue by pupupu-land** [actframework/actframework#736]
```java
@CacheFor(value = 60 * 60 * 10)
public Result getConfigJson() {
    $.T2 t = readConfigs();
    return renderJson(C.Map("GlobalMap", t._1, "GlobalArray", t._2));
}
```

When running app in prod mode, the response will be:

```
Request Method: GET
Status Code: 200 OK
Remote Address: 10.0.0.41:99
Referrer Policy: no-referrer-when-downgrade

Act-Session-Expires: Fri, 20 Jul 2018 03:28:59 GMT
Connection: keep-alive
Content-Length: 0
Content-Type: application/json
Date: Fri, 20 Jul 2018 02:58:59 GMT
Server: nginx/1.13.8
```

There is no body in the response.

**Comment by greenlaw110** [comment]
@KingOfBug can you please paste the full Response including header and body?

**Comment by KingOfBug** [comment]
# act.properties
`cacheFor.dev=true`

**Comment by KingOfBug** [comment]
It's still the same


# cached
```
   @GetAction("GlobalValues.json")
   @CacheFor(10 * 60 * 60)
    public Map getConfigJson() {
        $.T2 t = readConfigs();
        return C.Map("GlobalMap", t._1, "GlobalArray", t._2);
    }
```


## general
```
Request URL: http://localhost:8080/api/GlobalValues.json
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:8080
Referrer Policy: no-referrer-when-downgrade
```
## response headers

```
act-session-expires: Mon, 30 Jul 2018 02:37:08 GMT
connection: close
content-length: 0
content-type: application/json
date: Mon, 30 Jul 2018 02:07:08 GMT
server: act/1.8.8-RC11
set-cookie: sbinsession=34ff22f8b9e9c67740c727ee1ed3fb52535d5251-___TS%011532918228445%00___ID%016a49e5da-1cdd-4ab4-b429-e92a2c869911; path=/; HttpOnly
Vary: Accept-Encoding
X-Powered-By: Express
```

## request headers

```
GET /api/GlobalValues.json HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json
devid: 0c574aaf91a04c75968e156fda13c9c8
client-version: 1.0.3
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,la;q=0.8,en;q=0.7,id;q=0.6
Cookie: sms-code-12312312=""; gsScrollPos-5=""; gsScrollPos-558=""; gsScrollPos-579=""; _up_oi98="H4sIAAAAAAAAADM3SE5OMU6yTEtKS0tLMU9JSzRJSbNINk9LNDAwMEoyjouPM8q2DKussDRPRmInAdlKoeER5koA8ANF7kEAAAA="; _ujhy_c=H4sIAAAAAAAAAE3ITQ5AMBBA4avIrC1UqY6DWFZGOhXxE2krIeLuSCzs3vfQYqUL2QnhukLZUmUa0WnJUqiSKTetyUdsjh2r/tfu6RM807TQzFBD2Fb2yUwLpLAF9oN9pvgQIkX+OR7rywyuG6bw0ip/AAAA; xio10L=H4sIAAAAAAAAAEsyNzFJNE0yTUtKMU9KSzM0MLZIMTUxNUhOTUwyMzWzjIuPM8q2DKussDRPRWKnANlKMUqGMUpKANVe5oVCAAAA; sbinsession=cdae2daf957e20cd176e9bf1adec786a949fba6a-___TS%011532918212595%00___ID%016a49e5da-1cdd-4ab4-b429-e92a2c869911
```

## service logs

```
2018-07-30 10:14:34,209 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-1] - Error handling request: [GET] /wb/GlobalValues.json
java.lang.NullPointerException: null
        at org.osgl.mvc.result.RenderContent.apply(RenderContent.java:263)
        at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:302)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:216)
        at act.app.ActionContext.proceedWithHandler(ActionContext.java:1054)
        at act.route.Router$ContextualHandler.handle(Router.java:1595)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:159)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
2018-07-30 10:14:34,224 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-1] - error rendering exception handle  result
java.lang.IllegalStateException: UT000002: The response has already been started
        at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1406)
        at act.xio.undertow.UndertowResponse._setStatusCode(UndertowResponse.java:332)
        at act.ActResponse.status(ActResponse.java:123)
        at act.controller.ResponseCache._setStatusCode(ResponseCache.java:333)
        at act.ActResponse.status(ActResponse.java:123)
        at act.ActResponse.status(ActResponse.java:34)
        at org.osgl.mvc.result.Result.applyStatus(Result.java:229)
        at org.osgl.mvc.result.RenderContent.apply(RenderContent.java:254)
        at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:302)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:232)
        at act.app.ActionContext.proceedWithHandler(ActionContext.java:1054)
        at act.route.Router$ContextualHandler.handle(Router.java:1595)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:159)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

# no cached

```
   @GetAction("GlobalValues.json")
    public Map getConfigJson() {
        $.T2 t = readConfigs();
        return C.Map("GlobalMap", t._1, "GlobalArray", t._2);
    }
```


## general
```
Request URL: http://localhost:8080/api/GlobalValues.json
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:8080
Referrer Policy: no-referrer-when-downgrade
```
## response headers

```
act-session-expires: Mon, 30 Jul 2018 02:48:26 GMT
connection: close
Content-Encoding: gzip
content-type: application/json; charset=UTF-8
date: Mon, 30 Jul 2018 02:18:26 GMT
server: act/1.8.8-RC11
set-cookie: sbinsession=4b31a9fa260d399ce56043575bd60fb1d0eb1593-___TS%011532918906407%00___ID%016a49e5da-1cdd-4ab4-b429-e92a2c869911; path=/; HttpOnly
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Powered-By: Express
```

## request headers

```
GET /api/GlobalValues.json HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json
devid: 0c574aaf91a04c75968e156fda13c9c8
client-version: 1.0.3
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,la;q=0.8,en;q=0.7,id;q=0.6
Cookie: sms-code-12312312=""; gsScrollPos-5=""; gsScrollPos-558=""; gsScrollPos-579=""; _up_oi98="H4sIAAAAAAAAADM3SE5OMU6yTEtKS0tLMU9JSzRJSbNINk9LNDAwMEoyjouPM8q2DKussDRPRmInAdlKoeER5koA8ANF7kEAAAA="; _ujhy_c=H4sIAAAAAAAAAE3ITQ5AMBBA4avIrC1UqY6DWFZGOhXxE2krIeLuSCzs3vfQYqUL2QnhukLZUmUa0WnJUqiSKTetyUdsjh2r/tfu6RM807TQzFBD2Fb2yUwLpLAF9oN9pvgQIkX+OR7rywyuG6bw0ip/AAAA; xio10L=H4sIAAAAAAAAAEsyNzFJNE0yTUtKMU9KSzM0MLZIMTUxNUhOTUwyMzWzjIuPM8q2DKussDRPRWKnANlKMUqGMUpKANVe5oVCAAAA; gsScrollPos-574=0; sbinsession=9908dcf0dc1fc7b2033adb567699c67884ce24b0-___TS%011532918673845%00___ID%016a49e5da-1cdd-4ab4-b429-e92a2c869911
```



## service logs

```
nothing..
```
