### ISSUE TITLE
`@Data` enhancement error when Model class has no fields

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#784]
Java source:

```java
@Data
public class Product extends UcModelBase {
}
```

When invoking `Product.hashCode()` it raises `java.lang.NoSuchMethodError`:

```
Exception in thread "XNIO-1 task-1" java.lang.NoSuchMethodError: org.osgl.Osgl.hc()I
	at com.pixolut.underwriter.model.Product.hashCode(Product.java)
	at java.lang.Object.toString(Object.java:236)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.util.AbstractCollection.toString(AbstractCollection.java:462)
	at act.util.$$.toString($$.java:80)
	at act.controller.Controller$Util.inferPrimitiveResult(Controller.java:1572)
	at act.controller.Controller$Util.inferResult(Controller.java:1746)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:873)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:510)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:525)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:206)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1139)
	at act.route.Router$ContextualHandler.handle(Router.java:1601)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
The issue is fixed with https://github.com/osglworks/java-tool/issues/157
