### ISSUE TITLE
Extended request handler method's param not enhanced with `@Named` annotation 

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#819]
Base class:

```java
public abstract class UcDataService<MODEL extends UcModelBase> extends UcDataAgentBase<MODEL> {
    @PostAction
    public JSONObject create(JSONObject data) {
        return fromUcData(
                client.postObject(createUrl(), null, JSON.toJSONString(toUcData(data))),
                JSONObject.class);
    }
}
```

Sub class:

```java
@UrlContext("quotes")
public class QuoteService extends UcDataService<Quote> {
    @Override
    public JSONObject create(JSONObject data) {
        Quote quote = of(data);
        return submit(quote);
    }
    ...
}
```

When it post to `/quotes` with JSON data, it will result in the following exception:

```
java.lang.IllegalArgumentException: value null
	at act.asm.ClassWriter.newConstItem(ClassWriter.java:1057)
	at act.asm.MethodWriter.visitLdcInsn(MethodWriter.java:1126)
	at act.inject.param.JsonDtoClassGenerator.generateSetter(JsonDtoClassGenerator.java:87)
	at act.inject.param.JsonDtoClassGenerator.generateSetters(JsonDtoClassGenerator.java:76)
	at act.inject.param.JsonDtoClassGenerator.generateByteCode(JsonDtoClassGenerator.java:60)
	at act.inject.param.JsonDtoClassGenerator.generate(JsonDtoClassGenerator.java:54)
	at act.inject.param.JsonDtoClassManager.generate(JsonDtoClassManager.java:100)
	at act.inject.param.JsonDtoClassManager.get(JsonDtoClassManager.java:81)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.ensureJsonDtoGenerated(ReflectedHandlerInvoker.java:586)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:478)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:48)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:525)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:206)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1193)
	at act.route.Router$ContextualHandler.handle(Router.java:1601)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
The workaround is manually add `@Named` annotation to the request handler param:

```java
@UrlContext("quotes")
public class QuoteService extends UcDataService<Quote> {
    @Override
    public JSONObject create(@Named("data") JSONObject data) {
        Quote quote = of(data);
        return submit(quote);
    }
    ...
}
```
