### ISSUE TITLE
Using generic typed injection in Controller cause `UnexpectedException` when start up

### ISSUE THREAD

**Issue by donald2150** [actframework/actframework#820]
The error stack trace:

```
org.osgl.exception.UnexpectedException: type not recognized: SERVICE
	at org.osgl.util.E.unexpected(E.java:179)
	at org.osgl.inject.BeanSpec.rawTypeOf(BeanSpec.java:934)
	at org.osgl.inject.BeanSpec.<init>(BeanSpec.java:156)
	at org.osgl.inject.BeanSpec.of(BeanSpec.java:971)
	at act.apidoc.Endpoint.paramInfo(Endpoint.java:435)
	at act.apidoc.Endpoint.exploreParamInfo(Endpoint.java:424)
	at act.apidoc.Endpoint.explore(Endpoint.java:344)
	at act.apidoc.Endpoint.<init>(Endpoint.java:213)
	at act.apidoc.ApiManager$2.visit(ApiManager.java:128)
	at act.route.Router.visit(Router.java:191)
	at act.route.Router.visit(Router.java:197)
	at act.route.Router.visit(Router.java:197)
	at act.route.Router.visit(Router.java:197)
	at act.route.Router.accept(Router.java:178)
	at act.apidoc.ApiManager.load(ApiManager.java:124)
	at act.apidoc.ApiManager.load(ApiManager.java:96)
	at act.apidoc.ApiManager$1.run(ApiManager.java:75)
	at act.job.Job$4.apply(Job.java:387)
	at act.job.Job.doJob(Job.java:348)
	at act.job.Job.run(Job.java:285)
	at act.job.Job$LockableJobList$1.run(Job.java:89)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:476)
	at act.job.Job.doJob(Job.java:348)
	at act.job.Job.run(Job.java:285)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
I can't reproduce the issue.

The interface with type parameter:

```java
public interface Gh820Service<ENTITY_TYPE> {
    ENTITY_TYPE get();
}
```

The String typed implementation of the interface:

```java
public class Gh820StringService implements Gh820Service<String> {
    @Override
    public String get() {
        return "abc";
    }
}
```

The integer typed implementation of the interface:

```java
public class Gh820IntService implements Gh820Service<Integer> {
    @Override
    public Integer get() {
        return 123;
    }
}
```

The typed bean loader:

```java
public class Gh820ServiceLoader implements GenericTypedBeanLoader<Gh820Service> {
    @Override
    public Gh820Service load(BeanSpec spec) {
        List<Type> typeParams = spec.typeParams();
        E.illegalArgumentIf(typeParams.isEmpty(), "Expected type parameters in " + spec);
        Type type = typeParams.get(0);
        if (type == String.class) {
            return new Gh820StringService();
        } else if (type == Integer.class) {
            return new Gh820IntService();
        }
        throw E.unsupport("Unsupported type: " + type);
    }
}
```

The controller:

```java
@UrlContext("820")
public class Gh820 extends LogSupport {

    @Inject
    private Gh820Service<String> stringService;

    @Inject
    private Gh820Service<Integer> intService;

    @GetAction("string")
    public String getString() {
        return stringService.get();
    }

    @GetAction("int")
    public int getInt() {
        return intService.get();
    }

}
```

The test scripts:

```yaml
Scenario(GH820):
  description: "[820] Using generic typed injection in Controller cause `UnexpectedException`"
  interactions:
  - description: Access String Service
    request:
      get: /820/string
    response:
      json:
        result: abc
  - description: Access Int Service
    request:
      get: /820/int
    response:
      json:
        result: 123
```

**Comment by donald2150** [comment]
public class BaseController<T, SERVICE extends BaseService> {

    @Inject
    protected SERVICE service;


    public SERVICE getService() {
        return service;
    }
}

public class SysDemoController extends BaseController<SysDemo, SysDemoService> {
         @GetAction("sample")
         public List<SysDemo> sample(){
               return this.getService().dosomething();
         }

}

**Comment by greenlaw110** [comment]
Found the root cause: it is in the API doc building process.
