### ISSUE TITLE
远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by Saharaqie** [actframework/actframework#830]
服务器段请求处理方法：
```java
    @PostAction("/rest/{url}")
    public String rest(String url,String dataJson) {
        System.out.println(dataJson);
        System.out.println(url);
        return url;
    }
```

客户端请求方法：
```java
Map<String, Object> map = new HashMap<String, Object>();
map.put("dataJson","{\"appKey\":\"123\",\"body\":\"invoke\"}");
String post = HttpUtil.post("http://192.168.18.4:5460/rest/t1", map);
System.out.println(post);
```

客户端打印 `t1`，服务端打印 `{"appKey":"123","body":"invoke"}` 和 `t1`

服务端报错：

```java
20:30:04.567 [XNIO-1 I/O-2] DEBUG io.undertow.request.io - Error reading request
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.xnio.nio.NioSocketConduit.read(NioSocketConduit.java:319)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
```

**Comment by greenlaw110** [comment]
@Saharaqie HttpUtil 是什么?

**Comment by Saharaqie** [comment]
hutool的http请求工具

**Comment by looly** [comment]
请使用：

```java
HttpRequest.post("http://XXXX").body(jsonString).execute().body();
```

**Comment by greenlaw110** [comment]
I can't reproduce this issue

**Comment by Saharaqie** [comment]
目前我能确认的是hutool应该是没有问题的，我试了httpClient和jdkHttpURLConnection请求，服务端都会报错，header中加上Connection=close可以避免报错，但是postman请求的时候Connection=Keep-Alive，服务端也不会报错，我感觉应该是java中调用结束后线程就释放了，服务端握手失败报错，而postman可能是类似于浏览器，会保持连接，所以不会报错。目前的解决办法是在服务端返回的response中添加header：Connection=close，主动断开连接
