### ISSUE TITLE
FastJson exception when serialize ACT error message

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#841]
```java
    @PostAction("login")
    @ResponseStatus(200)
    public Map<String, String> login(String id, String password, AuthType type, ActionContext context) {
        User user = authenticate(id, password, type);
        unauthorizedIf(null == user);
        forbiddenIf(State.NA != user.state && State.NORMAL != user.state, context.i18n(Messages.LOGIN_FORBIDDEN, User.KEY, id));
        ...
    }
```
When code execute at line 'unauthorizedIf(null == user)', Act will throw lots of FastJson exception.
```log
Exception in thread "XNIO-1 task-1" java.lang.StackOverflowError
	at com.alibaba.fastjson.serializer.SerializeWriter.writeStringWithDoubleQuote(SerializeWriter.java:877)
	at com.alibaba.fastjson.serializer.SerializeWriter.writeString(SerializeWriter.java:2113)
	at com.alibaba.fastjson.serializer.StringCodec.write(StringCodec.java:46)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:373)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.writeClassName(JavaBeanSerializer.java:486)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:191)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:120)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:298)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:411)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:120)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:298)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:411)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:120)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:298)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:411)
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:120)
	at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:298)
       ...
```
Once act return error object, it will throw this kind of exception.

**Comment by leeaee** [comment]
It seems if we add return Map object, it will throw fastjson exception. You can run fellow code to reproduce the issue.

```java
    @GetAction("test")
    @ResponseStatus(200)
    public Map<String, String> test() {
        unauthorizedIf(true);
        return C.Map("token", "aabbcc");
    }
```
