### ISSUE TITLE
启动过程找不到MySQL jar包抛出异常最后还是启动完成了

### ISSUE THREAD

**Issue by licardoY** [actframework/actframework#842]
```
2018-09-17 11:27:35,358 ERROR c.a.d.p.DruidDataSource@[jobs-thread-2] - {dataSource-1} init error
java.sql.SQLException: com.mysql.jdbc.Driver
	at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:600)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:815)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1227)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1223)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
	at org.beetl.sql.core.DefaultConnectionSource.doGetConnectoin(DefaultConnectionSource.java:75)
	at org.beetl.sql.core.DefaultConnectionSource.getMaster(DefaultConnectionSource.java:47)
	at org.beetl.sql.core.DefaultConnectionSource.getMetaData(DefaultConnectionSource.java:118)
	at org.beetl.sql.core.db.MetadataManager.initDefaultSchema(MetadataManager.java:272)
	at org.beetl.sql.core.db.MetadataManager.<init>(MetadataManager.java:33)
	at org.beetl.sql.core.SQLManager.initMetadataManager(SQLManager.java:247)
	at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:179)
	at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:155)
	at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:150)
	at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:137)
	at act.db.beetlsql.BeetlSqlService.dataSourceProvided(BeetlSqlService.java:75)
	at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:210)
	at act.db.sql.SqlDbService.access$000(SqlDbService.java:51)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:90)
	at act.db.sql.SqlDbService$1.on(SqlDbService.java:77)
	at act.event.EventBus.callOn(EventBus.java:1312)
	at act.event.EventBus.access$1400(EventBus.java:53)
	at act.event.EventBus$4.run(EventBus.java:1341)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:460)
	at act.job.Job.doJob(Job.java:345)
	at act.job.Job.run(Job.java:282)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at act.boot.app.FullStackAppBootstrapClassLoader.loadClass(FullStackAppBootstrapClassLoader.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:598)
	... 32 common frames omitted
2018-09-17 11:27:35,456 ERROR a.a.App@[jobs-thread-2] - Block issue encountered
org.osgl.exception.ConfigurationException: Error init SQL db service
	at org.osgl.util.E.invalidConfiguration(E.java:300)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:116)
	at act.db.sql.SqlDbService$1.on(SqlDbService.java:77)
	at act.event.EventBus.callOn(EventBus.java:1312)
	at act.event.EventBus.access$1400(EventBus.java:53)
	at act.event.EventBus$4.run(EventBus.java:1341)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:460)
	at act.job.Job.doJob(Job.java:345)
	at act.job.Job.run(Job.java:282)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.beetl.sql.core.BeetlSQLException: java.sql.SQLException: com.mysql.jdbc.Driver
	at org.beetl.sql.core.DefaultConnectionSource.doGetConnectoin(DefaultConnectionSource.java:79)
	at org.beetl.sql.core.DefaultConnectionSource.getMaster(DefaultConnectionSource.java:47)
	at org.beetl.sql.core.DefaultConnectionSource.getMetaData(DefaultConnectionSource.java:118)
	at org.beetl.sql.core.db.MetadataManager.initDefaultSchema(MetadataManager.java:272)
	at org.beetl.sql.core.db.MetadataManager.<init>(MetadataManager.java:33)
	at org.beetl.sql.core.SQLManager.initMetadataManager(SQLManager.java:247)
	at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:179)
	at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:155)
	at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:150)
	at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:137)
	at act.db.beetlsql.BeetlSqlService.dataSourceProvided(BeetlSqlService.java:75)
	at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:210)
	at act.db.sql.SqlDbService.access$000(SqlDbService.java:51)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:90)
	... 14 common frames omitted
Caused by: java.sql.SQLException: com.mysql.jdbc.Driver
	at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:600)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:815)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1227)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1223)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
	at org.beetl.sql.core.DefaultConnectionSource.doGetConnectoin(DefaultConnectionSource.java:75)
	... 27 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at act.boot.app.FullStackAppBootstrapClassLoader.loadClass(FullStackAppBootstrapClassLoader.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:598)
	... 32 common frames omitted
2018-09-17 11:27:35,482 INFO  o.xnio@[main] - XNIO version 3.3.8.Final
2018-09-17 11:27:35,502 INFO  o.x.nio@[main] - XNIO NIO Implementation Version 3.3.8.Final
2018-09-17 11:27:35,588 INFO  a.Act@[main] - network client hooked on port: 5460
2018-09-17 11:27:35,591 INFO  a.Act@[main] - CLI server started on port: 5461
2018-09-17 11:27:35,593 INFO  a.Act@[main] - app is ready at: http://192.168.2.73:5460
2018-09-17 11:27:35,593 INFO  a.Act@[main] - it takes 4515ms to start the app
```

**Comment by licardoY** [comment]
访问: [localhost:5460](url)

```
HTTP/1.1 500 Server Error

Server Error
 - org.osgl.exception.ConfigurationException: Error init SQL db service

错误栈
at act.db.sql.SqlDbService$1.run(SqlDbService.java:116)
at act.db.sql.SqlDbService$1.on(SqlDbService.java:77)
at act.event.EventBus.callOn(EventBus.java:1312)
at act.event.EventBus.access$1400(EventBus.java:53)
at act.event.EventBus$4.run(EventBus.java:1341)
at act.job.JobManager$ContextualJob$1.apply(JobManager.java:460)
at act.job.Job.doJob(Job.java:345)
at act.job.Job.run(Job.java:282)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by org.beetl.sql.core.BeetlSQLException: java.sql.SQLException: com.mysql.jdbc.Driver
at org.beetl.sql.core.DefaultConnectionSource.doGetConnectoin(DefaultConnectionSource.java:79)
at org.beetl.sql.core.DefaultConnectionSource.getMaster(DefaultConnectionSource.java:47)
at org.beetl.sql.core.DefaultConnectionSource.getMetaData(DefaultConnectionSource.java:118)
at org.beetl.sql.core.db.MetadataManager.initDefaultSchema(MetadataManager.java:272)
at org.beetl.sql.core.db.MetadataManager.<init>(MetadataManager.java:33)
at org.beetl.sql.core.SQLManager.initMetadataManager(SQLManager.java:247)
at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:179)
at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:155)
at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:150)
at org.beetl.sql.core.SQLManager.<init>(SQLManager.java:137)
at act.db.beetlsql.BeetlSqlService.dataSourceProvided(BeetlSqlService.java:75)
at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:210)
at act.db.sql.SqlDbService.access$000(SqlDbService.java:51)
at act.db.sql.SqlDbService$1.run(SqlDbService.java:90)
at act.db.sql.SqlDbService$1.on(SqlDbService.java:77)
Caused by java.sql.SQLException: com.mysql.jdbc.Driver
at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:600)
at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:815)
at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1227)
at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1223)
at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
at org.beetl.sql.core.DefaultConnectionSource.doGetConnectoin(DefaultConnectionSource.java:75)
at org.beetl.sql.core.DefaultConnectionSource.getMaster(DefaultConnectionSource.java:47)
Caused by java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
at java.lang.ClassLoader.findClass(ClassLoader.java:530)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at act.boot.app.FullStackAppBootstrapClassLoader.loadClass(FullStackAppBootstrapClassLoader.java:312)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:598)
at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:815)

```
