### ISSUE TITLE
when I add "mahout-math" & "mahout-core "& "hadoop-core" to pom.xml demo app will throw some errors

### ISSUE THREAD

**Issue by 18807600203** [actframework/actframework#85]
as  title
```
       _           _              _    _        _  
 |_|  |_  |   |   / \    \    /  / \  |_)  |   | \ 
 | |  |_  |_  |_  \_/     \/\/   \_/  | \  |_  |_/ 
                                                   
                powered by ActFramework R1.0.0-8707

 version: 2.0.0-SNAPSHOT
scan pkg: demo.helloworld
base dir: E:\java_program\UMonitor
     pid: 1
 profile: dev
    mode: DEV

     zen: Special cases aren't special enough to break the rules. 
          Although practicality beats purity.

Exception in thread "main" org.osgl.exception.UnexpectedException: Unknown error captured starting the application
	at org.osgl.util.E.unexpected(E.java:104)
	at act.boot.app.RunApp.start(RunApp.java:70)
	at act.Act.start(Act.java:610)
	at demo.helloworld.HelloWorldApp.main(HelloWorldApp.java:24)
Caused by: java.lang.IncompatibleClassChangeError: javax.el.BeanELResolver and javax.el.BeanELResolver$SoftConcurrentHashMap disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1227)
	at java.lang.Class.getEnclosingClass(Class.java:1269)
	at java.lang.Class.getCanonicalName(Class.java:1384)
	at act.util.ClassInfoRepository.canonicalName(ClassInfoRepository.java:93)
	at act.boot.app.FullStackAppBootstrapClassLoader.cache(FullStackAppBootstrapClassLoader.java:239)
	at act.boot.app.FullStackAppBootstrapClassLoader.pluginClasses(FullStackAppBootstrapClassLoader.java:74)
	at act.Act.pluginClasses(Act.java:160)
	at act.plugin.PluginScanner.scan(PluginScanner.java:25)
	at act.Act.loadPlugins(Act.java:653)
	at act.Act.start(Act.java:293)
	at act.Act.startApp(Act.java:269)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at act.boot.app.RunApp.start(RunApp.java:64)
	... 2 more
```

pom.xml 
```
<dependency>
		    <groupId>org.apache.mahout</groupId>
		    <artifactId>mahout-math</artifactId>
		    <version>0.12.2</version>
		    <exclusions>
				<exclusion>
					<artifactId>com.google.guava</artifactId>
					<groupId>guava</groupId>
				</exclusion>
			</exclusions>
</dependency>	
<dependency>
		    <groupId>org.apache.mahout</groupId>
		    <artifactId>mahout-core</artifactId>
		    <version>0.9</version>
		    <exclusions>
				<exclusion>
					 <groupId>org.apache.mahout</groupId>
		   			 <artifactId>mahout-math</artifactId>
				</exclusion>
			</exclusions>
</dependency>	 
<dependency>
		    <groupId>org.apache.hadoop</groupId>
		    <artifactId>hadoop-core</artifactId>
		    <version>1.2.1</version>
</dependency>
```

**Comment by greenlaw110** [comment]
It should caused by incompatible class versions in different jars. See [What causes java.lang.IncompatibleClassChangeError?](http://stackoverflow.com/questions/1980452/what-causes-java-lang-incompatibleclasschangeerror).

I run a `mvn dependency:tree` on your pom configuration and found this:
![image](https://cloud.githubusercontent.com/assets/216930/23820509/fdec4280-066d-11e7-93c1-3ac0064f5466.png)


So ActFramework use [ReflectASM](https://github.com/EsotericSoftware/reflectasm) to accelerate the method invocation. That library relies on objectweb asm 5, while hadoop core relies on jersey which require asm 3. That's the root cause of your issue. 

ObjectWeb suggest the libraries use asm to relocate the package, which is exactly what act-asm project for to avoid the conflict. I think it might be good to raise an issue to ReflectASM project. But anyway this issue is out of the scope of ActFramework

**Comment by greenlaw110** [comment]
I've submitted the issue to ReflectASM: https://github.com/EsotericSoftware/reflectasm/issues/54

**Comment by 18807600203** [comment]
Thank you for you answer
