### ISSUE TITLE
dev模式下，热加载报错

### ISSUE THREAD

**Issue by donald2150** [actframework/actframework#850]
@Every("10s")
	public void test(){
	    System.out.println( "---------test---------" );
	    App.instance().getInstance( SysDemoService.class );
    }

错误信息
org.osgl.inject.InjectException: Cannot instantiate interface com.moses.sys.service.SysJobService
	at org.osgl.inject.Genie.findProvider(Genie.java:925)
	at org.osgl.inject.Genie.getProvider(Genie.java:587)
	at org.osgl.inject.Genie.get(Genie.java:558)
	at act.inject.genie.GenieInjector.get(GenieInjector.java:75)
	at act.app.App.getInstance(App.java:1012)
	at com.moses.util.JobUtil$1.run(JobUtil.java:19)
	at cn.hutool.cron.task.RunnableTask.execute(RunnableTask.java:17)
	at cn.hutool.cron.TaskExecutor.run(TaskExecutor.java:33)

**Comment by greenlaw110** [comment]
不能重现啊. 一开始用了你那种方式, 中途改成这样的:

![image](https://user-images.githubusercontent.com/216930/45904754-4a0f6d00-be31-11e8-9c28-892d31b0f212.png)

Console log:

![image](https://user-images.githubusercontent.com/216930/45904746-4380f580-be31-11e8-8005-6e110955c72a.png)

完全看不到错误栈的影子

**Comment by greenlaw110** [comment]
@donald2150 你能提供 `SysJobService` 的代码吗?
