### ISSUE TITLE
TFB project failure on eclipselink and hibernate permutations

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#854]
[Error log](https://tfb-status.techempower.com/unzip/results.2018-09-25-09-14-04-763.zip/results/20180921195039/act-eclipselink-pgsql/run/act-eclipselink-pgsql.log)

```
act-eclipselink-pgsql:         _  ___   _   _                _           _    _      
act-eclipselink-pgsql:   /\   /    |   |_  |_)   /\   |\/|  |_  \    /  / \  |_)  |/ 
act-eclipselink-pgsql:  /--\  \_   |   |   | \  /--\  |  |  |_   \/\/   \_/  | \  |\ 
act-eclipselink-pgsql:             powered by ActFramework[m v1.8.8-RC12-SNAPSHOT-5d2f7
act-eclipselink-pgsql:  version: r1.8.8g-180921_2043
act-eclipselink-pgsql: scan pkg: 
act-eclipselink-pgsql: base dir: /act/target/dist
act-eclipselink-pgsql:      pid: 8
act-eclipselink-pgsql:  profile: eclipselink_pgsql
act-eclipselink-pgsql:     mode: PROD
act-eclipselink-pgsql:      zen: There should be one-- and preferably only one --obvious way to do it.
act-eclipselink-pgsql:           Although that way may not be obvious at first unless you're Dutch.
act-eclipselink-pgsql: Exception in thread "main" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6c50dd79 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7f796fb0[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
act-eclipselink-pgsql: 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
act-eclipselink-pgsql: 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
act-eclipselink-pgsql: 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
act-eclipselink-pgsql: 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
act-eclipselink-pgsql: 	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:632)
act-eclipselink-pgsql: 	at act.job.JobManager.now(JobManager.java:101)
act-eclipselink-pgsql: 	at act.job.JobManager.now(JobManager.java:97)
act-eclipselink-pgsql: 	at act.job.JobManager.processDelayedJob(JobManager.java:293)
act-eclipselink-pgsql: 	at act.job.JobManager.on(JobManager.java:249)
act-eclipselink-pgsql: 	at act.job.JobManager.on(JobManager.java:219)
act-eclipselink-pgsql: 	at act.job.JobManager.on(JobManager.java:215)
act-eclipselink-pgsql: 	at act.util.SimpleBean$ByteCodeScanner$SimpleBeanByteCodeVisitor.visitEnd(SimpleBean.java:242)
act-eclipselink-pgsql: 	at act.asm.ClassVisitor.visitEnd(ClassVisitor.java:317)
act-eclipselink-pgsql: 	at act.asm.ClassVisitor.visitEnd(ClassVisitor.java:317)
act-eclipselink-pgsql: 	at act.asm.ClassVisitor.visitEnd(ClassVisitor.java:317)
act-eclipselink-pgsql: 	at act.view.rythm.RythmTransformerScanner$Visitor.visitEnd(RythmTransformerScanner.java:104)
act-eclipselink-pgsql: 	at act.asm.ClassVisitor.visitEnd(ClassVisitor.java:317)
act-eclipselink-pgsql: 	at act.asm.ClassVisitor.visitEnd(ClassVisitor.java:317)
act-eclipselink-pgsql: 	at act.asm.ClassVisitor.visitEnd(ClassVisitor.java:317)
act-eclipselink-pgsql: 	at act.asm.ClassVisitor.visitEnd(ClassVisitor.java:317)
act-eclipselink-pgsql: 	at act.asm.ClassReader.accept(ClassReader.java:701)
act-eclipselink-pgsql: 	at act.asm.ClassReader.accept(ClassReader.java:506)
act-eclipselink-pgsql: 	at act.app.AppClassLoader.scanByteCode(AppClassLoader.java:284)
act-eclipselink-pgsql: 	at act.app.AppClassLoader.scan(AppClassLoader.java:242)
act-eclipselink-pgsql: 	at act.app.App.scanAppCodes(App.java:1632)
act-eclipselink-pgsql: 	at act.app.App.refresh(App.java:675)
act-eclipselink-pgsql: 	at act.app.AppManager.load(AppManager.java:75)
act-eclipselink-pgsql: 	at act.app.AppManager$_F$1.visit(AppManager.java:143)
act-eclipselink-pgsql: 	at act.app.AppManager$_F$1.visit(AppManager.java:139)
act-eclipselink-pgsql: 	at org.osgl.Lang$Visitor.apply(Lang.java:2459)
act-eclipselink-pgsql: 	at org.osgl.Lang$Visitor.apply(Lang.java:2449)
act-eclipselink-pgsql: 	at act.app.AppScanner.scan(AppScanner.java:91)
act-eclipselink-pgsql: 	at act.app.AppScanner.scan(AppScanner.java:71)
act-eclipselink-pgsql: 	at act.app.AppManager.loadSingleApp(AppManager.java:53)
act-eclipselink-pgsql: 	at act.Act.startup(Act.java:318)
act-eclipselink-pgsql: 	at act.Act.startup(Act.java:1141)
act-eclipselink-pgsql: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
act-eclipselink-pgsql: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
act-eclipselink-pgsql: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
act-eclipselink-pgsql: 	at java.lang.reflect.Method.invoke(Method.java:498)
act-eclipselink-pgsql: 	at org.osgl.Lang.invokeStatic(Lang.java:7971)
act-eclipselink-pgsql: 	at act.Act.bootstrap(Act.java:1047)
act-eclipselink-pgsql: 	at act.Act.start(Act.java:638)
act-eclipselink-pgsql: 	at com.techempower.act.AppEntry.main(AppEntry.java:31)
```

**Comment by greenlaw110** [comment]
The error is caused by incompatible change in act-1.8.8-RC12-SNAPSHOT. The fix is done with https://github.com/greenlaw110/FrameworkBenchmarks/commit/e7de46f3c82011f129be2d8256d1ab5f7189be4b
