### ISSUE TITLE
ACT start failed with GenieModuleScanner

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#875]
Sometimes ACT start will be failed at GenieModuleScanner. This failed exception appear random.
```trace
2018-10-10 10:47:34.472 [main] WARN  act.job.Job - error executing job GenieModuleScanner:addModuleClass:act.aaa.AAAModule
java.lang.IllegalStateException: null
	at org.osgl.util.E.illegalStateIf(E.java:726)
	at act.inject.genie.GenieInjector.addModule(GenieInjector.java:157)
	at act.inject.genie.GenieInjector.addModuleClass(GenieInjector.java:325)
	at act.inject.genie.GenieModuleScanner$2.run(GenieModuleScanner.java:53)
	at act.job.Job$4.apply(Job.java:394)
	at act.job.Job.doJob(Job.java:355)
	at act.job.Job.run(Job.java:292)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:100)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:81)
	at act.job.Job.runPrecedenceJobs(Job.java:371)
	at act.job.Job.run(Job.java:287)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:436)
	at act.event.EventBus.callOn(EventBus.java:1310)
	at act.event.EventBus.callOn(EventBus.java:1332)
	at act.event.EventBus.callOn(EventBus.java:1362)
	at act.event.EventBus._emit(EventBus.java:1223)
	at act.event.EventBus.emit(EventBus.java:679)
	at act.app.App.emit(App.java:1169)
	at act.app.App.refresh(App.java:711)
	at act.app.AppManager.load(AppManager.java:75)
	at act.app.AppManager$_F$1.visit(AppManager.java:143)
	at act.app.AppManager$_F$1.visit(AppManager.java:139)
	at org.osgl.Lang$Visitor.apply(Lang.java:2459)
	at org.osgl.Lang$Visitor.apply(Lang.java:2449)
	at act.app.AppScanner.scan(AppScanner.java:91)
	at act.app.AppScanner.scan(AppScanner.java:71)
	at act.app.AppManager.loadSingleApp(AppManager.java:53)
	at act.Act.startup(Act.java:319)
	at act.Act.startup(Act.java:1188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Lang.invokeStatic(Lang.java:7971)
	at act.Act.bootstrap(Act.java:1094)
	at act.Act.start(Act.java:743)
	at com.lingxian.probe.App.main(App.java:12)
2018-10-10 10:47:35.281 [main] WARN  act.job.Job - error executing job GenieModuleScanner:addModuleClass:act.db.jpa.JPAModule
java.lang.IllegalStateException: null
	at org.osgl.util.E.illegalStateIf(E.java:726)
	at act.inject.genie.GenieInjector.addModule(GenieInjector.java:157)
	at act.inject.genie.GenieInjector.addModuleClass(GenieInjector.java:325)
	at act.inject.genie.GenieModuleScanner$2.run(GenieModuleScanner.java:53)
	at act.job.Job$4.apply(Job.java:394)
	at act.job.Job.doJob(Job.java:355)
	at act.job.Job.run(Job.java:292)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:100)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:81)
	at act.job.Job.runPrecedenceJobs(Job.java:371)
	at act.job.Job.run(Job.java:287)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:436)
	at act.event.EventBus.callOn(EventBus.java:1310)
	at act.event.EventBus.callOn(EventBus.java:1332)
	at act.event.EventBus.callOn(EventBus.java:1362)
	at act.event.EventBus._emit(EventBus.java:1223)
	at act.event.EventBus.emit(EventBus.java:679)
	at act.app.App.emit(App.java:1169)
	at act.app.App.refresh(App.java:711)
	at act.app.AppManager.load(AppManager.java:75)
	at act.app.AppManager$_F$1.visit(AppManager.java:143)
	at act.app.AppManager$_F$1.visit(AppManager.java:139)
	at org.osgl.Lang$Visitor.apply(Lang.java:2459)
	at org.osgl.Lang$Visitor.apply(Lang.java:2449)
	at act.app.AppScanner.scan(AppScanner.java:91)
	at act.app.AppScanner.scan(AppScanner.java:71)
	at act.app.AppManager.loadSingleApp(AppManager.java:53)
	at act.Act.startup(Act.java:319)
	at act.Act.startup(Act.java:1188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Lang.invokeStatic(Lang.java:7971)
	at act.Act.bootstrap(Act.java:1094)
	at act.Act.start(Act.java:743)
	at com.lingxian.probe.App.main(App.java:12)
```

**Comment by leeaee** [comment]
There still another failed in ACT startup.

```trace
2018-10-10 20:46:52.429 [main] WARN  act.job.Job - error executing job ClassFinder[org.osgl.inject.Module@act.inject.genie.GenieInjector.foundModule]
java.lang.IllegalStateException: null
	at org.osgl.util.E.illegalStateIf(E.java:726)
	at act.inject.genie.GenieInjector.addModule(GenieInjector.java:157)
	at act.inject.genie.GenieInjector.addModuleClass(GenieInjector.java:325)
	at act.inject.genie.GenieInjector.foundModule(GenieInjector.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Lang.invokeMethod(Lang.java:8133)
	at org.osgl.Lang.invokeStatic(Lang.java:7931)
	at act.util.ClassFinderData$By$3.visit(ClassFinderData.java:101)
	at act.util.ClassFinderData$By$3.visit(ClassFinderData.java:83)
	at org.osgl.Lang$Visitor.apply(Lang.java:2459)
	at org.osgl.Lang$14.visit(Lang.java:2564)
	at org.osgl.Lang$Visitor.apply(Lang.java:2459)
	at org.osgl.Lang$Visitor.apply(Lang.java:2449)
	at act.util.ClassNode.visitTree(ClassNode.java:178)
	at act.util.ClassNode.visitSubTree(ClassNode.java:185)
	at act.util.ClassNode.visitSubTree(ClassNode.java:225)
	at act.util.ClassNode.visitSubTree(ClassNode.java:238)
	at act.util.ClassFinderData$By$2.tryFind(ClassFinderData.java:64)
	at act.util.ClassFinderData$By.find(ClassFinderData.java:108)
	at act.util.ClassFinderData$1.run(ClassFinderData.java:216)
	at act.job.Job$4.apply(Job.java:394)
	at act.job.Job.doJob(Job.java:355)
	at act.job.Job.run(Job.java:292)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:100)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:81)
	at act.job.Job.runPrecedenceJobs(Job.java:371)
	at act.job.Job.run(Job.java:287)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:436)
	at act.event.EventBus.callOn(EventBus.java:1310)
	at act.event.EventBus.callOn(EventBus.java:1332)
	at act.event.EventBus.callOn(EventBus.java:1362)
	at act.event.EventBus._emit(EventBus.java:1223)
	at act.event.EventBus.emit(EventBus.java:679)
	at act.app.App.emit(App.java:1170)
	at act.app.App.refresh(App.java:712)
	at act.app.AppManager.load(AppManager.java:75)
	at act.app.AppManager$_F$1.visit(AppManager.java:143)
	at act.app.AppManager$_F$1.visit(AppManager.java:139)
	at org.osgl.Lang$Visitor.apply(Lang.java:2459)
	at org.osgl.Lang$Visitor.apply(Lang.java:2449)
	at act.app.AppScanner.scan(AppScanner.java:91)
	at act.app.AppScanner.scan(AppScanner.java:71)
	at act.app.AppManager.loadSingleApp(AppManager.java:53)
	at act.Act.startup(Act.java:319)
	at act.Act.startup(Act.java:1188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.osgl.Lang.invokeStatic(Lang.java:7971)
	at act.Act.bootstrap(Act.java:1094)
	at act.Act.start(Act.java:743)
	at com.lingxian.probe.App.main(App.java:12)
```
