### ISSUE TITLE
It randomly found request handler parameters are not enhanced with `@Named` annotation

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#879]
ActFramework require every parameter of a request handler to be named in order to do parameter binding, the name is either done by explicitly adding `@Named` annotation or enhanced by actframework bytecode enhancer to add it.

With the introducing of #872 we have done a bunch of changes in app bootstrap process, and it raised a few issues. This issue is also one of them. The symptom is when app is running in PROD mode, it randomly found certain request handler params are not enhanced with `@Named` annotation and triggered error like:

```
java.lang.NullPointerException: null
        at act.inject.param.JsonDtoClassManager$3.compare(JsonDtoClassManager.java:249)
        at act.inject.param.JsonDtoClassManager$3.compare(JsonDtoClassManager.java:246)
        at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.util.TimSort.sort(TimSort.java:220)
        at java.util.Arrays.sort(Arrays.java:1512)
        at java.util.ArrayList.sort(ArrayList.java:1462)
        at java.util.Collections.sort(Collections.java:175)
        at act.inject.param.JsonDtoClassManager.beanSpecs(JsonDtoClassManager.java:143)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:299)
        at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createControllerAction(ReflectedHandlerInvoker.java:1083)
        at act.Act$Mode.createRequestHandler(Act.java:170)
        at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:419)
        at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:343)
        at act.handler.builtin.controller.RequestHandlerProxy.corsSpec(RequestHandlerProxy.java:536)
        at act.handler.DelegateRequestHandler.corsSpec(DelegateRequestHandler.java:71)
        at act.handler.OptionsInfoBase.createHandler(OptionsInfoBase.java:77)
        at act.handler.OptionsInfoBase.optionHandler(OptionsInfoBase.java:53)
        at act.route.Router.getInvoker(Router.java:210)
        at act.xio.NetworkHandler.handle(NetworkHandler.java:133)
        at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:48)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:147)
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:93)
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:52)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129)
        at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)
```

**Comment by greenlaw110** [comment]
The root cause the issue is identified:

* the Exception is triggered while sending OPTION request, rather than the POST request
* the first OPTION request is handled in a different way, rather than handle it in a dispatching thread, it is handled directly in the IO thread, and the current logic failed to set the current `ActionContext`in this scenario.
* when ReflectedHandlerInvoker is initialized for handling the OPTION request, it relies on current `ActionContext` to resolve the binding parameter (annotation) correctly:
![image](https://user-images.githubusercontent.com/216930/46845120-c3452300-ce25-11e8-8b37-46c2b8d5b892.png)

**Comment by greenlaw110** [comment]
The reason this doesn't happen in dev mode:
* dev mode will run api doc compiling and process the handlers before hand

The reason (suspected) that it happens intermittently in UAT:
* When it starts the app, a pending POST request is hit before the OPTION request and process the handler before OPTION request triggered processing
