### ISSUE TITLE
setting "act.session.encrypt" error

### ISSUE THREAD

**Issue by mezongzi** [actframework/actframework#91]
![image](https://cloud.githubusercontent.com/assets/7627445/23884073/7caeedd2-08a5-11e7-98a7-f887766986f6.png)

After I enabled `act.session.encrypt` I got the following error:

![image](https://cloud.githubusercontent.com/assets/7627445/23884088/9b841b2e-08a5-11e7-853c-faa40e1be814.png)

**Comment by greenlaw110** [comment]
Can't reproduce. Here is my case:
![image](https://cloud.githubusercontent.com/assets/216930/23946464/9c8c4968-09ce-11e7-824b-5de3a0418375.png)

**Comment by mezongzi** [comment]
13:01:06.851 [XNIO-1 task-17] ERROR a.a.u.AppCrypto - Cannot encrypt/decrypt! Please download Java Crypto Extension pack from Oracle: http://www.oracle.com/technetwork/java/javase/tech/index-jsp-136007.html
13:01:06.851 [XNIO-1 task-17] ERROR a.h.b.c.RequestHandlerProxy - Error handling request
org.osgl.exception.UnexpectedException: java.security.InvalidKeyException: Illegal key size
	at org.osgl.util.E.unexpected(E.java:100)
	at org.osgl.util.Crypto.encryptAES(Crypto.java:183)
	at act.app.util.AppCrypto.encrypt(AppCrypto.java:71)
	at act.app.App.encrypt(App.java:659)
	at act.util.SessionManager$CookieResolver.dissolveIntoCookieContent(SessionManager.java:321)
	at act.util.SessionManager$CookieResolver.dissolveSession(SessionManager.java:217)
	at act.util.SessionManager.dissolveSession(SessionManager.java:78)
	at act.app.ActionContext.dissolveSession(ActionContext.java:849)
	at act.app.ActionContext.dissolve(ActionContext.java:697)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:241)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:177)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:27)
	at act.route.Router$ContextualHandler.handle(Router.java:935)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1034)
	at javax.crypto.Cipher.implInit(Cipher.java:800)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:859)
	at javax.crypto.Cipher.init(Cipher.java:1370)
	at javax.crypto.Cipher.init(Cipher.java:1301)
	at org.osgl.util.Crypto.encryptAES(Crypto.java:174)
	... 15 common frames omitted
13:01:06.852 [XNIO-1 task-17] ERROR a.a.u.AppCrypto - Cannot encrypt/decrypt! Please download Java Crypto Extension pack from Oracle: http://www.oracle.com/technetwork/java/javase/tech/index-jsp-136007.html
13:01:06.852 [XNIO-1 task-17] ERROR a.h.b.c.RequestHandlerProxy - error rendering exception handle  result
org.osgl.exception.UnexpectedException: java.security.InvalidKeyException: Illegal key size
	at org.osgl.util.E.unexpected(E.java:100)
	at org.osgl.util.Crypto.encryptAES(Crypto.java:183)
	at act.app.util.AppCrypto.encrypt(AppCrypto.java:71)
	at act.app.App.encrypt(App.java:659)
	at act.util.SessionManager$CookieResolver.dissolveIntoCookieContent(SessionManager.java:321)
	at act.util.SessionManager$CookieResolver.dissolveSession(SessionManager.java:217)
	at act.util.SessionManager.dissolveSession(SessionManager.java:78)
	at act.app.ActionContext.dissolveSession(ActionContext.java:849)
	at act.app.ActionContext.dissolve(ActionContext.java:697)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:241)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:189)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:27)
	at act.route.Router$ContextualHandler.handle(Router.java:935)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1034)
	at javax.crypto.Cipher.implInit(Cipher.java:800)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:859)
	at javax.crypto.Cipher.init(Cipher.java:1370)
	at javax.crypto.Cipher.init(Cipher.java:1301)
	at org.osgl.util.Crypto.encryptAES(Crypto.java:174)
	... 15 common frames omitted
13:01:06.853 [XNIO-1 task-17] ERROR a.a.u.AppCrypto - Cannot encrypt/decrypt! Please download Java Crypto Extension pack from Oracle: http://www.oracle.com/technetwork/java/javase/tech/index-jsp-136007.html
13:01:06.853 [XNIO-1 task-17] ERROR a.x.NetworkHandler - Error handling network request
org.osgl.exception.UnexpectedException: java.security.InvalidKeyException: Illegal key size
	at org.osgl.util.E.unexpected(E.java:100)
	at org.osgl.util.Crypto.encryptAES(Crypto.java:183)
	at act.app.util.AppCrypto.encrypt(AppCrypto.java:71)
	at act.app.App.encrypt(App.java:659)
	at act.util.SessionManager$CookieResolver.dissolveIntoCookieContent(SessionManager.java:321)
	at act.util.SessionManager$CookieResolver.dissolveSession(SessionManager.java:217)
	at act.util.SessionManager.dissolveSession(SessionManager.java:78)
	at act.app.ActionContext.dissolveSession(ActionContext.java:849)
	at act.app.ActionContext.dissolve(ActionContext.java:697)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:241)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:192)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:27)
	at act.route.Router$ContextualHandler.handle(Router.java:935)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1034)
	at javax.crypto.Cipher.implInit(Cipher.java:800)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:859)
	at javax.crypto.Cipher.init(Cipher.java:1370)
	at javax.crypto.Cipher.init(Cipher.java:1301)
	at org.osgl.util.Crypto.encryptAES(Crypto.java:174)
	... 15 common frames omitted
Exception in thread "XNIO-1 task-17" java.lang.NullPointerException
	at act.util.ActContext$Base.config(ActContext.java:149)
	at act.app.ActionContext.applyGlobalCorsSetting(ActionContext.java:415)
	at act.app.ActionContext.applyCorsSpec(ActionContext.java:407)
	at act.handler.event.ResultEvent$1.apply(ResultEvent.java:41)
	at act.handler.event.ResultEvent$1.apply(ResultEvent.java:37)
	at org.osgl.mvc.MvcConfig.applyBeforeCommitResultHandler(MvcConfig.java:150)
	at org.osgl.mvc.result.Result.applyBeforeCommitHandler(Result.java:133)
	at org.osgl.mvc.result.Result.apply(Result.java:152)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by greenlaw110** [comment]
This is caused by missing JCE (Java Cryptography Extension). Please google `java8 jce` and find the link on oracle webside, then follow the instruction to download and install
