### ISSUE TITLE
Hot reload is broken in R1.8.8 version

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#921]
Error stack:

```
2018-11-01 21:04:26,812 ERROR a.x.NetworkHandler@[XNIO-1 I/O-1] - Error refreshing app
org.osgl.inject.InjectException: Cannot instantiate class org.osgl.inject.loader.TypedElementLoader
	at org.osgl.inject.Genie.findProvider(Genie.java:933)
	at org.osgl.inject.Genie.getProvider(Genie.java:595)
	at org.osgl.inject.Genie.get(Genie.java:566)
	at org.osgl.inject.ElementLoaderProvider.loaders(ElementLoaderProvider.java:163)
	at org.osgl.inject.ElementLoaderProvider.<init>(ElementLoaderProvider.java:120)
	at org.osgl.inject.ElementLoaderProvider.<init>(ElementLoaderProvider.java:41)
	at org.osgl.inject.ElementLoaderProvider$CollectionLoaderProvider.<init>(ElementLoaderProvider.java:85)
	at org.osgl.inject.ElementLoaderProvider.decorate(ElementLoaderProvider.java:154)
	at org.osgl.inject.Genie.decorate(Genie.java:955)
	at org.osgl.inject.Genie.findProvider(Genie.java:943)
	at org.osgl.inject.Genie.fieldInjector(Genie.java:1074)
	at org.osgl.inject.Genie.fieldInjectors(Genie.java:1062)
	at org.osgl.inject.Genie.buildFieldMethodInjector(Genie.java:1001)
	at org.osgl.inject.Genie.buildProvider(Genie.java:981)
	at org.osgl.inject.Genie.findProvider(Genie.java:939)
	at org.osgl.inject.Genie.getProvider(Genie.java:595)
	at org.osgl.inject.Genie.get(Genie.java:566)
	at act.inject.genie.GenieInjector.get(GenieInjector.java:81)
	at act.app.App.getInstance(App.java:1053)
	at act.view.rythm.RythmView.createEngine(RythmView.java:183)
	at act.view.rythm.RythmView.getEngine(RythmView.java:105)
	at act.view.rythm.RythmView.registerBuiltInTransformer(RythmView.java:194)
	at act.app.App.registerBuiltInRythmTransformers(App.java:1668)
	at act.app.App.initViewManager(App.java:1663)
	at act.app.App.access$500(App.java:102)
	at act.app.App$3.run(App.java:733)
	at act.app.App.refresh(App.java:749)
	at act.app.App.refresh(App.java:592)
	at act.app.App.checkUpdates(App.java:471)
	at act.xio.NetworkHandler.handle(NetworkHandler.java:102)
	at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:48)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
```

**Comment by greenlaw110** [comment]
fixed along with #931
