### ISSUE TITLE
`Unable to find the overwritten method of Xxx` issue on 1.8.8

### ISSUE THREAD

**Issue by pcmanjack** [actframework/actframework#925]
After upgrading to act-starter-parent from 1.8.8.6 to 1.8.8.8, it reports the following error when hitting the `GET /` endpoint:

```
2018-11-02 17:26:39,361 ERROR i.u.request@[XNIO-1 I/O-1] - UT005071: Undertow request failed HttpServerExchange{ GET / request {Connection=[keep-alive], Accept=[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8], Accept-Language=[zh-CN,zh;q=0.9,en;q=0.8], Accept-Encoding=[gzip, deflate], DNT=[1], User-Agent=[Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36], Upgrade-Insecure-Requests=[1], Host=[192.168.1.205:8000]} response {Server=[act_admin]}}
org.osgl.exception.UnexpectedException: Unable to find the overwritten method of public org.osgl.mvc.result.Result com.act.admin.controllers.MainController.home(org.osgl.http.H$Session)
	at org.osgl.util.E.unexpected(E.java:179)
	at act.util.ReflectedInvokerHelper.overwrittenMethodOf(ReflectedInvokerHelper.java:100)
	at act.util.ReflectedInvokerHelper.requestHandlerMethodParamAnnotations(ReflectedInvokerHelper.java:81)
	at act.inject.param.JsonDtoClassManager.extractBeanSpec(JsonDtoClassManager.java:207)
	at act.inject.param.JsonDtoClassManager.beanSpecs(JsonDtoClassManager.java:142)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.<init>(ReflectedHandlerInvoker.java:300)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.createControllerAction(ReflectedHandlerInvoker.java:1089)
	at act.Act$Mode.createRequestHandler(Act.java:149)
	at act.handler.builtin.controller.RequestHandlerProxy.generateHandlers(RequestHandlerProxy.java:421)
	at act.handler.builtin.controller.RequestHandlerProxy.ensureAgentsReady(RequestHandlerProxy.java:345)
	at act.handler.builtin.controller.RequestHandlerProxy.express(RequestHandlerProxy.java:280)
	at act.handler.DelegateRequestHandler.express(DelegateRequestHandler.java:42)
	at act.xio.NetworkHandler.handle(NetworkHandler.java:206)
	at act.xio.undertow.ActHttpHandler.handleRequest(ActHttpHandler.java:48)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:336)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
Disconnected from the target VM, address: '127.0.0.1:60741', transport: 'socket'
```

The project site：https://github.com/shaofangjie/act_admin

**Comment by greenlaw110** [comment]
## context

ActFramework look for action annotation (e.g. `@GetAction`) on the request handler method, if the annotation is not found then it look for the method defined in super class.

# Root cause

There is no Action annotation on request handling method in the given project. Route mappings are all defined in routes.conf file. This cause the failure locating the request handler method in super class.

## Fix

We need to check if the request handler is coming from Action annotation or not (e.g. route configuration) while looking for the request method declaration
