### ISSUE TITLE
post error

### ISSUE THREAD

**Issue by zczhao** [actframework/actframework#93]
2017-03-15 00:08:13 [XNIO-1 I/O-4] DEBUG i.u.r.io - Error reading request
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.xnio.nio.NioSocketConduit.read(NioSocketConduit.java:286)
        at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:156)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:134)
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:58)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:559)

**Comment by greenlaw110** [comment]
From the error stack it looks like the browser disconnected while server is accepting the request. We need you to provide more details to help understand the issue and it's context, literally the following information:

1. what's your action handler method signature
2. what's the URL path of this post
3. what data have you posted
4. list out the reproduce steps

**Comment by greenlaw110** [comment]
@zczhao can you please come back to my questions?

**Comment by greenlaw110** [comment]
Closed as no response from issue submitter. Please feel free to resumit the issue with details information if needed
