### ISSUE TITLE
@AutoConfig failed with Guava cache

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#930]
Here is the code.

```java
import act.app.conf.AutoConfig;
import com.google.common.cache.Cache;
import com.google.common.cache.CacheBuilder;
import com.lingxian.domain.entity.User;
import org.osgl.$;
import org.osgl.util.Const;

import java.util.concurrent.TimeUnit;

@AutoConfig("user.sms")
public class Caches {

    private static final Const<Long> PERIOD = $.constant();

    public static Cache<String, Long> smsesCache = CacheBuilder.newBuilder().maximumSize(3000).expireAfterWrite(PERIOD.get(), TimeUnit.SECONDS).build();
    public static Cache<String, User> userSmsesCache = CacheBuilder.newBuilder().maximumSize(30000).expireAfterWrite(PERIOD.get(), TimeUnit.SECONDS).build();

}
```

Start up error:
```log
2018-11-03 19:27:21.016 [jobs-thread-2] ERROR act.app.App - Block issue encountered
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.osgl.Lang.classForName(Lang.java:7304)
	at act.app.conf.AutoConfigPlugin$1$1.on(AutoConfigPlugin.java:58)
	at act.event.EventBus.callOn(EventBus.java:1310)
	at act.event.EventBus.callOn(EventBus.java:1332)
	at act.event.EventBus.callOn(EventBus.java:1362)
	at act.event.EventBus._emit(EventBus.java:1223)
	at act.event.EventBus.emit(EventBus.java:679)
	at act.app.App.emit(App.java:1176)
	at act.app.App$4.run(App.java:760)
	at act.job.Job$4.apply(Job.java:394)
	at act.job.Job.doJob(Job.java:355)
	at act.job.Job.run(Job.java:292)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:100)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:81)
	at act.job.Job.runPrecedenceJobs(Job.java:371)
	at act.job.Job.run(Job.java:287)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:436)
	at act.event.EventBus.callOn(EventBus.java:1310)
	at act.event.EventBus.callOn(EventBus.java:1332)
	at act.event.EventBus.callOn(EventBus.java:1362)
	at act.event.EventBus._emit(EventBus.java:1223)
	at act.event.EventBus.emit(EventBus.java:679)
	at act.app.App.emit(App.java:1176)
	at act.app.DbServiceManager$1.run(DbServiceManager.java:78)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:132)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:126)
	at act.event.EventBus.callOn(EventBus.java:1310)
	at act.event.EventBus.callOn(EventBus.java:1332)
	at act.event.EventBus.callOn(EventBus.java:1367)
	at act.event.EventBus._emitWithOnceBus(EventBus.java:1283)
	at act.event.EventBus.emit(EventBus.java:847)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:112)
	at act.job.Job$4.apply(Job.java:394)
	at act.job.Job.doJob(Job.java:355)
	at act.job.Job.run(Job.java:292)
	at act.job.Job$LockableJobList$1.run(Job.java:96)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:483)
	at act.job.Job.doJob(Job.java:355)
	at act.job.Job.run(Job.java:292)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at com.lingxian.drone.cache.Caches.<clinit>(Caches.java:17)
	... 48 common frames omitted
2018-11-03 19:27:21.021 [jobs-thread-2] ERROR act.app.App - Block issue encountered
org.osgl.exception.ConfigurationException: Error init SQL db service
	at org.osgl.util.E.invalidConfiguration(E.java:300)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:117)
	at act.job.Job$4.apply(Job.java:394)
	at act.job.Job.doJob(Job.java:355)
	at act.job.Job.run(Job.java:292)
	at act.job.Job$LockableJobList$1.run(Job.java:96)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:483)
	at act.job.Job.doJob(Job.java:355)
	at act.job.Job.run(Job.java:292)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: act.boot.app.BlockIssueSignal: null
```

**Comment by greenlaw110** [comment]
Problem with your code is you are trying to initialize cache directly during class initialization, by when the `PERIOD` was not commissioned by auto config mechanism. Try to init your cache variable using something like this:

```java
@AutoConfig("user.sms")
public class Caches {

    private static final Const<Long> PERIOD = $.constant();

    public static Cache<String, Long> smsesCache;
    public static Cache<String, User> userSmsesCache;

    @OnAppStart
    public void initCaches() {
        smsesCache = CacheBuilder.newBuilder().maximumSize(3000).expireAfterWrite(PERIOD.get(), TimeUnit.SECONDS).build();
        userSmsesCache = CacheBuilder.newBuilder().maximumSize(30000).expireAfterWrite(PERIOD.get(), TimeUnit.SECONDS).build();
    }
}
```
