### ISSUE TITLE
`java.lang.IllegalArgumentException` upon starting BSBF project

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#931]
After migrating actframework from 1.8.7 to 1.8.8 in BSBF project. I got the error stacking starting the app:

```
java.lang.IllegalArgumentException: Cannot infer type parameter implementation on act.db.morphia.MorphiaDao against act.db.DaoBase
	at org.osgl.util.Generics.typeParamImplementations(Generics.java:72)
	at act.db.DaoBase.exploreTypes(DaoBase.java:125)
	at act.db.DaoBase.<init>(DaoBase.java:50)
	at act.db.morphia.MorphiaDaoBase.<init>(MorphiaDaoBase.java:53)
	at act.db.morphia.MorphiaDao.<init>(MorphiaDao.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.osgl.inject.Genie$9.get(Genie.java:1012)
	at org.osgl.inject.Genie$7.get(Genie.java:965)
	at org.osgl.inject.ScopedProvider.get(ScopedProvider.java:50)
	at org.osgl.inject.Genie$FieldInjector.applyTo(Genie.java:463)
	at org.osgl.inject.Genie$9.get(Genie.java:1018)
	at org.osgl.inject.Genie$7.get(Genie.java:965)
	at org.osgl.inject.ScopedProvider.get(ScopedProvider.java:50)
	at org.osgl.inject.Genie.get(Genie.java:566)
	at act.inject.genie.GenieInjector.get(GenieInjector.java:81)
	at act.app.App.getInstance(App.java:1053)
	at act.app.DbServiceManager$1$1.visit(DbServiceManager.java:101)
	at act.app.DbServiceManager$1$1.visit(DbServiceManager.java:83)
	at org.osgl.Lang$Visitor.apply(Lang.java:2460)
	at org.osgl.Lang$14.visit(Lang.java:2565)
	at org.osgl.Lang$Visitor.apply(Lang.java:2460)
	at org.osgl.Lang$Visitor.apply(Lang.java:2450)
	at act.util.ClassNode.visitTree(ClassNode.java:178)
	at act.util.ClassNode.visitSubTree(ClassNode.java:185)
	at act.util.ClassNode.visitTree(ClassNode.java:176)
	at act.util.ClassNode.visitSubTree(ClassNode.java:185)
	at act.util.ClassNode.visitTree(ClassNode.java:176)
	at act.util.ClassNode.visitSubTree(ClassNode.java:185)
	at act.util.ClassNode.visitTree(ClassNode.java:176)
	at act.util.ClassNode.visitSubTree(ClassNode.java:185)
	at act.util.ClassNode.visitTree(ClassNode.java:176)
	at act.util.ClassNode.visitSubTree(ClassNode.java:185)
	at act.util.ClassNode.visitTree(ClassNode.java:176)
	at act.util.ClassNode.visitTree(ClassNode.java:171)
	at act.util.ClassNode.visitPublicNotAbstractTreeNodes(ClassNode.java:293)
	at act.app.DbServiceManager$1.initDao(DbServiceManager.java:83)
	at act.app.DbServiceManager$1.run(DbServiceManager.java:77)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:132)
	at act.app.DbServiceManager$3.on(DbServiceManager.java:126)
	at act.event.EventBus.callOn(EventBus.java:1310)
	at act.event.EventBus.callOn(EventBus.java:1332)
	at act.event.EventBus.callOn(EventBus.java:1367)
	at act.event.EventBus._emitWithOnceBus(EventBus.java:1283)
	at act.event.EventBus.emit(EventBus.java:847)
	at act.db.morphia.MorphiaService.init(MorphiaService.java:133)
	at act.db.morphia.MorphiaService$1.run(MorphiaService.java:96)
	at act.job.Job$4.apply(Job.java:394)
	at act.job.Job.doJob(Job.java:355)
	at act.job.Job.run(Job.java:292)
	at act.job.Job$LockableJobList$1.run(Job.java:96)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:483)
	at act.job.Job.doJob(Job.java:355)
	at act.job.Job.run(Job.java:292)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.osgl.util.Generics.typeParamImplementations(Generics.java:178)
	at org.osgl.util.Generics.typeParamImplementations(Generics.java:70)
	... 63 common frames omitted
```

**Comment by greenlaw110** [comment]
## First triage

Initially I thought it was the problem of Genie and created https://github.com/osglworks/java-di/issues/42.

After doing some research, I realized there is nothing can be done on Genie for this issue.

## Root case

I have changed `MorphiaService` initializing to async model in act-1.8.8, and this behavior change is the root cause of the issue.

The main point is the time when `DbServiceManager.daoInitializer` is called. When all db service is initialized in sync mode, the `daoInitializer` is called upon `SINGLETON_PROVISIONED` event, while if any db service is initialized in async mode, then `daoInitializer` is called when `DbServiceInitialized` event triggered.

Problem in `MorphiaService` is it initialize itself upon `DEPENDENCY_INJECTOR_LOADED` event, and triggered `DbServiceInitialized` event immediately after initialized.  Unfortunately `DEPENDENCY_INJECTOR_LOADED` event is triggered before `DEPENDENCY_INJECTOR_PROVISIONED`, by when the `MorphiaDaoLoader` is registered. And time sequence issue is the direct cause of the BSBF app startup issue

**Comment by greenlaw110** [comment]
Problem with act-1.8.8 implementation:

In order to accelerate dev mode app load performance, it moved the following logic to the time when `DB_SVC_PROVISIONED` is triggered:

```java
initJsonDtoClassManager();
initParamValueLoaderManager();
initMailerConfigManager();

// setting context class loader here might lead to memory leaks
// and cause weird problems as class loader been set to thread
// could be switched to handling other app in ACT or still hold
// old app class loader instance after the app been refreshed
// - Thread.currentThread().setContextClassLoader(classLoader());

initHttpConfig();
initViewManager();

// let's any emit the dependency injector loaded event
// in case some other service depend on this event.
// If any DI plugin e.g. guice has emitted this event
// already, it doesn't matter we emit the event again
// because once app event is consumed the event listeners
// are cleared
emit(DEPENDENCY_INJECTOR_PROVISIONED);
emit(SINGLETON_PROVISIONED);
registerMetricProvider();
config().preloadConfigurations();
initSessionManager();
```

This change caused an issue that the above code is never invoked if `DbService` is correctly implemented, i.e. it emits `DbServiceInitalized` upon `SINGLETON_PROVISIONED`, which is not going to happen before `DbServiceInitialized` event. This caused a circular reference problem between `DbServiceInitalized` and `SINGLETON_PROVISIONED` event.

**Comment by greenlaw110** [comment]
It shows this is also the root cause of #921
