### ISSUE TITLE
Automate test failure

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#932]
Found on: 1.8.9

When running `mvn clean compile act:test`, it failed with the following error:

```
2018-11-04 22:37:28,548 ERROR a.x.NetworkHandler@[XNIO-1 task-1] - Error handling network request
java.lang.NullPointerException: null
	at act.app.ActionContext.resolveSession(ActionContext.java:1503)
	at act.app.ActionContext.resolve(ActionContext.java:1281)
	at act.route.Router$ContextualHandler.handle(Router.java:1598)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:165)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-11-04 22:37:28,577 ERROR a.x.NetworkHandler@[XNIO-1 task-2] - Error handling network request
```

**Comment by greenlaw110** [comment]
If run `mvn clean compile act:run` and then go to browser to hit `/~/test`, the automate test will run good
