### ISSUE TITLE
Handle `Error` encountered processing incoming request

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#933]
The BSBF project was good in the beginning. However once it run for a certain amount of time. It starts to reject requests. Here the error logs 

```
2018-11-05_14:52:37.813 [XNIO-1 task-11] ERROR a.h.b.controller.RequestHandlerProxy - error handling request: [PUT]/api/v1/admin/kits/5a2a72ab18ba58ffb7417fb7
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at act.xio.undertow.HttpStringCache.get(HttpStringCache.java:96)
        at act.xio.undertow.UndertowRequest.header(UndertowRequest.java:106)
        at act.security.CSRF$Spec.retrieveCsrfToken(CSRF.java:220)
        at act.security.CSRF$Spec.setCookieAndRenderArgs(CSRF.java:196)
        at act.app.ActionContext.setCsrfCookieAndRenderArgs(ActionContext.java:876)
        at act.app.ActionContext.dissolve(ActionContext.java:1348)
        at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:315)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:231)
        at act.app.ActionContext.proceedWithHandler(ActionContext.java:1304)
        at act.route.Router$ContextualHandler.handle(Router.java:1603)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:165)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
2018-11-05_14:52:56.111 [XNIO-1 task-8] ERROR a.h.b.controller.RequestHandlerProxy - error handling request: [GET]/api/v1/admin/accounts
act.exception.ActException: Render template[com/pixolut/colgate/bsbf/admin/AccountService/accounts] not found
        at act.view.RenderTemplate.apply(RenderTemplate.java:73)
        at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:322)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:231)
        at act.app.ActionContext.proceedWithHandler(ActionContext.java:1304)
        at act.route.Router$ContextualHandler.handle(Router.java:1603)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:165)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
2018-11-05_14:56:40.656 [XNIO-1 task-2] ERROR a.h.b.controller.RequestHandlerProxy - error handling request: [GET]/api/v1/admin/accounts
act.exception.ActException: Render template[com/pixolut/colgate/bsbf/admin/AccountService/accounts] not found
        at act.view.RenderTemplate.apply(RenderTemplate.java:73)
        at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:322)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:231)
        at act.app.ActionContext.proceedWithHandler(ActionContext.java:1304)
        at act.route.Router$ContextualHandler.handle(Router.java:1603)
        at act.xio.NetworkHandler$3.run(NetworkHandler.java:165)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
2018-11-05_14:56:44.158 [XNIO-1 task-5] ERROR a.h.b.controller.RequestHandlerProxy - error handling request: [GET]/api/v1/admin/kits
act.exception.ActException: Render template[com/pixolut/colgate/bsbf/admin/KitService/list] not found
        at act.view.RenderTemplate.apply(RenderTemplate.java:73)
        at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:322)
        at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:231)
        at act.app.ActionContext.proceedWithHandler(ActionContext.java:1304)
        at act.route.Router$ContextualHandler.handle(Router.java:1603)
```

**Comment by greenlaw110** [comment]
There are even more strange symptom observed when trying to reproduce this issue in local dev mode: the Route table cleared which is triggered by failure to detect all the source code.

**Comment by greenlaw110** [comment]
Root cause:

When AdaptiveRecord (e.g. the Kit) has a hidden property with boolean type and `false` as the value. Calling Morphia to save the record will trigger `StackOverflowError`, I believe this error destroyed the JVM state including stacks, and result in all the weird things happening on SIT and local.

The problem with ActFramework is it failed to capture the Error (which is **not** an Exception), and things like `StackOverflowError` just get swallowed, and there is even no sign of that in the console, while the problem already destroyed the entire JVM.

The fix shall be capture the `Error`, print the message and shutdown app
