### ISSUE TITLE
`UnexpectedException` with `Controller.Util.download(URL)` call

### ISSUE THREAD

**Issue by greenlaw110** [actframework/actframework#944]
Source code:

```java
@LoadResource("postcode-report.xls")
private URL defaultPostCodeReport

@GetAction("postcodes")
@CacheFor(value = 60 * 60 * 12, id = CACHE_FOR_ID)
public void downloadReport(ActionContext context, String tk) {
    if (Act.isProd()) {
        verifyDownloadToken(tk);
    }
   Controller.Util.download(defaultPostCodeReport);
}
```

Error stack

```
org.osgl.exception.UnexpectedException: org.osgl.exception.UnexpectedIOException: java.io.IOException: Stream closed
	at org.osgl.util.E.unexpected(E.java:189)
	at org.osgl.mvc.result.RenderBinary.apply(RenderBinary.java:257)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:329)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:231)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1304)
	at act.route.Router$ContextualHandler.handle(Router.java:1649)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:165)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.osgl.exception.UnexpectedIOException: java.io.IOException: Stream closed
	at org.osgl.util.E.ioException(E.java:254)
	at org.osgl.util.IO$WriteStageBase.to(IO.java:275)
	at org.osgl.util.IO.copy(IO.java:1876)
	at org.osgl.util.IO.copy(IO.java:1851)
	at org.osgl.util.IO.readContent(IO.java:1501)
	at org.osgl.storage.impl.SObject$InputStreamSObject.asByteArray(SObject.java:781)
	at act.xio.undertow.UndertowResponse.writeBinary(UndertowResponse.java:147)
	at act.xio.undertow.UndertowResponse.writeBinary(UndertowResponse.java:54)
	at act.controller.ResponseCache.writeBinary(ResponseCache.java:217)
	at org.osgl.mvc.result.RenderBinary.apply(RenderBinary.java:252)
	... 8 common frames omitted
Caused by: java.io.IOException: Stream closed
	at java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:67)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:142)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.osgl.util.IO$InputStreamWriteStage.doWriteTo(IO.java:465)
	at org.osgl.util.IO$WriteStageBase.to(IO.java:273)
	... 16 common frames omitted
2018-11-13 20:36:40,279 ERROR a.h.b.c.RequestHandlerProxy@[XNIO-1 task-2] - error rendering exception handle result
java.lang.IllegalStateException: UT000002: The response has already been started
	at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1406)
	at act.xio.undertow.UndertowResponse._setStatusCode(UndertowResponse.java:209)
	at act.ActResponse.status(ActResponse.java:142)
	at act.controller.ResponseCache._setStatusCode(ResponseCache.java:345)
	at act.ActResponse.status(ActResponse.java:142)
	at act.ActResponse.status(ActResponse.java:38)
	at org.osgl.mvc.result.Result.applyStatus(Result.java:229)
	at org.osgl.mvc.result.Result.apply(Result.java:249)
	at act.handler.builtin.controller.RequestHandlerProxy.onResult(RequestHandlerProxy.java:329)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:248)
	at act.app.ActionContext.proceedWithHandler(ActionContext.java:1304)
	at act.route.Router$ContextualHandler.handle(Router.java:1649)
	at act.xio.NetworkHandler$3.run(NetworkHandler.java:165)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
Root cause is inside the `ResponseCache`:

```java
@Override
public H.Response writeBinary(ISObject binary) {
    byte[] ba = binary.asByteArray();
    ByteBuffer buffer = ByteBuffer.allocateDirect(ba.length);
    buffer.put(ba);
    buffer.flip();
    this.buffer = buffer;
    realResponse.writeBinary(binary);
    this.wroteDirectly = true;
    return this;
}
```

In the above code, `binary` is get from URL.openStream(), which is backed by an `InputStream`, and the stream is consumed when calling `binary.asByteArray()`, when it is referenced in `realResponse.writeBinary(binary);` it will trigger the `UnexpectedException`
