### ISSUE TITLE
CamelCase named fields in MySQL datasource caused "Unknown column" SQL Exception

### ISSUE THREAD

**Issue by piaohao** [actframework/actframework#95]
Create an new Database
```sql
create database test;
```

And a table

```sql
create table car_info(
id int not null primary key,
imgUrl varchar(1024)
);
```
The Model class

```java
@Entity
@Table(name="car_info")
public class CarInfo implements SimpleBean{
  @Id
  public Integer id;
  public String imgUrl;
}
```
The controller
```java
public class MainApp extends Controller.util{
  @Inject
  private EbeanDao<Integer,CarInfo> dao;

  @GetAction("/list")
  public Iterable<CarInfo> list(){
    return dao.findAll();
  }

  public static void main(String[] args){
    Act.start("Ebean Mysql");
  }
}
```
db.properties

```properties
db.driver=com.mysql.jdbc.Driver
db.url=jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
db.username=root
db.password=root
```
Run the application and I will get the following error:

```
15:57:14.487 [XNIO-1 task-11] ERROR a.h.b.c.RequestHandlerProxy - Error handling request
javax.persistence.PersistenceException: Query threw SQLException:Unknown column 't0.img_url' in 'field list' 
Bind values:[] 
Query was:
select t0.id c0, t0.img_url c1 from car_info t0 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:680)
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:660)
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findIterate(CQueryEngine.java:209)
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findIterate(DefaultOrmQueryEngine.java:84)
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findIterate(OrmQueryRequest.java:336)
	at com.avaje.ebeaninternal.server.core.DefaultServer.findIterate(DefaultServer.java:1310)
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findIterate(DefaultOrmQuery.java:1114)
	at act.db.ebean.EbeanQuery.findIterate(EbeanQuery.java:275)
	at act.db.ebean.EbeanQuery.fetch(EbeanQuery.java:150)
	at act.db.ebean.EbeanDao.findAll(EbeanDao.java:150)
	at com.ridersunion.App.list(App.java:20)
	at com.ridersunion.AppMethodAccess.invoke(Unknown Source)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:389)
	at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:198)
	at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:22)
	at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:425)
	at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:167)
	at act.handler.DelegateRequestHandler.handle(DelegateRequestHandler.java:27)
	at act.route.Router$ContextualHandler.handle(Router.java:932)
	at act.xio.NetworkHandler$1.run(NetworkHandler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't0.img_url' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1062)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4208)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4140)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2597)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2758)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2826)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2212)
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQueryWithOption(CQuery.java:355)
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQueryForwardOnly(CQuery.java:301)
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findIterate(CQueryEngine.java:175)
	... 20 common frames omitted
```

**Comment by greenlaw110** [comment]
Add the following configuration to your `db.properties` file:

```properties
db.namingconvention=com.avaje.ebean.config.MatchingNamingConvention
```

It will sort out the issue
